### ISSUE TITLE
index.js MAX

### ISSUE THREAD

**Issue by Maxbroooooo** [Androz2091/discord-giveaways#1]
```
const Discord = require('discord.js')
var config = require("./config.json");
const client = new Discord.Client()

settings = {
    prefix: config.prefix,
    
};
giveaways = require("discord-giveaways"),

client.on("ready", () => {
    giveaways.launch(client, {
        updateCountdownEvery: 5000,
        botsCanWin: false,
        ignoreIfHasPermission: [
            "MANAGE_MESSAGES",
            "MANAGE_GUILD",
            "ADMINISTRATOR"
        ],
        embedColor: "#FAAC58",
        reaction: "🎉"
    });
});
  client.on("message", (message) => {
 
    const ms = require("ms"); // npm install ms
    const args = message.content.slice(settings.prefix.length).trim().split(/ +/g);
    const command = args.shift().toLowerCase();
 
    if(command === "start"){
                // g!start-giveaway 2d 1 Awesome prize !
        // will create a giveaway with a duration of two days, with one winner and the prize will be "Awesome prize"
    
        let time = ms(args[0]);
        let winnersCount = args[1];
        let prize = args.slice(2).join(" ");
        giveaways.start(message.channel, {
            time: ms(args[0]),
            prize: args.slice(2).join(" "),
            winnersCount: parseInt(args[1])
        });
        
        
    }
});
giveaways.launch(client, {
    updateCountdownEvery: 3000,
    botsCanWin: false,
    ignoreIfHasPermission: [],
    embedColor: "#FAAC58",
    reaction: "🎉",
    messages: {
        giveaway: "** **",
        giveawayEnded: "@everyone\n\n🎉🎉 **RESULTAT** 🎉🎉",
        timeRemaining: "Temps restant: **{duration}**!",
        inviteToParticipate: "Tu dois appuyre sur 🎉 pour t'inscrire sur la liste!",
        winMessage: "Ouiiiii!!! GG, {winners}! Tu as gangé **{prize}**!",
        embedFooter: "Giveaways",
        noWinner: "Giveaway annulé, non valide participations.",
        winners: "Gagnant(s)",
        endedAt: "Fin à",
        units: {
            seconds: "secondes",
            minutes: "minutes",
            hours: "heures",
            days: "jours"
        }
    }
});

                        
client.login("");
```

**Comment by Androz2091** [comment]
Bonjour
Tu dois mettre les paramètres de langue dans la même fonction launch(). Ce qui donnera dans le client.on("ready") :
```js
giveaways.launch(client, {
        updateCountdownEvery: 5000,
        botsCanWin: false,
        ignoreIfHasPermission: [
            "MANAGE_MESSAGES",
            "MANAGE_GUILD",
            "ADMINISTRATOR"
        ],
        embedColor: "#FAAC58",
        reaction: "🎉",
        messages: {
            giveaway: "** **",
            giveawayEnded: "@everyone\n\n🎉🎉 **RESULTAT** 🎉🎉",
            timeRemaining: "Temps restant: **{duration}**!",
            inviteToParticipate: "Tu dois appuyre sur 🎉 pour t'inscrire sur la liste!",
            winMessage: "Ouiiiii!!! GG, {winners}! Tu as gangé **{prize}**!",
            embedFooter: "Giveaways",
            noWinner: "Giveaway annulé, non valide participations.",
            winners: "Gagnant(s)",
            endedAt: "Fin à",
            units: {
                seconds: "secondes",
                minutes: "minutes",
                hours: "heures",
                days: "jours"
            }
        }
    });
```

**Comment by Maxbroooooo** [comment]
`settings` = {
    prefix: config.prefix,
    
};
client.on("ready", () => {
giveaways.launch(client, {

    updateCountdownEvery: 5000,

    botsCanWin: false,

    ignoreIfHasPermission: [

        "MANAGE_MESSAGES",

        "MANAGE_GUILD",

        "ADMINISTRATOR"

    ],

    embedColor: "#FAAC58",

    reaction: "🎉",

    messages: {

        giveaway: "** **",

        giveawayEnded: "@everyone\n\n🎉🎉 **RESULTAT** 🎉🎉",

        timeRemaining: "Temps restant: **{duration}**!",

        inviteToParticipate: "Tu dois appuyre sur 🎉 pour t'inscrire sur la liste!",

        winMessage: "Ouiiiii!!! GG, {winners}! Tu as gangé **{prize}**!",

        embedFooter: "Giveaways",

        noWinner: "Giveaway annulé, non valide participations.",

        winners: "Gagnant(s)",

        endedAt: "Fin à",

        units: {

            seconds: "secondes",

            minutes: "minutes",

            hours: "heures",

            days: "jours"

        }

    }

});
client.on("message", (message) => {
 
    const ms = require("ms"); // npm install ms
    const args = message.content.slice(settings.prefix.length).trim().split(/ +/g);
    const command = args.shift().toLowerCase();
 
    if(command === "start"){
                // g!start-giveaway 2d 1 Awesome prize !
        // will create a giveaway with a duration of two days, with one winner and the prize will be "Awesome prize"
    
        let time = ms(args[0]);
        let winnersCount = args[1];
        let prize = args.slice(2).join(" ");
        giveaways.start(message.channel, {
            time: ms(args[0]),
            prize: args.slice(2).join(" "),
            winnersCount: parseInt(args[1])
        });
        
        
    }
});
`})```

**Comment by Androz2091** [comment]
Effectivement, c'était de ma faute, la variable messages ne passait pas. Réinstalle le module et réessaye
