### ISSUE TITLE
Lunch

### ISSUE THREAD

**Issue by NikXxX** [Androz2091/discord-giveaways#10]
When I restart my bot the giveaways doesn't continue. Is this normal ?

**Comment by Androz2091** [comment]
Can you show your `launch()` function please?

**Comment by NikXxX** [comment]
https://media.discordapp.net/attachments/592753744681369613/637685437305061376/image0.jpg

**Comment by Androz2091** [comment]
Try to replace `storage: "./giveaways.json"` with `storage: __dirname+"/giveaways.json"`, create a new giveaway and restart the bot

**Comment by NikXxX** [comment]
That's work! Thanks you ^^'
