### ISSUE TITLE
Giveaway ID

### ISSUE THREAD

**Issue by iNXECTRE** [Androz2091/discord-giveaways#101]
const Command = require('../../Structures/Command.js');
const Discord = require("discord.js")
const embeds = require("../../Structures/Bot/embeds.json");
// const perms = require("../../Structures/Bot/permissions.js");
const ms = require("ms");

module.exports = class extends Command {

	constructor(...args) {
		super(...args, {
      name: "gdrop",
      description: "",
      category: "⚒️ developer",
      usage: "gdrop <#channel || channel ID> <prize>",
			aliases: []
		});
	}

	// eslint-disable-next-line no-unused-vars
	async run(message, args) {

    let error = new Discord.MessageEmbed()
	  .setColor(embeds.colors.red)
	  .setTimestamp()
	  .setAuthor('Error!', embeds.images.error)
	  .setFooter(`${this.client.user.username}`, this.client.user.displayAvatarURL())
	  
    let success = new Discord.MessageEmbed()
	  .setColor(embeds.colors.green)
	  .setTimestamp()
	  .setAuthor('Success!', embeds.images.success)
	  .setFooter(`${this.client.user.username}`, this.client.user.displayAvatarURL())
	  
	  if(!args[0]){
	    error.setDescription(`${message.author} You need to mention or give the channel ID where you want to host your drop, you also need to include a prize\n\n**Usage:** gdrop <#channel | channel ID> <prize>`)
	    return message.channel.send(error)
	  }
	  
	  let dropChannel = message.mentions.channels.first() || message.guild.channels.cache.get(args[0])
    let dropPrize = args.slice(1).join(" ")
    
    if(!dropChannel) {
      error.setDescription(`${message.author} Couldnt find that channel, make sure to mention or give the correct channel id that exists in this server`)
      return message.channel.send(error)
    }
    
    if(!dropPrize){
      error.setDescription(`${message.author} You need to include the prize of your drop`)
      return message.channel.send(error)
    } else {
      message.delete()
      success.setDescription(`${message.author} Successfully made a drop in ${dropChannel} with the prize of **${dropPrize}**`)
      message.channel.send(success).then(m => m.delete({timeout: 20000}))
      
      let m = this.client.dropsManager.start(dropChannel, {
        // The giveaway duration
        time: ms("5m"),
        // The giveaway prize
        prize: dropPrize,
        // The giveaway winner count
        winnerCount: 1,
        // Who hosts this giveaway
        hostedBy: this.client.config.hostedBy ? message.author : null,
        // Messages
        messages: {
            drop: (this.client.config.everyoneMention ? "@everyone\n\n" : "")+"🎉 **NEW GIVEAWAY DROP** 🎉",
            dropEnded: (this.client.config.everyoneMention ? "@everyone\n\n" : "")+"🎉 **GIVEAWAY DROP ENDED** 🎉",
            timeRemaining: "⏰ Time remaining: **{duration}**!",
            inviteToParticipate: "🎖️ First one to react with 🎉 wins!",
            winMessage: "Congratulations, {winners}! You won **{prize}**!",
            embedFooter: "Giveaways",
            noWinner: "Giveaway cancelled, no valid participations.",
            hostedBy: "Hosted by: {user}",
            winners: "winner(s)",
            endedAt: "Ended at",
            units: {
                seconds: "seconds",
                minutes: "minutes",
                hours: "hours",
                days: "days",
                pluralS: false // Not needed, because units end with a S so it will automatically removed if the unit value is lower than 2
            }
        }
    });
    
    const filter = (reaction, user) => {
      return reaction.emoji.name === '👍' //&& user.id === message.author.id;
    };
    
    message.awaitReactions(filter, { max: 1, time: 60000, errors: ['time'] }).then(collected => {
      let giveaway = 
      // Search with giveaway prize
      this.client.dropsManager.giveaways.find((g) => g.prize === args.join(' ')) ||
      // Search with giveaway ID
      this.client.dropsManager.giveaways.find((g) => g.messageID === args[0]);

      // Edit the giveaway
      this.client.dropsManager.edit(m.messageID, {
          setEndTimestamp: Date.now()
      })
    })
    }
	}
};

How can I get the giveaway ID without using any other command or getting the ID manually? Im trying to make a drop feature straight from this package. Is there any other way to do this?

**Comment by Androz2091** [comment]
This package is not really made for this type of giveaway. You should try to make it yourself or use another package...
