### ISSUE TITLE
How to get giveaway message URL?

### ISSUE THREAD

**Issue by iNXECTRE** [Androz2091/discord-giveaways#102]
const Command = require('../../Structures/Command.js');
const Discord = require('discord.js');
const embeds = require('../../Structures/Bot/embeds.json');
const perms = require("../../Structures/Bot/permissions.js");
const ms = require('ms');
const pms = require("pretty-ms");

module.exports = class extends Command {
	constructor(...args) {
		super(...args, {
			name: 'gend',
			description: 'Ends the giveaway & pick the winner(s)',
			category: '🎉 giveaways',
			usage: 'gend <giveaway ID>',
			aliases: []
		});
	}

	// eslint-disable-next-line no-unused-vars
	async run(message, args) {
		let error = new Discord.MessageEmbed()
			.setColor(embeds.colors.red)
			.setTimestamp()
			.setAuthor('Error!', embeds.images.error)
			.setFooter(`${this.client.user.username}`, this.client.user.displayAvatarURL());

		let success = new Discord.MessageEmbed()
			.setColor(embeds.colors.green)
			.setTimestamp()
			.setAuthor('Success!', embeds.images.success)
			.setFooter(`${this.client.user.username}`, this.client.user.displayAvatarURL());
			
	  if(message.member.roles.cache.some(r => `${perms.giveaway}`.includes(r.name)) || message.member.hasPermission('ADMINISTRATOR')){
    } else {
      error.setDescription(`${message.author} You dont have permission to use this command. You need to have the \`\`${perms.giveaway}\`\` role or \`\`ADMINISTRATOR\`\` permission to use this command`)
      return message.channel.send(error)
    }
    
		let giveawayID = args[0]
		
		if(!args[0]){
		  error.setDescription(`${message.author} You need to include the giveaeay ID of the giveaway you want to end`)
		  return message.channel.send(error)
		}
		
		if(isNaN(giveawayID)){
		  error.setDescription(`${message.author} Giveaway ID's only contains numbers & numbers only`)
		  return message.channel.send(error)
		}
		
		let giveaway = this.client.giveawaysManager.giveaways.find((g) => g.messageID === giveawayID);
    
    // If no giveaway was found
    if(!giveaway){
      error.setDescription(`${message.author} Unable to find a giveaway with the ID \`\`${giveawayID}\`\`. Make sure you give the correct giveaway ID`)
      return message.channel.send(error)
    }
    
    // Edit the giveaway
    this.client.giveawaysManager.edit(giveaway.messageID, {
        setEndTimestamp: Date.now()
    }).then(() => {
      message.delete()
      success.setDescription(`${message.author} Successfully ended the giveaway with the ID \`\`${giveawayID}\`\`. This might take a few seconds before ending & picking the winner\n\n**\`\`THIS MESSAGE WILL BE AUTOMATICALLY DELETED AFTER LESS THAN ${this.client.giveawaysManager.options.updateCountdownEvery/1000} SECONDS\`\`**`)
      message.channel.send(success).then(m => m.delete({ timeout: 20000}))
    }).catch((e) => {
      if(e.startsWith(`Giveaway with message ID ${giveaway.messageID} is already ended.`)){
        error.setDescription(`${message.author} The giveaway with the ID \`\`${giveawayID}\`\` has already ended`)
        message.channel.send(error)
      } else {
        console.error(e)
        error.setDescription(`${message.author} Uh oh! Something went wrong!`)
        message.channel.send(error)
      }
    });
	}
};

How can I get the message link of the giveaway? I want the gend command gives the link of the message so they can click on it to go to the giveaway embed that they ended

**Comment by Androz2091** [comment]
You can use:
```js
const giveawayURL = `https://discordapp.com/channels/${giveaway.guildID}/${giveaway.channelID}/${giveaway.messageID}`;
```
