### ISSUE TITLE
[BUG] WinnerCount dosen't work on reroll

### ISSUE THREAD

**Issue by Myzumi** [Androz2091/discord-giveaways#104]
So i used the example reroll in the npm page description and edited the options and added a winnerCount 1 to it so it outputs only 1 new winner, if i reroll it it uses the winnercount of the giveaway and not the one i set in the options

Code:
```
    if (command === "reroll") {
      if (
        message.member.hasPermission("ADMINISTRATOR") ||
        message.author.id === config.devid
      ) {
        let messageID = args[0];
        client.gmanager
          .reroll(messageID, {
            winnerCount: 1,
            messages: {
              congrat: ':tada: New winner: {winners}! Congratulations!',
              error: 'No valid participations, no winners can be chosen!'
          }
          })
          .then(() => {
            message.channel.send("Success! Giveaway rerolled!");
          })
          .catch((err) => {
            message.channel.send(
              "No giveaway found for " +
                messageID +
                ", please check and try again"
            );
          });
      }
    }
```

After i do the command it uses the winners from the giveaway (wich was 3)
https://prnt.sc/ucfe6m

**Comment by Skeec54** [comment]
Also a suggestion would be not letting the bot pick someone that already won

**Comment by Androz2091** [comment]
Indeed, the bug will be fixed in the next release.

> Also a suggestion would be not letting the bot pick someone that already won

As the previous winners are not stored, it's not really possible to implement that feature. You would have to make your own `reroll()` command.

**Comment by Skeec54** [comment]
> As the previous winners are not stored, it's not really possible to implement that feature. You would have to make your own `reroll()` command.

could you not store it in the giveaways.json file?

**Comment by iNXECTRE** [comment]
This is what I think about this issue:

After ending the giveaway, store the user id(s) of the winners in a file or something. But to make it so that they wont win in the giveaway where they won something only, add the message id of the giveaway

> "123456789" (Giveaway id)
  > "8338938377" (The id of the user who won a giveaway from the giveaway id given above)
  > "988473388338" (The id of the user who won a giveaway from the giveaway id given above)
  > And so on and so on


I dont really know how to implement that above, but I think Androz would find a way to implement this in the future 😜

**Comment by Shashank3736** [comment]
Yeah, whenever you reroll it can pick the same winner but what you can do simply remove winners reaction after the giveaway ends and every time you reroll it. I recommended this way [here](https://github.com/Androz2091/discord-giveaways/issues/103#issuecomment-687709792) in issue #103  

For now, this is the best way to achieve this.

**Comment by Skeec54** [comment]
So when does this get fixed?

**Comment by NicoHd105** [comment]
Probably in the next update but if you want to use it right now you can just add `options.winnerCount` into the brackets of `this.roll()` in the reroll function of the Giveaway.js file of the module

**Comment by SoftyMystic** [comment]
I believe the next release would be a big one

**Comment by EwoX07** [comment]
Cmon, when it'll be fixed?

**Comment by NicoHd105** [comment]
> Cmon, when it'll be fixed?

In the next release, it's already a pr and if you can't wait anymore then you can install the develop branch of this repo.
