### ISSUE TITLE
[Suggestion] X Role has X Entries

### ISSUE THREAD

**Issue by Myzumi** [Androz2091/discord-giveaways#108]
Please add a feature to allow like nitro boosters to get Double entries into a giveaway

**Comment by NicoHd105** [comment]
It is planned

**Comment by Shashank3736** [comment]
Best way to execute it is by making allowing us to pass functions like 
```js
entries: message.author.bot? 0 : 1
```
This will not bound the entries part just to the role but we can also do many things there.

**Comment by ririko5834** [comment]
Can you add this?

**Comment by Lebyy** [comment]
This would be a really good feature.

**Comment by Nico105** [comment]
🎉 v4.5.0 is now released!
