### ISSUE TITLE
Reroll

### ISSUE THREAD

**Issue by NikXxX** [Androz2091/discord-giveaways#11]
The reroll don't work. I have the err
reaction.users.fetch is not a function.

**Comment by Androz2091** [comment]
Can I see the content of the `package.json` file please?

**Comment by NikXxX** [comment]
I don't have package.json

**Comment by Androz2091** [comment]
OK, so go to your `node_modules` folder, choose `discord.js` and show me the `package.json` file

**Comment by Androz2091** [comment]
Oh ok

**Comment by herothedev** [comment]
this works on v11 only

**Comment by Androz2091** [comment]
@herothedev no it works on v12 too. I don't know what's the mistake with @NikXxX. Maybe it has the both versions of discord.js installed.
