### ISSUE TITLE
2 message wins when the giveaway end

### ISSUE THREAD

**Issue by blackopss** [Androz2091/discord-giveaways#112]
https://cdn.discordapp.com/attachments/670307770398015488/765738266254770196/unknown.png
i got this sometimes 
i use
client.giveawaysManager.on('giveawayEnded', (giveaway, winners) => {
    giveaway.channel.send(`Congratulations, ${winners}! You won **${giveaway.prize}**! 🎉
https://discordapp.com/channels/${giveaway.message.guild.id}/${giveaway.channelID}/${giveaway.messageID}`);
});

**Comment by NicoHd105** [comment]
So if you would set the winnercount to 1 and you and your friend would react and then in the 1st message you would be the winner and in the 2nd your friend would be the winner, if that is the case => so it would choose different winners and not just send the message twice, then the solution is to move `this.ended = true;` above `fetchmessage` in the end function inside the "Giveaway.js" file of the module like you see in the ss. At least that was the solution for me. The only thing that would happen now is that if it would like to send the message twice it would instead log `The ... giveaway is already ended`.
![image](https://user-images.githubusercontent.com/63612668/96036542-e9fb2180-0e64-11eb-84ae-e3b98912b1cc.png)
