### ISSUE TITLE
A npm error.

### ISSUE THREAD

**Issue by Dragonizedpizza** [Androz2091/discord-giveaways#114]
I get an error when I do `npm install --save discord-giveaways` 

```PS C:\Users\akyra\Desktop\Bots\discord-giveaways> npm install --save discord-giveaways
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "discord-giveaways" under a package
npm ERR! also called "discord-giveaways". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\akyra\AppData\Roaming\npm-cache\_logs\2020-10-21T12_29_57_756Z-debug.log

**Comment by MaximKing1** [comment]
Try adding the discord-giveaways to the package.json file then run npm install and see if that works...

**Comment by Dragonizedpizza** [comment]
@MaximKing1 idk what the package Androz wants is. 
It attempts to install discord-giveaways, but failed because there is another package called discord-giveaways.

**Comment by Snowflake107** [comment]
change your `"name"` field in `package.json`. You cannot install a package with a name of your `package.json`

**Comment by Dragonizedpizza** [comment]
@Snowflake107 idk which package to install though, because there are 2 discord-giveaways package.

**Comment by Snowflake107** [comment]
**Androz2091/`discord-giveaways`** 🤔

**Comment by Androz2091** [comment]
@Dragonizedpizza looks like you downloaded the files of the package and tried to install it in the downloaded folder. Instead, you should install it in your bot's folder.

**Comment by Dragonizedpizza** [comment]
Yes, I sorted that out. It was very careless of me, I thought I'd done it
on my bot's folder.
