### ISSUE TITLE
Cannot read property 'start' of undefined Error 

### ISSUE THREAD

**Issue by Hazza88** [Androz2091/discord-giveaways#118]
When I run gstart this error comes up:

TypeError: Cannot read property 'start' of undefined

**Comment by NicoHd105** [comment]
Could you please send the whole line?

**Comment by Nico105** [comment]
> When I run gstart this error comes up:
> 
> TypeError: Cannot read property 'start' of undefined

Hello?
If you fixed the problem yourself then provide the solution/what was wrong and close this issue, otherwise please answer my questions...

**Comment by Hazza88** [comment]
Yea sorry, I did fix it I was missing a part of the code that was in another folder

**Comment by Nico105** [comment]
> Yea sorry, I did fix it I was missing a part of the code that was in another folder

Then please close this issue
