### ISSUE TITLE
Discord MySQL For Database

### ISSUE THREAD

**Issue by MaximKing1** [Androz2091/discord-giveaways#119]
I’m using the giveaways for my bot every time it restarts it resets the giveaways that are on going... I’m trying to use MySQL but in the docs only has SQLITE3 which has same issue any help would be great!

**Comment by NicoHd105** [comment]
Did you figure out a solution? If not did you properly extend the _giveawaysManager_ class?

**Comment by NicoHd105** [comment]
#140 should be all you need. I will make a pr to include it in the docs somewhen, so please close this issue.

**Comment by Androz2091** [comment]
:tada: v4.3.0 is now released!

**Comment by Androz2091** [comment]
MySQL example is available here: https://github.com/Androz2091/discord-giveaways/blob/master/examples/custom-databases/mysql.js
