### ISSUE TITLE
[FR/EN] Couleur "End" Embed + "Last Chance"

### ISSUE THREAD

**Issue by NzoSifou** [Androz2091/discord-giveaways#12]
[FR]
Bonjour,
Je propose 2 suggestions :
La première étant d'ajouter une couleur pour l'embed quand le giveaway est terminé car pour l'instant nous pouvons mettre la couleur de l'embed seulement quand le giveaway est actif, mais lorsqu'il est terminé la couleur de l'embed devient noir et nous ne pouvons pas la changer ! (Si possible mettre le paramètre "endEmbedColor" ou "endedEmbedColor" dans l'event ready)

La deuxième suggestion :
Ajouter un "Last Chance" :

lastChance: true/false
lastChanceOptions: {
    title: "Last Chance to enter!",
    secondsBeforeLastChance: 5000,
    embedColor: #ff0000

Le "Last Chance" permet d'informer aux membres du serveur qu'il ne reste plus que 5 secondes (en reprenant le code ci-dessus) pour participer au giveaway avant qu'il ne se termine.
Aussi la couleur de l'embed pourras être changé pendant les 5 dernières secondes.
Le titre pourras lui aussi être changé pendant les 5 dernières secondes.
Si possible mettre le "Last Chance" dans l'event message.

[EN]
Hello,
I propose 2 suggestions:
The first is to add a color for the embed when the giveaway is over because for now we can put the color of the embed only when the giveaway is active, but when it is finished the color of the embed becomes black and we can not change it! (If possible put the parameter "endEmbedColor" or "endedEmbedColor" in the event ready)

The second suggestion:
Add a "Last Chance":

lastChance: true / false
lastChanceOptions: {
     title: "Last Chance to enter!",
     secondsBeforeLastChance: 5000,
     embedColor: #ff0000

The "Last Chance" informs the server members that there is only 5 seconds left (using the code above) to participate in the giveaway before it ends.
The color of the embed can be changed during the last 5 seconds.
The title can also be changed during the last 5 seconds.
If possible put the "Last Chance" in the event message.

**Comment by Nico105** [comment]
🎉 v4.5.0 is now released!
