### ISSUE TITLE
[Probs a Bug] Bot keeps saying no valid participations

### ISSUE THREAD

**Issue by FC5570** [Androz2091/discord-giveaways#120]
Hey,

 I tried to host a test giveaway with 1 winner, whenever the giveaway ends it says no valid participations were found and it ends the giveaway without declaring any winner. I thought this might be because of the reactions it gets which is only me and the bot. I made some of my friends react too for another test give-away. But it still says it can't decide any winner cause of lack of participants.

**Comment by NicoHd105** [comment]
Look into your `const manager = new GiveawaysManager(client, {` , is there `exemptPermissions: [ "MANAGE_MESSAGES", "ADMINISTRATOR" ],` ? If yes then remove it because it will not choose a winner that has those permissions.

**Comment by FC5570** [comment]
Ah I do, Lemme try and see if it works.

**Comment by FC5570** [comment]
It worked thanks.
