### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by Ult1m1** [Androz2091/discord-giveaways#122]
(node:24) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
at /home/container/node_modules/discord-giveaways/src/Giveaway.js:375:26
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:24) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by NicoHd105** [comment]
Does this still happen/did you maybe remove _{winners}_ from your _winMessage_ key in your giveaway object?

**Comment by Androz2091** [comment]
:tada: v4.3.0 is now released!
