### ISSUE TITLE
Manager not ready yet...

### ISSUE THREAD

**Issue by RahulPlays** [Androz2091/discord-giveaways#124]
It is happening all time... I waited soo many times to let the manager ready.. fix this and i love this module.. ;) but please fix it

Im not using command handler and other stuff

**Comment by NicoHd105** [comment]
The module tries to start a giveaway but the manager is not ready yet, so that means you have to make a delay _I think_

**Comment by Androz2091** [comment]
Hello, this error is *generally* due to the fact that you create the `giveaways.json` file yourself. Did you do it? If so, delete it and restart the bot, it will create it automatically.

**Comment by Androz2091** [comment]
Closed due to inactivity.

**Comment by KanonBlanc** [comment]
Hello. Im having the same issue with "The manager is not ready yet." The thing is I didn't create the `./giveaway.json` and yes it created itself. But still i'm getting the error

**Comment by Nico105** [comment]
> Hello. Im having the same issue with "The manager is not ready yet." The thing is I didn't create the `./giveaway.json` and yes it created itself. But still i'm getting the error

Where is your `new GiveawaysManager(client` located? If it's in the command file then that's the wrong place.
_btw you should have opened a new issue but nvm_

**Comment by KanonBlanc** [comment]
> 

Should i put the GiveawaysManager in `index.js` file? I'm using slappey package to create my bot, Sorry kinda new in coding

**Comment by KanonBlanc** [comment]
> > Hello. Im having the same issue with "The manager is not ready yet." The thing is I didn't create the `./giveaway.json` and yes it created itself. But still i'm getting the error
> 
> Where is your `new GiveawaysManager(client` located? If it's in the command file then that's the wrong place. _btw you should have opened a new issue but nvm_

Should i put the GiveawaysManager in `index.js` file? I'm using slappey package to create my bot, Sorry kinda new in coding

**Comment by Shashank3736** [comment]
> Should i put the GiveawaysManager in `index.js` file? I'm using slappey package to create my bot, Sorry kinda new in coding

Yes and make a client.manager which you will use to control giveaways

**Comment by KanonBlanc** [comment]
> > Should i put the GiveawaysManager in `index.js` file? I'm using slappey package to create my bot, Sorry kinda new in coding
> 
> Yes and make a client.manager which you will use to control giveaways

Now im lost, Im new so I can't understand some of it

**Comment by Shashank3736** [comment]
See this [example](https://github.com/Androz2091/discord-giveaways-bot) to better understand how to use the package and what I just said.

**Comment by KanonBlanc** [comment]
> See this [example](https://github.com/Androz2091/discord-giveaways-bot) to better understand how to use the package and what I just said.

What is this meaning if i get this kind of error? `options.winnerCount is not a positive integer. (val=1)`

**Comment by Shashank3736** [comment]
options.winnerCount must be greater than 0. That's what it means

**Comment by KanonBlanc** [comment]
> options.winnerCount must be greater than 0. That's what it means

I already did 5+

**Comment by Nico105** [comment]
> > options.winnerCount must be greater than 0. That's what it means
> 
> I already did 5+

You're providing a string. Convert it to number.

**Comment by KanonBlanc** [comment]
> > > options.winnerCount must be greater than 0. That's what it means
> > 
> > 
> > I already did 5+
> 
> You're providing a string. Convert it to number.

How do i actually convert it to numbers? I command like this `?gstart #<channel> <5m/5s/5h> <1/2/3/4/5> <item prize>`

**Comment by Shashank3736** [comment]
> How do i actually convert it to numbers? I command like this `?gstart #<channel> <5m/5s/5h> <1/2/3/4/5> <item prize>`

use `parseInt()` function. 
for e.g 
```
parseInt("2") //2
````
First, from the arguments take 3rd argument and then convert it into an integer.

**Comment by KanonBlanc** [comment]
> 

Where to be exact? here? `let giveawayNumberWinners = args[2];`

**Comment by Shashank3736** [comment]
make `args[2]` to `parseInt(args[2])`

**Comment by KanonBlanc** [comment]
> make `args[2]` to `parseInt(args[2])`

Ah i tried it that too since its numerical, and this is the error it gives `options.duration is not a positive number. (val=undefined)`

**Comment by KanonBlanc** [comment]
> > make `args[2]` to `parseInt(args[2])`
> 
> Ah i tried it that too since its numerical, and this is the error it gives `options.duration is not a positive number. (val=undefined)`

Or am i missing in my package?

**Comment by Nico105** [comment]
> > make `args[2]` to `parseInt(args[2])`
> 
> Ah i tried it that too since its numerical, and this is the error it gives `options.duration is not a positive number. (val=undefined)`

`time` changed to `duration` in the start options

**Comment by KanonBlanc** [comment]
> 

Uh what should i do with that? sorry im very new

**Comment by KanonBlanc** [comment]
> you forget to set `options.duration` in your code. Add duration in `Manager.start` method.

Wait.. i have that in Manager.start named as `time(giveawayDuration)` its not gonna work?

**Comment by KanonBlanc** [comment]
Thank you guys! The only problem is `time: ms(duration)` should be `duration: ms(duration)`!

**Comment by KanonBlanc** [comment]
Anyway I'm having a problem about `messageID` , when I do a reroll probably its connected to it, the thing is in console log this is what it shows `Giveaway <#undefined> ended! Winners` the `<#undefined>` should be `channelID` so when i do the reroll the `messageID` cant find

**Comment by Nico105** [comment]
> 

ID changed to Id.
You're using a v4 coded bot from somewhere.
But please stop posting in this closed issue.
If you encounter a real bug, open a new issue.
Otherwise read the docs for such trivial problems.

**Comment by KanonBlanc** [comment]
> > 
> 
> ID changed to Id. You're using a v4 coded bot from somewhere. But please stop posting in this closed issue. If you encounter a real bug, open a new issue. Otherwise read the docs for such trivial problems.

Ok thanks
