### ISSUE TITLE
(Suggestion) A !gend command

### ISSUE THREAD

**Issue by WideIrenaKan2** [Androz2091/discord-giveaways#125]
Basically if you do !gend {messageid} it will end the active giveaway. (Not deleting the giveaway but ending it and showing whose the winner of that giveaway)

**Comment by NicoHd105** [comment]
Already exists, look at the docs or the npm page

**Comment by WideIrenaKan2** [comment]
> Already exists, look at the docs or the npm page

Where sorry I cannot find it in npm page

**Comment by NicoHd105** [comment]
Right, sry, herw is it https://github.com/Androz2091/giveaways-bot/blob/master/commands/end-giveaway.js
