### ISSUE TITLE
Suggestion: Add support for mongodb

### ISSUE THREAD

**Issue by wolfier74** [Androz2091/discord-giveaways#127]
Hello, can you please create option to use mongodb database as storage for giveaways? This would be useful, json files are sometimes buggy, when more values are saved there.

Another suggestion: Auto remove giveaway from database after 30 days when it ended.
I think that nobody will edit or reroll 30 days old giveaway. Its just spamming database.

**Comment by NicoHd105** [comment]
If you want to use mongodb got to the bottom of #90, it works, it uses quickmongo, a mongoDB wrapper and you can add the after 30 days deletion yourself if you want with just checking on startup of every day on runtime and doing `Array.forEach` but I agree that it would be a nice utility to add to the module itself somewhen

**Comment by wolfier74** [comment]
Ok, the mongo is working. Can you please send me code how to delete giveaways older than 30 days on ready event?

**Comment by NicoHd105** [comment]
`client,giveawaysManager.giveaways.filter(g => Date.now() - g.startAt >= ms('30d')).forEach(g => client.giveawaysManager.deleteGiveaway(g.messageID))`
But for real you should really take a look at the docs or the README if you want to work with this module if you have to ask for code...

**Comment by wolfier74** [comment]
Ty, it will delete giveaway data from database or also the giveaway embed from discord?

**Comment by wolfier74** [comment]
Also how can i send DM "Giveaway entry for {giveaway message id} was confirmed" to member who joined giveaway?

**Comment by NicoHd105** [comment]
`deleteGiveaway()` only deletes from DB, `delete()` would delete message too/you can choose if message should get deleted or not.
For DM, use the `giveawayReactionAdded` event: https://discord-giveaways.js.org/ just look at the docs, you can add it to your code like you added discord.js events
