### ISSUE TITLE
Help: How to make command to get list of all giveaways

### ISSUE THREAD

**Issue by ririko5834** [Androz2091/discord-giveaways#129]
Can someone send me example code how to get list of all active giveaways for message guild.

There should be returned giveaway channel and giveaway message link

**Comment by NicoHd105** [comment]
#62 should do it.

**Comment by ririko5834** [comment]
Also i would like to have that old giveaways will be removed from database.

**Comment by NicoHd105** [comment]
`client.giveawaysManager.giveaways.filter(g => g.ended).forEach(g => client.giveawaysManager.deleteGiveaway(g.messageID))`
_Approximately like that_
Check on startup or on an interval

**Comment by NicoHd105** [comment]
If you don't have a question left then please close this issue.

**Comment by ririko5834** [comment]
Ok
