### ISSUE TITLE
Invalid Participant Error

### ISSUE THREAD

**Issue by Veltimo** [Androz2091/discord-giveaways#130]
When someone starts a raffle with my bot, sometimes the bot gives an invalid participation error even if it is a participant in the raffle. I can only fix this with the re-roll command (so I can only see the winners this way), but I want to solve it completely, not with the command. Please help me. https://cdn.discordapp.com/attachments/763041186335424523/786244120733286460/Screenshot_20201209-175316.png

**Comment by NicoHd105** [comment]
Do you have the latest version of this module? And have you checked what permissions, if any, are in your `exemptPermissions` option when you initialize the manager?

**Comment by Veltimo** [comment]
I'm using the latest version of the module, and the bot has admin permission.

**Comment by NicoHd105** [comment]
Is your countdown only 100? You should put it at least at 5000 because otherwise you will get ratelimited.
Maybe that will also help your issue idk, but otherwise I could only suggest for now that you put some console.logs into the `roll` functiin of the Giveaway.js file of the module to maybe see when/why the winner array gets empty/if that even happens.

**Comment by Veltimo** [comment]
No countdown time is not 100. 
![image](https://user-images.githubusercontent.com/67333585/101796620-2754f600-3b1a-11eb-8357-3472716f5b27.png)

**Comment by Veltimo** [comment]
However, I want to solve this problem completely, not by command. But I don't know how to solve this without command. I thought of having the bot auto reroll when there was an invalid participation error, but I don't know how to do it.

**Comment by NicoHd105** [comment]
You don't have to do it because it should not happen in the first place, so try debugging like i told you

**Comment by Veltimo** [comment]
So where should I write what code?

**Comment by NicoHd105** [comment]
"into the roll function of the Giveaway.js file of the module"

**Comment by NicoHd105** [comment]
Did you find a solution to this problem?
