### ISSUE TITLE
Feature request: Drops

### ISSUE THREAD

**Issue by wolfier74** [Androz2091/discord-giveaways#132]
Can you please add Drops feature like first to reacts will be the winner and drop should be ended then?

**Comment by wolfier74** [comment]
Also how can i make role requirement giveaway that when user dont have role reaction will be removed and dm will be sent to user?

**Comment by NicoHd105** [comment]
`giveawayReactionAdded` event for requirements and to be safe you can add the `exemptMembers` function property of the giveaway object and for drops, if you know how you can add it youself with also the same event I mentioned though I admit directly having an option would be better

**Comment by ririko5834** [comment]
This is good idea to add drops. I made drop cmd for my server, But there is problem, i have this when member reacts to drop it will end it (update timestamp) but there members can still join the drop for 10 seconds, because giveaways are updated every 10 seconds. 
So i think that it will be nice to add that feature.

**Comment by wolfier74** [comment]
@NicoHd105 Can you make PR if you can?

**Comment by NicoHd105** [comment]
I will figure something out _I think/hope_ to directly call the function but cause my bot is not fully stable cause of many changes I made you will have to wait some time

**Comment by wolfier74** [comment]
Ok

**Comment by Androz2091** [comment]
I don't think drops will be added to this package, but I will let this issue opened so if someone has an idea about how to implement them it will be possible.

**Comment by ririko5834** [comment]
ok

**Comment by Androz2091** [comment]
At the end, this has been added in v5. Run `npm install discord-giveaways@latest` to update!
