### ISSUE TITLE
we want update | reroll

### ISSUE THREAD

**Issue by Akurejs** [Androz2091/discord-giveaways#133]
how long has it been since a new update for this system that I think is simply one of the best

Anyway, I have a doubt, when using the reroll command he rolls new winners if there were 3 winners he rolls all 3, I need him to roll 1 or even 2 new winners, but he always rolls the total number of winners.

**Comment by NicoHd105** [comment]
You can go into the Giveaway.js file of the module and in the `reroll` function there is a line `this.roll()` you have to put `options.winnerCount` int the `roll()` then you can just add `winnerCount` to the options of `client.giveawaysManager.reroll(, {})` and it will work, in the next update it will be fixed for everyone

**Comment by NicoHd105** [comment]
And btw its cool that you want an update but you can't force somebody who does this freely to follow your orders and I mean you as a fellow developer should learn over time to do things yourself and become more independent so you don't have to rely on updates/you can create pull requests yourself then

**Comment by NicoHd105** [comment]
if you do what I said, it will fix your problem, so please close this issue.

**Comment by Akurejs** [comment]
thank you for the explanation
