### ISSUE TITLE
I cant roll/reroll

### ISSUE THREAD

**Issue by Unknown-Fllooo** [Androz2091/discord-giveaways#134]
If im starting a giveaway first everything runs fine but if it ends theres always no valid participant even tho 70 people reacted with the right emoji.

**Comment by NicoHd105** [comment]
Have you now found out if the exemptMembers or the exemptPermission triggers in the roll function or not, as I told you to see...?

**Comment by NicoHd105** [comment]
![image](https://user-images.githubusercontent.com/63612668/101989156-cb67aa00-3c9e-11eb-8db7-dccbad74bc50.png)
If your bot is under 100 servers could you please try to enable both, or one by one, the discord intents and see if it fixes anything?

**Comment by Androz2091** [comment]
Closed due to inactivity
