### ISSUE TITLE
Multiple Winners

### ISSUE THREAD

**Issue by alima566** [Androz2091/discord-giveaways#135]
Sometimes the bot will ping multiple winners when I have the number of winners set to 1. Embed will show the true winner, but when it announces, it will ping multiple times to multiple people. 
![image](https://user-images.githubusercontent.com/14950662/101816216-fc4cb100-3add-11eb-8252-af5c8a58dfe5.png)

**Comment by NicoHd105** [comment]
![image](https://user-images.githubusercontent.com/63612668/101822100-224b7300-3b29-11eb-83ee-f6216257d808.png)
If you change the `this.ended` position inside the end function in the Giveaway.js file of the module then it should get fixed, this will be fixed for everyone in the next release but you can already add it yourself to prevent the multiple winners problem.

**Comment by Akurejs** [comment]
I didn’t quite understand what to do, because it’s quite different there.

**Comment by NicoHd105** [comment]
> I didn’t quite understand what to do, because it’s quite different there.

Yeah sry, as I said this is for when 1 giveaway ends twice, your issue is something else, maybe because of intents like "no-participants" but idk, I will see what I can do somewhen when I have time.

**Comment by Androz2091** [comment]
So as @NicoHd105 said, this should be fixed in v4.3.0. If it's not the case, please re-open the issue.
