### ISSUE TITLE
Giveaway cancelled, not enough participants.

### ISSUE THREAD

**Issue by Akurejs** [Androz2091/discord-giveaways#136]
this is the second time this happens, I make a lottery and everyone reacts and says there are no valid participants

and another question, does anyone know a program that I can open the json.sqlite file and manually edit a giveaway?

screenshot [https://prnt.sc/w0s43a](https://prnt.sc/w0s43a)

**Comment by NicoHd105** [comment]
You don't use either `exemptMembers` nor `exemptPermissions` right?
And for your other question, you can use https://sqlitebrowser.org/ but I recommend to only edit things manually if you really have to because you easily can accidently change something else which you don't want.

**Comment by Akurejs** [comment]
> You don't use neither `exemptMembers` nor `exemptPermissions` right?
> And for your other question, you can use https://sqlitebrowser.org/ but I recommend to only edit things manually if you really have to because you easily can accidently change something else which you don't want.

I do not use, `exemptMembers` and `exemptPermissions`
I even tried to make a reroll using the id and he didn't find it, and then I used the command that samples the active giveaways and he didn't sample this giveaway either, something strange happened.

Thanks for the link, it was to put this giveaway on the air again.

**Comment by NicoHd105** [comment]
_You can make a cmd for adding it with the same embed to the DB again if you put some time into that_
And you are using the latest version of this module?

**Comment by Akurejs** [comment]
> _Você pode fazer um cmd para adicioná-lo com o mesmo embed ao banco de dados novamente se você dedicar algum tempo a isso._
> E você está usando a versão mais recente deste módulo?

yes, i'm using the latest version, referring to this cmd i don't know how to do unfortunately

**Comment by Akurejs** [comment]
> _You can make a cmd for adding it with the same embed to the DB again if you put some time into that_
> And you are using the latest version of this module?

yes, i'm using the latest version, referring to this cmd i don't know how to do unfortunately

**Comment by NicoHd105** [comment]
@Androz2091 do you maybe have any idea why? Because this recently _why ever_ happens to some people and the ones I had contact with all didn't use any function to remove users. I mean it did not really happen before so idk what could be the reason, I already suggested some to log the whole `roll()` function but because of lacking "intelligence/English skills" of those I don't know if any of them came to a conclusion/solution.

**Comment by Akurejs** [comment]
another very strange thing, to make up for the problem I remade 2 giveaways and the same two people won both

screenshot: [https://prnt.sc/w0t1ee](https://prnt.sc/w0t1ee)

**Comment by NicoHd105** [comment]
> another very strange thing, to make up for the problem I remade 2 giveaways and the same two people won both
> 
> screenshot: https://prnt.sc/w0t1ee

#135 Should fix it, will get rolled out for everyone in the next update.

**Comment by Akurejs** [comment]
> > another very strange thing, to make up for the problem I remade 2 giveaways and the same two people won both
> > screenshot: https://prnt.sc/w0t1ee
> 
> #135 Should fix it, will get rolled out for everyone in the next update.

if i do it will solve? I try to reroll in the giveaway but both people always win, this is very strange, I rerolled 5 times they won 5 times and the winners were not changed.

**Comment by Androz2091** [comment]
It **could** be due to the fact that some intents are or are not enabled. I haven't had the time to look further into the problem, but you could try to enable all the intents and retry.

**Comment by NicoHd105** [comment]
> > > another very strange thing, to make up for the problem I remade 2 giveaways and the same two people won both
> > > screenshot: https://prnt.sc/w0t1ee
> > 
> > 
> > #135 Should fix it, will get rolled out for everyone in the next update.
> 
> if i do it will solve? I try to reroll in the giveaway but both people always win, this is very strange, I rerolled 5 times they won 5 times and the winners were not changed.

Oh so its not double ending? That is what my solution would be for. `Mabye its also because of intents.` I will see to it later

**Comment by NicoHd105** [comment]
> It **could** be due to the fact that some intents are or are not enabled. I haven't yet had time to look further into the problem, but you could enable all the intents and retry.

Kk, I will try to let some people test it.

**Comment by Akurejs** [comment]
I've been observing something and I don't know if it was already like that, when creating a new giveaway and turning off the bot and reacting with the bot off, connecting the bot and the time of the giveaway is over, he doesn't tell the person who reacted at the moment he was offline so if you are the only one to react he ends the giveaway for no valid participations

**Comment by Androz2091** [comment]
I know what's the problem, it will be fixed in v4.3.0

**Comment by Androz2091** [comment]
:tada: v4.3.0 is now released!
