### ISSUE TITLE
Add endedGiveawayReactionAdded event

### ISSUE THREAD

**Issue by ririko5834** [Androz2091/discord-giveaways#137]
Can you please add option to remove user's reaction when user reacts on giveaway that has already ended? Is these some event for it?

**Comment by NicoHd105** [comment]
I mean why? What good would that do? The only thing I can imagine is that when you reroll it then there should not be any new people but is that really that important? Correct me if there's another more useful use case.

**Comment by ririko5834** [comment]
> The only thing I can imagine is that when you reroll it then there should not be any new people but is that really that important?

Yes, that's why i want it. I don't want new people react to giveaway when it has ended. And also i am making role requirement giveaways and when giveaway is ended, everyone can react here and when I reroll it, members who dont have that role can won too 😕 .

**Comment by NicoHd105** [comment]
I mean for the requirement issue you can just check inside your reroll command after `.find` has found a giveaway and before `.reroll()` is used, if the giveaway has a requirements and then remove the invalid reactions before `.reroll()` fires.

**Comment by ririko5834** [comment]
Yes, but can you make PR for reaction remove on ended giveaway? I am removing reactions for users who dont have role in giveawayReactionAdded event and this event is not also for ended giveaways :/
Can you please make endedGiveawayReactionAdded and endedGiveawayReactionRemoved events?

**Comment by NicoHd105** [comment]
I will make one once the new version is released.

**Comment by wolfier74** [comment]
Ok, can you also make drops?

**Comment by NicoHd105** [comment]
With the next update you will get a `extraData` property in the giveaway object where you can easily add that, you can already do it right now, but you will need a DB. 
The only thing I will try to for this feature is to try to make the `end` function instantly, so that it doesn't wait for the next update time.

**Comment by wolfier74** [comment]
Ok

**Comment by NicoHd105** [comment]
> Yes, but can you make PR for reaction remove on ended giveaway? I am removing reactions for users who dont have role in giveawayReactionAdded event and this event is not also for ended giveaways :/
> Can you please make endedGiveawayReactionAdded and endedGiveawayReactionRemoved events?

The first one sure, but what use would the 2nd event have?

**Comment by wolfier74** [comment]
Idk, ok just make pr for endedGiveawayReactionAdded

**Comment by Androz2091** [comment]
:tada: v4.3.0 is now released!
