### ISSUE TITLE
The "embedFooter" value is not used

### ISSUE THREAD

**Issue by sskewer** [Androz2091/discord-giveaways#138]
I set the `embedFooter` value (`messages` object) as "Ends at", but it is not used anywhere in the giveaway embed.
Is this my problem or a problem with the package?

**Comment by wolfier74** [comment]
Yes, I have same problem

**Comment by NicoHd105** [comment]
It maybe was forgotten to get removed I think, or it was forgotten to add it to the embed.

**Comment by sskewer** [comment]
> It maybe was forgotten to get removed I think, or it was forgotten to add it to the embed.

@NicoHd105 It could be very useful to add the value in the footer after the winnerCount

**Comment by wolfier74** [comment]
Yes

**Comment by wolfier74** [comment]
Also footer icon can be useful

**Comment by sskewer** [comment]
@Androz2091 @NicoHd105 Excuse me for one more tag, but would it be possible to use this value in the footer?

**Comment by NicoHd105** [comment]
I'm not sure how you mean that, without extending the module its currently no option for you because if you would change `winners: "winner(s)` to `winners: "winners() | Ends at"` then it would display "2 winner(s) Ends at" in the footer BUT it would also display that in the description of the embed when it is ended. _It should be like that I think, test it if you want_

**Comment by sskewer** [comment]
@NicoHd105 You understood perfectly. I was asking if it would be possible to add it in the next version. Thank you anyway!

**Comment by NicoHd105** [comment]
`2 winners() • Ends at • 29.06.2020, 23:07:50`
Would it be ok if it's like that then? _The • is because of the Timestamp its' not removeable_

**Comment by sskewer** [comment]
> `2 winners() • Ends at • 29.06.2020, 23:07:50`
> Would it be ok if it's like that then? _The 2nd • is because of the Timestamp its' not removeable_

@NicoHd105 Yes, it is perfect. Thanks again!

**Comment by NicoHd105** [comment]
Np, I will add it in a pr that I make somewhen.

**Comment by Androz2091** [comment]
We won't add more options to configure the embeds like embedFooterIcon or embedAuthorName. If you want to make your own embeds, overwrite the `generateMainEmbed()`, `generateEndEmbed()` and `generateNoValidParticipantsEndEmbed()` (will be available in v4.3.0)

**Comment by Androz2091** [comment]
:tada: v4.3.0 is now released!
