### ISSUE TITLE
Add array of winners in the data

### ISSUE THREAD

**Issue by GreepTheSheep** [Androz2091/discord-giveaways#141]
Hi, I'm looking for adding an array of winners by their ID directly in the data, it will output like this:
```json
{
  "messageID":"788667977205415967",
  "channelID":"729084166674841680",
  "guildID":"729083124226719816",
  "startAt":1608103498384,
  "endAt":1608107098384,
  "ended":true,
  "winnerCount":2,
  "winners": [
    "293095120134340609",
    "667808789923364883"
  ],
  "prize":"Something",
  "hostedBy":"<@330030648456642562>"
}
```
As you can see, I added this part:
```json
 "winners": [
    "293095120134340609",
    "667808789923364883"
  ],
```
It is possible to add this part on the data? Thanks in advance

**Comment by NicoHd105** [comment]
With the next update _the merge of v.4.3.0_ the giveaway Object will get a `extraData` property where you can store things like your winner array

**Comment by NicoHd105** [comment]
Can I ask for your specific use case of this?
Because I would maybe make it a default property in a future pr I will make.

**Comment by GreepTheSheep** [comment]
It was to be able to get the list of winners when retrieving information about a giveaway with a command (like `!g info [messageID]`).

**Comment by NicoHd105** [comment]
Ok, thanks. As said I will probably make it a own property then.

**Comment by wolfier74** [comment]
Ok, but when will be extraData added?

**Comment by NicoHd105** [comment]
> Ok, but when will be extraData added?

Once the pr gets merged=when Androz has time

**Comment by Androz2091** [comment]
:tada: v4.3.0 is now released!
