### ISSUE TITLE
help

### ISSUE THREAD

**Issue by KrabbyBuckets** [Androz2091/discord-giveaways#144]
if i didnt mention a channel
winners would = args[1]

if i did
winners would = args[2]

so how i make it both?

yes i tried 

args[1] || args[2]

but it doesnt work

**Comment by NicoHd105** [comment]
```
if (message.mentions.channels.first()) {
winners = args[2]
} else {
winners = args[1]
}
```
Btw what you asked is common JS/discord.js and opening a issue which is called "help" could get you roasted to death.

**Comment by KrabbyBuckets** [comment]
i still have it.

i do

!create 1m 1 Test
nothing

!create #general 1m 1 Test
nothing

so dont roast people. lol.

**Comment by Androz2091** [comment]
Please use the discord server for these questions.
