### ISSUE TITLE
giveaway does not close and is not in the database

### ISSUE THREAD

**Issue by Akurejs** [Androz2091/discord-giveaways#147]
after having updated the module to the new version today, I went to the tests to start a new giveaway, and it doesn’t end, you can’t find it in the list of active giveaways, and you can’t close it with the end command or reroll

while writing this, I found this error in the terminal

`(node:5856) UnhandledPromiseRejectionWarning: Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time.
    at C:\Users\clonesheik\Desktop\novogivebot\node_modules\discord.js\src\managers\GuildMemberManager.js:317:16
    at Timeout._onTimeout (C:\Users\clonesheik\Desktop\novogivebot\node_modules\discord.js\src\client\BaseClient.js:83:7)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5856) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5856) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:5856) UnhandledPromiseRejectionWarning: Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time.
    at C:\Users\clonesheik\Desktop\novogivebot\node_modules\discord.js\src\managers\GuildMemberManager.js:317:16
    at Timeout._onTimeout (C:\Users\clonesheik\Desktop\novogivebot\node_modules\discord.js\src\client\BaseClient.js:83:7)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:5856) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)`

**Comment by Androz2091** [comment]
This is now fixed in v4.4.0
