### ISSUE TITLE
How to use extraData option?

### ISSUE THREAD

**Issue by ririko5834** [Androz2091/discord-giveaways#149]
How can I use extraData?
I want to save there custom data when making giveaway and then check the data in events.

**Comment by NicoHd105** [comment]
In your start command, you add `extraData: 'Test'` to the giveaway Object and then it will be saved with the giveaway when you start one.
In an event you then can just do `console.log(giveaway.extraData)`

**Comment by ririko5834** [comment]
Ok, can I rewrite the extraDate using manager.edit?

**Comment by Androz2091** [comment]
Sure, this will be available in v4.4.0

**Comment by Androz2091** [comment]
v4.4.0 has been published 👍

**Comment by ririko5834** [comment]
Ok

**Comment by ririko5834** [comment]
@Androz2091 Can I use this?
 ``` client.giveawaysManager.edit(giveaway.messageID, {
     extraData: "my own data",
    })```

**Comment by Androz2091** [comment]
No, use 
```js
client.giveawaysManager.edit(giveaway.messageID, {
    newExtraData: "my own data",
   })

**Comment by ririko5834** [comment]
Can I use {messageURL} also in giveaway reroll messages?

**Comment by Androz2091** [comment]
Yes.

**Comment by ririko5834** [comment]
I have problem. I am getting Uncaught Promise Error:  TypeError: Cannot read property 'username' of undefined
```js
client.giveawaysManager.on('giveawayEnded', async (giveaway, winners) => {
     winners.forEach((member) => {
         member.send(`Congratulations, **${member.user.username}**, you won **${giveaway.prize}** in **<#${giveaway.channelID}>**"`)
         
     });
```

**Comment by Androz2091** [comment]
@ririko5834 this is fixed on develop branch (`npm install Androz2091/discord-giveaways`). It will be released in a few hours
