### ISSUE TITLE
"time" is not defined

### ISSUE THREAD

**Issue by Ronak0020** [Androz2091/discord-giveaways#15]
I am facing a problem in your package.
I made a discord bot that also does giveaways and i used your package for the giveaway command.
When i run the bot, it showed error "time" is not defined.
It was in -> line 101, discord-giveaways.js file...
when i edited it and removed "isNaN(time)" and again tried to run the code, it worked alright!
but because i am hosting my bot to Heroku, it won't work because i can't edit the modules in heroku...
Please fix this issue!
Thank you!

**Comment by Androz2091** [comment]
I think I see what happened. I will fix this issue today
