### ISSUE TITLE
messages.embedFooter instantly cancels a giveaway.

### ISSUE THREAD

**Issue by BulletTide** [Androz2091/discord-giveaways#151]
When setting `embedFooter`, newly started giveaways instantly cancel.

**Comment by ririko5834** [comment]
same problem

**Comment by Androz2091** [comment]
What do you mean? Can you send your code please?

**Comment by BulletTide** [comment]
> What do you mean? Can you send your code please?

Looks like changing command handlers fixed the issue. Was previously using WOKCommands.

**Comment by Nico105** [comment]
> > What do you mean? Can you send your code please?
> 
> Looks like changing command handlers fixed the issue. Was previously using WOKCommands.

Please close this issue if your command handler change really fixed the problem.
