### ISSUE TITLE
Giveaway Ended Event

### ISSUE THREAD

**Issue by alima566** [Androz2091/discord-giveaways#156]
Sometimes the giveawayEnded event triggers multiple times (or none at all) when there's only ONE winner.

![Screen Shot 2020-12-25 at 22 47 31](https://user-images.githubusercontent.com/14950662/103146221-574bee00-4703-11eb-9de8-24f6f3f43610.png)
<img width="778" alt="Screen Shot 2020-12-25 at 22 47 51" src="https://user-images.githubusercontent.com/14950662/103146222-587d1b00-4703-11eb-99b3-baa32ed9519e.png">
<img width="574" alt="Screen Shot 2020-12-25 at 22 47 57" src="https://user-images.githubusercontent.com/14950662/103146223-59ae4800-4703-11eb-8829-bed958a3929b.png">

**Comment by Nico105** [comment]
Your event code is hopefully not im a command file, is it?
If not, what version of this module are you using?

**Comment by alima566** [comment]
I do not. However, I do have these set up so that there's these raffles every 4 hours and it's a Cron job that does it. It's in the same file as the Cron job.
________________________________

**Comment by Nico105** [comment]
So the code of your ss is in a file that gets "activated" every 4 hours? 
That's not how it should be, it is enougj if you put that code under the "initialization" code of the `giveawaysMamager` => `client.giveawaysMager = new ...`
 It just has to get "activated" once on startup and NOT on an interval.
If my first sentence is true then change it like i wrote and that should probably fix the 3rd ss problem of yours.

**Comment by alima566** [comment]
I have just done that and I will wait a day or two and let you know if it resolves this issue or not.
