### ISSUE TITLE
trouble ending the giveaway

### ISSUE THREAD

**Issue by Akurejs** [Androz2091/discord-giveaways#158]
here is some information about the problems I'm having with the new update

Index GiveawayManager

`const GiveawayManagerWithShardSupport = class extends GiveawaysManager {

    // Refresh storage method is called when the database is updated on one of the shards
    async refreshStorage(){
        // This should make all shard refreshing their cache with the updated database
        return client.shard.broadcastEval(() => this.giveawaysManager.getAllGiveaways());
    }

    // This function is called when the manager needs to get all the giveaway stored in the database.
    async getAllGiveaways(){
        // Get all the giveaway in the database
        return db.get("giveaways");
    }

    // This function is called when a giveaway needs to be saved in the database (when a giveaway is created or when a giveaway is edited).
    async saveGiveaway(messageID, giveawayData){
        // Add the new one
        db.push("giveaways", giveawayData);
        // Don't forget to return something!
        return true;
    }

    async editGiveaway(messageID, giveawayData){
        // Gets all the current giveaways
        const giveaways = db.get("giveaways");
        // Remove the old giveaway from the current giveaways ID
        const newGiveawaysArray = giveaways.filter((giveaway) => giveaway.messageID !== messageID);
        // Push the new giveaway to the array
        newGiveawaysArray.push(giveawayData);
        // Save the updated array
        db.set("giveaways", newGiveawaysArray);
        // Don't forget to return something!
        return true;
    }

    // This function is called when a giveaway needs to be deleted from the database.
    async deleteGiveaway(messageID){
        // Remove the giveaway from the array
        const newGiveawaysArray = db.get("giveaways").filter((giveaway) => giveaway.messageID !== messageID);
        // Save the updated array
        db.set("giveaways", newGiveawaysArray);
        // Don't forget to return something!
        return true;
    }

};

// Create a new instance of your new class
const manager = new GiveawayManagerWithShardSupport(client, {
    storage: false,
    updateCountdownEvery: 60000,
    hasGuildMembersIntent: false,
    default: {
        botsCanWin: false,
        embedColor: "#9a54d6",
        reaction: "🎉"
    }
});
client.giveawaysManager = manager;`

Start command

`const ms = require('ms');
const Discord = require('discord.js');

exports.run = async (client, message, args) => {
    
    const db = require('quick.db')

    const config = require(`../config/bot.js`)

    let language = db.fetch(`lang_${message.guild.id}`)

    if (language === null) language = config.basiclang

    const lang = require(`../lang/${language}.js`)

    let role = db.fetch(`role_${message.guild.id}`)

    if (role === null) role = config.grole

    // If the member doesn't have enough permissions
    if(!message.member.hasPermission('MANAGE_MESSAGES') && !message.member.roles.cache.some((r) => r.name === role)){
        return message.channel.send(lang.start.perms + "** **" + "`" + role + "`" + ".");
    }

    if (client.giveawaysManager.giveaways.filter((g) => g.guildID === message.guild.id && !g.ended).length + 1 > 10) return message.channel.send(lang.start.filter)

    

    // Giveaway channel
    let giveawayChannel = message.mentions.channels.first();
    // If no channel is mentionned
    if(!giveawayChannel){
        return message.channel.send(lang.start.channel);
    }

    // Giveaway duration
    let giveawayDuration = args[1];
    // If the duration isn't valid
    if (!giveawayDuration) return message.channel.send(lang.start.durationerror);
    if (ms(giveawayDuration) > ms("15d")) {
        return message.channel.send(lang.start.durationtime);
    }
    if(!giveawayDuration || isNaN(ms(giveawayDuration))){
        return message.channel.send(lang.start.duration);
        
    }

    // Number of winners
    let giveawayNumberWinners = args[2];
    if (giveawayNumberWinners > 25) return message.channel.send(lang.start.nbwinners);
    // If the specified number of winners is not a number
    if(isNaN(giveawayNumberWinners) || (parseInt(giveawayNumberWinners) <= 0)){
        return message.channel.send(lang.start.argswinners);
    }

    // Giveaway prize
    let giveawayPrize = args.slice(3).join(' ');
    // If no prize is specified
    if(!giveawayPrize){
        return message.channel.send(lang.start.prize);
    }

    let mention = db.fetch(`mention_${message.guild.id}`)

    if (mention === null) mention = false

    if (mention === true) {

    var text1 = "@everyone\n\n" + lang.start.giveaway
    var text2 = "@everyone\n\n" + lang.start.giveawayEnded

    }

    if (mention === false) {

        var text1 = lang.start.giveaway
        var text2 = lang.start.giveawayEnded
    
    }
    
    // Start the giveaway
    client.giveawaysManager.start(giveawayChannel, {
        
        // The giveaway duration
        time: ms(giveawayDuration),
        // The giveaway prize
        prize: giveawayPrize,
        // The giveaway winner count
        winnerCount: giveawayNumberWinners,
        // Who hosts this giveaway
        hostedBy: client.config.hostedBy ? message.author : null,
        // Messages
        messages: {
            giveaway: text1,
            giveawayEnded: text2,
            timeRemaining: lang.start.timeRemaining,
            inviteToParticipate: lang.start.inviteToParticipate(message),
            winMessage: lang.start.winMessage(message),
            embedFooter: lang.start.embedFooter,
            noWinner: lang.start.noWinner,
            hostedBy: lang.start.hostedBy,
            winners: lang.start.winners,
            endedAt: lang.start.endedAt,
            units: {
                seconds: lang.units.seconds,
                minutes: lang.units.minutes,
                hours: lang.units.hours,
                days: lang.units.days,
                pluralS: false // Not needed, because units end with a S so it will automatically removed if the unit value is lower than 2
            }
        }
    });

    message.channel.send(`${lang.start.ini} ${giveawayChannel} !`);

};`

**Comment by Nico105** [comment]
Could you please send the whole code block/part where it sends the `https://discordapp.com/channels/undefined/undefined/undefined`

**Comment by Androz2091** [comment]
Closed due to inactivity
