### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by Bloectasy** [Androz2091/discord-giveaways#16]
How may i change the storage option to a database(mongoose in my situation)? So if the bot restarts the giveaway doesn't freeze aka get uncached and not work anymore.

**Comment by thewilloftheshadow** [comment]
i believe that would take some major reworking of the code, because a lot of this is based on using a json file to store all the giveaways, but it should persist through restarts anyway. does it not for you?

**Comment by Bloectasy** [comment]
Yes it would if my host actually updated the json file.But sadly it doesn't.

**Comment by Androz2091** [comment]
Can you send your code (particularly the `launch()` function)? The issue can be that you passed a bad file path to the package.

**Comment by Bloectasy** [comment]
The db part is not necessary anymore but the
when i try to do storage: __dirname+"giveawayss.json" it doesnt log anything there as well when i try to parse the options.messages.giveaway option into the .start() it still shows the @everyone @Androz2091

**Comment by Bloectasy** [comment]
![20191205_171309](https://user-images.githubusercontent.com/47886919/70253136-f01f6c80-1782-11ea-8b07-9f488f49b349.jpg)

**Comment by Androz2091** [comment]
Hmm... Can you show your bot structure with the functions used? For example:

index.js (launch function)
src/cmd/giveaway.js (start function)
etc...

**Comment by Bloectasy** [comment]
You have discord?

**Comment by Androz2091** [comment]
Friend request sent. I will post the answer here if someone has the same problem in the future.

**Comment by Androz2091** [comment]
The problem was that the host was Glitch and it has some restrictions that cause some problems...

**Comment by thewilloftheshadow** [comment]
What restrictions would these be? I use this package in glitch perfectly with no issues at all on several different bots.

**Comment by Bloectasy** [comment]
when i try to define the storage in the index aka in the launch() function it doesn't even edit the json file as well when i try to start the giveaway i get a giveaways.filter is not a function error. As well i don't know how to remove the everyone ping.
