### ISSUE TITLE
Doc error

### ISSUE THREAD

**Issue by LePtitMetalleux** [Androz2091/discord-giveaways#160]
Thers a ) missing [here](https://discord-giveaways.js.org/GiveawaysManager.html#event:giveawayReactionAdded) 
![image](https://user-images.githubusercontent.com/59097429/103318218-08b59100-4a2e-11eb-9d5e-9c3d86299c06.png)
And [here](https://discord-giveaways.js.org/GiveawaysManager.html#event:giveawayReactionRemoved), single quotes must be double quotes or escape the single quote of "That's"
![image](https://user-images.githubusercontent.com/59097429/103318276-3995c600-4a2e-11eb-91fe-665abe6a4c33.png)

**Comment by Nico105** [comment]
I made a pr for it because whyever you made a issue instead of making a pr yourself...

**Comment by Nico105** [comment]
🎉 v4.5.0 is now released!
