### ISSUE TITLE
Show host?

### ISSUE THREAD

**Issue by IamGhostly** [Androz2091/discord-giveaways#162]
how do I show the host via embed?

**Comment by Nico105** [comment]
Isn't it there by default? _I don't remember properly_
If it is not there, then add `hostedBy: 'Hosted by: {user}'` to the `messages` property of your giveaway object.

**Comment by IamGhostly** [comment]
Yes it is but it comes back null in console and only having the timer and reaction invitation on the embed.

**Comment by Nico105** [comment]
```js
 hostedBy: message.author
 messages: {
       hostedBy: "Hosted by: {user}",
 }
```
Are you sure that you have both?

**Comment by Nico105** [comment]
@IamGhostly

**Comment by Nico105** [comment]
Closed due to inactivity
