### ISSUE TITLE
Error in Node Module

### ISSUE THREAD

**Issue by dylanjamesdev** [Androz2091/discord-giveaways#166]
```[Unhandled Rejection] TypeError: member.hasPermission is not a function
    at /Users/dylan/Desktop/Projects/Tritan-Bot/node_modules/discord-giveaways/src/Giveaway.js:306:82
    at Array.some (<anonymous>)
    at Giveaway.checkWinnerEntry (/Users/dylan/Desktop/Projects/Tritan-Bot/node_modules/discord-giveaways/src/Giveaway.js:306:54)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Giveaway.roll (/Users/dylan/Desktop/Projects/Tritan-Bot/node_modules/discord-giveaways/src/Giveaway.js:340:46)
    at async /Users/dylan/Desktop/Projects/Tritan-Bot/node_modules/discord-giveaways/src/Giveaway.js:400:29
```

**Comment by Nico105** [comment]
Ahm, you should have got a error message, shouldn't you? Please provide it.

**Comment by dylanjamesdev** [comment]
No that error was just on the function being started with the client. The giveaways also end freeze around 22 seconds without finishing.

**Comment by Nico105** [comment]
> Ahm, you should have got a error message, shouldn't you? Please provide it.

`Uncaught Promise Error:  TypeError: member.hasPermission is not a function` normally this should be it

**Comment by dylanjamesdev** [comment]
I just ran another giveaway to try and reproduce the error, it can't find the member's ID within the node module while trying to finish the giveaway. 

```[Unhandled Rejection] TypeError: Cannot read property 'id' of undefined at /root/tritan-bot/node_modules/discord-giveaways/src/Giveaway.js:338:89```

**Comment by dylanjamesdev** [comment]
> > Ahm, you should have got a error message, shouldn't you? Please provide it.
> 
> `Uncaught Promise Error: TypeError: member.hasPermission is not a function` this should be it _for protocol_

Ahh my bad I thought it was in the code snippet, that was the message yes.

**Comment by Nico105** [comment]
`npm install Androz2091/discord-giveaways#develop` that branch should have the fix, try it

**Comment by dylanjamesdev** [comment]
Thank you :)
