### ISSUE TITLE
[Suggestion] Double entries

### ISSUE THREAD

**Issue by AcrenoZ** [Androz2091/discord-giveaways#171]
Hi, I think it would be good if multiple entries can be implemented in the future version. How this work is that you can double (or maybe even triple, its up to you) the entries of a member with the @role (doubleEntryRole: @ServerBooster) or something. Sorry for bad grammar

**Comment by Nico105** [comment]
It is planned/already noted as an enhancement for the future, but it won't come to soon because it's a little complicated to write it _i tried it, so thats my experience_

**Comment by wolfier74** [comment]
Please make this

**Comment by AdamTmHun** [comment]
> It is planned/already noted as an enhancement for the future, but it won't come to soon because it's a little complicated to write it _i tried it, so thats my experience_

I do have an idea in my head, it probably won't help too much (if it would even work lol). But the bot listens for the reaction, finds the user in the database, check if it has multiple entries, if so, add the user to an array that many times, and then just roll the winner with a random number generator. And after that there goes the multiple rolled checking and stuff.

**Comment by Nico105** [comment]
> > It is planned/already noted as an enhancement for the future, but it won't come to soon because it's a little complicated to write it _i tried it, so thats my experience_
> 
> I do have an idea in my head, it probably won't help too much (if it would even work lol). But the bot listens for the reaction, finds the user in the database, check if it has multiple entries, if so, add the user to an array that many times, and then just roll the winner with a random number generator. And after that there goes the multiple rolled checking and stuff.

Yeah, the concept is to push a user who has, let us say 2 entries because of a role he has, 2 times into an array, and that is it. Now he has 2 times the chance to get rolled.
I will send my "attempt" of doing this to the discord server

**Comment by Androz2091** [comment]
@AcrenoZ why did you close the issue?

**Comment by AcrenoZ** [comment]
Nico sent his attempt in the Discord, I haven't tested it yet, I'll just reopen it again I guess?

**Comment by Nico105** [comment]
🎉 v4.5.0 is now released!
