### ISSUE TITLE
[Suggestion] Disable counter in giveaway message

### ISSUE THREAD

**Issue by DomeQdev** [Androz2091/discord-giveaways#172]
Add option `disableTimer: true`.

Or if it's alr existing way to do it, tell me

**Comment by Nico105** [comment]
`8640000000000000` use this as the time and extend the `createMainEmbed` function and check if the time is really big and if it is really big then do not display the timer or display something else.
Is that what you want? A "endless" giveaway?

**Comment by DomeQdev** [comment]
No, I want simple remove timer from embed. But I've fixed it.
