### ISSUE TITLE
Deleted message crashes bot.

### ISSUE THREAD

**Issue by DomeQdev** [Androz2091/discord-giveaways#173]
![](https://isis.tools/d715aCC.png)

**Comment by DomeQdev** [comment]
Okay, I fixed it, but add it in next update `src/Manager.ejs:398`:
`giveaway.message.edit(giveaway.messages.giveaway, { embed }).catch(() => {})`

**Comment by wolfier74** [comment]
Make that bot will delete the giveaway from database when message was deleted

**Comment by Androz2091** [comment]
I agree with @Nico105, and I would like to add that personally I like that my bot can resume a giveaway even if for a few minutes it was removed from the giveaway channel for example. But indeed, it's very painful to receive error messages in the terminal so I added .catch and it no longer logs them.

(will be available in the next release)
