### ISSUE TITLE
Remove old winners reactions before calling reroll?

### ISSUE THREAD

**Issue by wolfier74** [Androz2091/discord-giveaways#174]
How to remove user's reaction on giveaway reroll?

**Comment by Nico105** [comment]
With the `endedGiveawayReactionAdded` event you can remove reactions that get added to a giveaway that is already ended, if that is what you want.
If it is not, then please provide a more precise description of which user reactions should get removed.

**Comment by wolfier74** [comment]
When i reroll the giveaway i want that the old winner's reaction will be removed, so when i will reroll giveaway more times, the original and reroller winners will be not selected

**Comment by Androz2091** [comment]
@wolfier74 you need to do it before calling `client.giveawaysManager.reroll()`. For example:
```js
const messageID = args.join(' ');
if (!messageID) return message.channel.(':x: Please send the message ID of the giveaway you want to reroll!');

const giveaway = client.giveawaysManager.giveaways.find((g) => g.messageID === messageID);
await giveaway.fetchMessage(); // make sure giveaway.message is available

const reaction = giveaway.message.reactions.first();
const oldWinners = giveaway.winnerIDs;
oldWinners.forEach((oldWinner) => reaction.users.remove(oldWinner));
```

something like that should work
