### ISSUE TITLE
TypeError: Cannot read property 'forEach' of null

### ISSUE THREAD

**Issue by typhoon11** [Androz2091/discord-giveaways#175]
I changed my database from quick.db to quickmongo so I used your code. But now I am getting this error.
![image](https://user-images.githubusercontent.com/66431066/104006893-22dd3500-51cd-11eb-9305-f6f8b5e22938.png)

**Comment by Nico105** [comment]
```js
db.once('ready', async () => {
    if ((await db.get('giveaways')) === null) await db.set('giveaways', []);
});
```
Are you sure that you have this?

**Comment by typhoon11** [comment]
Yeah I have that.
![image](https://user-images.githubusercontent.com/66431066/104012942-b5ce9d00-51d6-11eb-9bf4-996bfd4a981a.png)

**Comment by typhoon11** [comment]
I figured out the problem. `db.once` is not an option anymore so it will be `db.on`
