### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by AdamTmHun** [Androz2091/discord-giveaways#176]
I didn't find any resources that this package already has this, so I am writing it down.

1. Role requirement.
 > I think I don't have to explain this one.

2. Custom requirements.
> By this, I mean for example, if the bot has a levelling system, then the dev could link the package with the lvl system, and then the users could set a level requirement for the giveaway. I hope this is possible since I am not really sure.

**Comment by Nico105** [comment]
https://discord-giveaways.js.org RTMFD

`giveawayReactionAdded` event _there litterly is an example for the role requirement already_ use the 
`extraData` property of the giveaway object to pass the role ID or the role Name to the event

`exemptMembers` function to make sure that if for example the role gets removed from the user when he already reacted, then he will still not be able to win

**Comment by AdamTmHun** [comment]
o sorry mister
