### ISSUE TITLE
DM the host of the giveaway when giveaway ended?

### ISSUE THREAD

**Issue by WideIrenaKan2** [Androz2091/discord-giveaways#179]
The title said it all, maybe a setting to dm the host that their giveaway ended. Or is there already a way to do that? If so how

**Comment by Nico105** [comment]
https://discord-giveaways.js.org/GiveawaysManager.html#event:giveawayEnded
https://discord-giveaways.js.org/Giveaway.html#hostedBy
I think that should explain it.

**Comment by Nico105** [comment]
@WideIrenaKan2

**Comment by WideIrenaKan2** [comment]
oh ok
