### ISSUE TITLE
Giveaway crashed

### ISSUE THREAD

**Issue by Ronak0020** [Androz2091/discord-giveaways#18]
I created a giveaway of 5 days.
It was alright for 2 days but just right now, it crashed....
I didn't even re-start it.... If i restart the bot, then the Giveaways are crashed but i have not done so...
Is there any way i can continue that giveaway?
and also, is there any way to prevent crashes like this even if i restart my bot?

**Comment by Ronak0020** [comment]
Please make it use an online database. the local database doesn't support restart if the bot is deployed...

**Comment by INEX07** [comment]
@Ronak0020 are you using heroku?

**Comment by Ronak0020** [comment]
yes... i am using heroku...

**Comment by INEX07** [comment]
@Ronak0020 so heroku is the problem. There's nothing wrong with the package

**Comment by Ronak0020** [comment]
i know this... because on using heroku free dyno, bot restarts every day...
and the data that was stored in the heroku's server gets erased...
But if this package starts using MongoDB, heroku server will not be used
for storage and MongoDB will be used by which the bot will be able to fetch
giveaway data from MongoDB server even if it is restarted....
