### ISSUE TITLE
Remove 'watermark' from giveaway message?

### ISSUE THREAD

**Issue by AdamTmHun** [Androz2091/discord-giveaways#180]
It would be cool to remove that. I would mention this package in another way.

**Comment by Nico105** [comment]
`embedFooter: 'something'` just change it = add it to your giveaway object, the "watermark" is just the default value

**Comment by AdamTmHun** [comment]
Could you be more specific? I tried to change the embedFooter in the setup, and when creating a giveaway but it didn't work.

**Comment by Nico105** [comment]
```js
client.giveawaysManager.start(giveawayChannel, {
        // The giveaway duration
        time: ms(giveawayDuration),
        // The giveaway prize
        prize: giveawayPrize,
        // The giveaway winner count
        winnerCount: giveawayNumberWinners,
        // Who hosts this giveaway
        hostedBy: client.config.hostedBy ? message.author : null,
        // Messages
        messages: {
            giveaway: (client.config.everyoneMention ? "@everyone\n\n" : "")+"🎉🎉 **GIVEAWAY** 🎉🎉",
            giveawayEnded: (client.config.everyoneMention ? "@everyone\n\n" : "")+"🎉🎉 **GIVEAWAY ENDED** 🎉🎉",
            timeRemaining: "Time remaining: **{duration}**!",
            inviteToParticipate: "React with 🎉 to participate!",
            winMessage: "Congratulations, {winners}! You won **{prize}**!",
            embedFooter: "SOMETEXTHERE",
            noWinner: "Giveaway cancelled, no valid participations.",
            hostedBy: "Hosted by: {user}",
            winners: "winner(s)",
            endedAt: "Ended at",
            units: {
                seconds: "seconds",
                minutes: "minutes",
                hours: "hours",
                days: "days",
                pluralS: false // Not needed, because units end with a S so it will automatically removed if the unit value is lower than 2
            }
        }
    });
```
My bad, forgot to say that it gets into the messages object of the giveaway object

**Comment by AdamTmHun** [comment]
Okay, thank you very much :)

**Comment by AdamTmHun** [comment]
and is there a way to wipe all of the giveaways? I noticed that when I delete the content of the giveaway json file, it just puts it back when I create another giveaway.

**Comment by Nico105** [comment]
Delete the whole file or add the following somewher to your code
```js
client.giveawaysManager.giveaways.filter((g) => !g.ended).forEach(g => client.giveawaysManager.deleteGiveaway(g.messageID))
```

**Comment by AdamTmHun** [comment]
Thanks a lot :)

**Comment by AdamTmHun** [comment]
Hi @Nico105 , So i tried what you have said to edit the footer, I tried both as default and when staring the giveaway but it didn't work. Heres the code of the file:

**Comment by Nico105** [comment]
```js
client.giveawaysManager.start(collected[3].mentions.channels.first(), {
	time: ms(collected[1].content),
	prize: collected[0].content,
	hostedBy: message.author,
	winnerCount: parseInt(collected[2].content),
	// Messages
        messages: {
                embedFooter: `Lightning Giveaways`,
                giveaway:
                '<:confetti:797773765407801354><:confetti:797773765407801354**GIVEAWAY** <:confetti:797773765407801354><:confetti:797773765407801354>',
                giveawayEnded:
                '<:confetti:797773765407801354><:confetti:797773765407801354 **GIVEAWAY ENDED** <:confetti:797773765407801354><:confetti:797773765407801354>',
                timeRemaining: 'Time remaining: **{duration}**!',
                inviteToParticipate:
                'React with <:confetti:797773765407801354> to participate!',
                winMessage: 'Congratulations, {winners}! You won **{prize}**!',
                embedFooter: 'Lightning Giveaways',
                noWinner: 'Giveaway cancelled, no valid participations.',
                hostedBy: 'Hosted by: {user}',
                winners: 'winner(s)',
                endedAt: 'Ended at',
                units: {
                seconds: 'seconds',
                minutes: 'minutes',
                hours: 'hours',
                days: 'days',
                pluralS: false
                }
        }
})
```
You did not look closely at what i sent you/what i said
Fixed your code for you

**Comment by Nico105** [comment]
![image](https://user-images.githubusercontent.com/63612668/104449072-538ee700-559e-11eb-80d7-12ce14677b10.png)
I guess you just forgot about it 😂

**Comment by Nico105** [comment]
> ```js
> client.giveawaysManager.start(collected[3].mentions.channels.first(), {
> 	time: ms(collected[1].content),
> 	prize: collected[0].content,
> 	hostedBy: message.author,
> 	winnerCount: parseInt(collected[2].content),
> 	// Messages
>         messages: {
>                 embedFooter: `Lightning Giveaways`,
>                 giveaway:
>                 '<:confetti:797773765407801354><:confetti:797773765407801354**GIVEAWAY** <:confetti:797773765407801354><:confetti:797773765407801354>',
>                 giveawayEnded:
>                 '<:confetti:797773765407801354><:confetti:797773765407801354 **GIVEAWAY ENDED** <:confetti:797773765407801354><:confetti:797773765407801354>',
>                 timeRemaining: 'Time remaining: **{duration}**!',
>                 inviteToParticipate:
>                 'React with <:confetti:797773765407801354> to participate!',
>                 winMessage: 'Congratulations, {winners}! You won **{prize}**!',
>                 embedFooter: 'Lightning Giveaways',
>                 noWinner: 'Giveaway cancelled, no valid participations.',
>                 hostedBy: 'Hosted by: {user}',
>                 winners: 'winner(s)',
>                 endedAt: 'Ended at',
>                 units: {
>                         seconds: 'seconds',
>                         minutes: 'minutes',
>                         hours: 'hours',
>                         days: 'days',
>                         pluralS: false
>                 }
>         }
> })
> ```
> 
> You did not look closely at what i sent you/what i said
> Fixed your code for you

@AdamTmHun Any more questions?

**Comment by Nico105** [comment]
Closed due to inactivity
