### ISSUE TITLE
Problem with winners

### ISSUE THREAD

**Issue by PHANTOM-14** [Androz2091/discord-giveaways#184]
![Screenshot_20210115-202136](https://user-images.githubusercontent.com/73062410/104741602-7290a300-576f-11eb-8261-266ace51ba34.jpg)
It was supposed to be 2 instead of 4 ;-;

**Comment by Nico105** [comment]
Have you checked if `winnerCount:` gets the right value in the options of `.start()` or `.reroll()`?
And do you have the latest version of the module?

**Comment by hydrascript** [comment]
here have same problem

**Comment by PHANTOM-14** [comment]
> Have you checked if `winnerCount:` gets the right value in the options of `.start()` or `.reroll()`?
> And do you have the latest version of the module?

Yes I have latest version

**Comment by Nico105** [comment]
and your `winnerCount:` gets the right value in your code?

**Comment by PHANTOM-14** [comment]
> and your `winnerCount:` gets the right value in your code?
> If you do `console.log(client.giveawaysManager.giveaways.find(g => !g.ended && g.messageID === 'giveawayID').winnerCount)` does it have the right value?

Checking it rn

**Comment by PHANTOM-14** [comment]
Yeah got it a function got wrong thanks for help.
: D
