### ISSUE TITLE
Error in json

### ISSUE THREAD

**Issue by megavirus2** [Androz2091/discord-giveaways#186]
![image](https://user-images.githubusercontent.com/52457549/104810841-1590fd80-5800-11eb-976c-14f49a91ba74.png)
How fix?

**Comment by Nico105** [comment]
Ahm i guess you remove it... because it does not seem that it should be there, should it?

**Comment by megavirus2** [comment]
Yes, I am deleting. But it reappears

**Comment by Nico105** [comment]
Have you checked if you yourself maybe added it into the giveaway object by accident somewhere in your code?
Because I checked the module files and there is nowhere a typo that would cause this.

**Comment by megavirus2** [comment]
It appears randomly
Now i'm testing. Does not appears

**Comment by Nico105** [comment]
But i guess always at the same place in the giveaway objects?
If you use VSCode then please press F3 and check for "ull" in your code files.

**Comment by megavirus2** [comment]
yeah
![image](https://user-images.githubusercontent.com/52457549/104815950-952ec480-5820-11eb-840d-6a01f28361b0.png)

**Comment by Spiderjockey02** [comment]
yes i can confirm, I get this error A LOT too when using the JSON file

**Comment by jameslinimk** [comment]
> yes i can confirm, I get this error A LOT too when using the JSON file

Easy fix, `npm i quick.db`. Copy and paste code from the bottom of the homepage

**Comment by jameslinimk** [comment]
also, JSON is prone to corruptions alot. So unless your dealing with 1-2 servers, i'd recomend switching to a database.

**Comment by Nico105** [comment]
@megavirus2 @Spiderjockey02 About how many giveaways in total are in your .json file? And in how many servers does your bot operate?
Because as james said, could it be because the .json file is overused/it got corrupted because of the heavy workload it isn't designed for?

**Comment by Spiderjockey02** [comment]
I'm running this on my test server on my test bot. So only 1 server on my bot, with 1-3 giveaways happening at once. All of them would error out.

**Comment by Nico105** [comment]
Does it make a difference if you create the .json file yourself or if you let the bot do it automatically?

**Comment by Spiderjockey02** [comment]
I don't know I haven't tested when manually creating it.
I would like to point out that I use my database now for storing giveaways.
So I was just making people aware that there could be a bug for JSON storing.

**Comment by Nico105** [comment]
Did you have made any special change to the package = extended a function or tried to do smth with it that could be problematic?
Or was it the plain package with no changes like in https://github.com/Androz2091/giveaways-bot

**Comment by WiseDevHelper** [comment]
This error occurs a lot in JSON files due to something called race conditions. You can read more about it [here](https://en.wikipedia.org/wiki/Race_condition#:~:text=A%20race%20condition%20arises%20in,depend%20on%20some%20shared%20state. 'Wikipeda on race conditions.').

**Comment by Androz2091** [comment]
The race conditions are not really applicable here, because the giveaways file is only read after the GiveawaysManager instance is created. Therefore, I think it is theoretically not possible for the file to be corrupted.

**Comment by WiseDevHelper** [comment]
Don't the corruptions occur after the GiveawaysManager instance is created?
