### ISSUE TITLE
[Issue] Costum emoji

### ISSUE THREAD

**Issue by AdamTmHun** [Androz2091/discord-giveaways#189]
Hey, I don't know if this is a known problem, but it looks like that if I try to add a custom emoji as `GiveawaysManager.options.reaction` (example: `<:confetti:797773765407801354>`) then the whole system breaks. No events will be emitted (tried out with `giveawayReactionAdded`). The reactions won't count as valid reactions, and as a result, no winners will be picked as winners.

Please fix this problem, I would like to use custom emojis.

**Comment by Nico105** [comment]
`797773765407801354` you only have to provide this

**Comment by AdamTmHun** [comment]
O alr, thanks a lot
