### ISSUE TITLE
Issue due installing 

### ISSUE THREAD

**Issue by MarijoMiksa** [Androz2091/discord-giveaways#19]
So when i execute "npm install discord-giveaways" it shows this error

npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "discord-giveaways" under a package
npm ERR! also called "discord-giveaways". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Zarko\AppData\Roaming\npm-cache\_logs\2019-12-14T11_17_16_918Z-debug.log

**Comment by Androz2091** [comment]
It says your project is named `discord-giveaways`. Do you have a `package.json` file in your project folder?

**Comment by MarijoMiksa** [comment]
I do

**Comment by Androz2091** [comment]
Can you send it here please?

**Comment by MarijoMiksa** [comment]
{
  "name": "discord-giveaways",
  "version": "2.4.3",
  "description": "A complete framework to facilitate the creation of giveaways using discord.js",
  "main": "index.js",
  "scripts": {
    "test": "node index.js"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/packcord/discord-giveaways.git"
  },
  "keywords": [
    "discord",
    "discord.js",
    "giveaways",
    "winner",
    "framework",
    "bot",
    "discord-giveaways",
    "discord giveaways",
    "giveaway"
  ],
  "author": "Androz2091",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/packcord/discord-giveaways/issues"
  },
  "homepage": "https://github.com/packcord/discord-giveaways#readme",
  "dependencies": {
    "randomstring": "^1.1.5"
  }
}

**Comment by Androz2091** [comment]
You must enter the `npm install discord-giveaways` command in your bot project folder

**Comment by MarijoMiksa** [comment]
Ye let me try

**Comment by MarijoMiksa** [comment]
![image](https://user-images.githubusercontent.com/49322724/70848094-da8a0100-1e6c-11ea-894b-391176fe456c.png)

**Comment by Androz2091** [comment]
Why are you trying to install `discord-giveaways` in a folder named `discord-giveaways`?

**Comment by MarijoMiksa** [comment]
Where to install it then?

**Comment by MarijoMiksa** [comment]
O yea i see i just entered it in CMD, i hope its fixed if i get an error ill contact u

**Comment by MarijoMiksa** [comment]
Thanks for your time

**Comment by Androz2091** [comment]
Discord Giveaways is a framework, a library to facilitate the creation of giveaways. But you have to create your main script, which make calls to `discord-giveaways` library. Create a folder with your main script, then install the library and you will be able to use the `discord-giveaways` methods and to call it.
