### ISSUE TITLE
The channels I mentioned are a server channel but they do not accept

### ISSUE THREAD

**Issue by eare-emirhan** [Androz2091/discord-giveaways#191]
![image](https://user-images.githubusercontent.com/67333585/105398682-b4b85980-5c33-11eb-9f82-dfce7555b590.png)
![image](https://user-images.githubusercontent.com/67333585/105398739-c3067580-5c33-11eb-976e-784ffff7d729.png)

**Comment by Nico105** [comment]
```js
const giveawayChannel = message.mentions.channels.first();
client.giveawaysManager.start(giveawayChannel, {
```
You have that?

**Comment by eare-emirhan** [comment]
> ```js
> const giveawayChannel = message.mentions.channels.first();
> client.giveawaysManager.start(giveawayChannel, {
> ```
> 
> You have that?

I was having a problem in the "mentions" part, when I fixed that part, this error was also fixed, sorry for opening unnecessary issue

**Comment by eare-emirhan** [comment]
after i finished this thing i noticed that such an error occurred
![image](https://user-images.githubusercontent.com/67333585/105410205-a4f44180-5c42-11eb-9e59-9e38e0267b38.png)

**Comment by eare-emirhan** [comment]
this error occurs when a giveaway ends

**Comment by Nico105** [comment]
This is a error from `quickmongo`, I did not really figure out yet how to fix it but it's not `discord-giveaways` itself that is causing this.
https://github.com/Automattic/mongoose/issues/9506

**Comment by eare-emirhan** [comment]
> This is a error from `quickmongo` based on `mongoose`. [Automattic/mongoose#9506](https://github.com/Automattic/mongoose/issues/9506)
> I did not really figure out yet how to fix it but it's not `discord-giveaways` itself that is causing this.

can't i fix this error?

**Comment by eare-emirhan** [comment]
(I have one more question: is this error important? So can the giveaways created by this error be broken, or could a serious problem occur?)

**Comment by Nico105** [comment]
> > This is a error from `quickmongo` based on `mongoose`. [Automattic/mongoose#9506](https://github.com/Automattic/mongoose/issues/9506)
> > I did not really figure out yet how to fix it but it's not `discord-giveaways` itself that is causing this.
> 
> can't i fix this error?

If you find out how, as said idk yet

**Comment by Nico105** [comment]
> (I have one more question: is this error important? So can the giveaways created by this error be broken, or could a serious problem occur?)

The giveawa(s) it/themself should not get broken but what happens is that a the functions you extended in your `giveawaysManagerWithOwnDataBase` don't execute properly/stop executing when the issue happens

**Comment by eare-emirhan** [comment]
understood 😕
