### ISSUE TITLE
Giveaway after 1 day dont work.

### ISSUE THREAD

**Issue by megavirus2** [Androz2091/discord-giveaways#193]
My bot stops editing the message one day after starting. And at the end of the draw, the winner is not announced

**Comment by Nico105** [comment]
Have you checked if it is still in your DB?

**Comment by megavirus2** [comment]
Yes, it in my DB

**Comment by Nico105** [comment]
Was there any error?
Does your bot still have the permission to edit messages inside of the giveaway channel?

**Comment by megavirus2** [comment]
Not errors, bot have administrator permissions

**Comment by Nico105** [comment]
Did this problem happen more than once?

**Comment by megavirus2** [comment]
Yes

**Comment by Nico105** [comment]
Are you using the default .json or quick.db DB and host that on heroku or glitch?

**Comment by megavirus2** [comment]
1) .json
2) heroku

**Comment by Nico105** [comment]
https://stackoverflow.com/questions/24033251/heroku-resets-my-json-file

Heroku has a ephemeral hard drive, that basically means that the hard drive is cleared everytime you start a new process
https://devcenter.heroku.com/articles/active-storage-on-heroku
theres no actual solution but a workaround, its to use another database that you dont store on the hard drive, such as mongoDB
https://www.mongodb.com/cloud/atlas

We have 2 examples for using mongoDB
[Mongoose example](https://github.com/Androz2091/discord-giveaways/blob/master/examples/custom-databases/mongoose.js)
- [QuickMongo example](https://github.com/Androz2091/discord-giveaways/blob/master/examples/custom-databases/quickmongo.js)
