### ISSUE TITLE
Can I predefine members?

### ISSUE THREAD

**Issue by typhoon11** [Androz2091/discord-giveaways#194]
I was wondering that can I predefine the winners in the manager, so when the giveaway ends the winners are from those predefined members not others. If this is possible please help me with this, I need this for one server bot. Thank You in advance.

**Comment by Nico105** [comment]
You can use `exemptMembers` to exclude people because it is a function and when it returns true for a member then the member cannot win.
But I hope you are not asking this because you want to scam people/fake giveaways...

**Comment by AcrenoZ** [comment]
I'm sorry but rigging giveaways is the only thing that is going in my mind when you will predefine winners...

**Comment by typhoon11** [comment]
Yeah in a way it's scamming people cuz the server wants that only. So is there a option in the manager to something like this or it's not possible

**Comment by Nico105** [comment]
`exemptMembers` as said already, but I highly suggest you  refrain from doing anything scammy especially because it could get you banned, I guess you maybe got offered money but is that really worth the trouble and the bad consciencec _if you have any_ ?

**Comment by Nico105** [comment]
@typhoon11 https://discord-giveaways.js.org/Giveaway.html#exemptMembers
But as said don't try anything scamy, it isn't worth it.

**Comment by typhoon11** [comment]
> @typhoon11 https://discord-giveaways.js.org/Giveaway.html#exemptMembers
> But as said don't try anything scamy, it isn't worth it.

Thank You
