### ISSUE TITLE
MongoDB Error

### ISSUE THREAD

**Issue by Dragonizedpizza** [Androz2091/discord-giveaways#197]
I get the following error when I try to host a giveaway. 
`(node:5688) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'giveawaysManager' of undefined
    at Object.run (C:\Users\akyra\Desktop\Bots\DragonNight\bot-files\commands\giveaways\gstart.js:17:25)`
    
Code: ```js
const ms = require("ms");
const num = require("num-parse");
const emojis = require('../../utilities/emojis.json');
const config = require('../../../config.json')
module.exports = {
  name: "gstart",
  aliases: ['gs', 'giveawaystart', 'g-start', 'giveaway', 'gcreate'],
  description: "Starts a giveaway!",
  run: async(client, message, args) => {
      if (!message.member.hasPermission("MANAGE_GUILD") && !message.member.roles.cache.includes(r => r.name.toLowerCase() === "Giveaway Manager")) {
return message.channel.send({ embed: {
    title: "An Error Occured.",
    description: "Smh, you need the `MANAGE_GUILD` permission or the role `Giveaway Manager` to host a giveaway."
}})
        } else if (message.author.id === this.ownerId) return true

        if (this.client.giveawaysManager.giveaways.filter((g) => g.guildID === message.guild.id && !g.ended).length + 1 > 10) return this.sendErrorMessage(message, 0, "Maximum giveaway limit 10 reached! Please try again later.");
        let time = args[0];
        if (!time) return message.channel.send({ embed: {
            title: "An Error Occured.",
            description: `You need to mention the giveaway time as well! \n Ex: \`${config.prefix}gstart 1d 1w Discord Nitro\``,
            fields: [
                {
                    name: "Time Values",
                    value: "TiS = second.\nH = hour. \n D = day. \n W = week. \n These do not have to be in capital. \n **Remember**, a giveaway can only last 20 days maximum.",
                },
                {
                    name: "Winner Values",
                    value: "W stands for winner. **Remember**, the maximum giveaway winner count should be less than 15."
                }
            ],
            footer: {text: "How do you think I'll host a giveaway without the time given smh?"}
        }})
        if (ms(time) > ms("20d")) return message.channel.send({ embed: {
            title: "An Error Occured.",
            description: `The giveaway duration has to be lesser than 20 days. \n Ex: \`${config.prefix}gstart 1d 1w Discord Nitro\``,
            fields: [
                {
                    name: "Time Values",
                    value: "TiS = second.\nH = hour. \n D = day. \n W = week. \n These do not have to be in capital.",
                },
                {
                    name: "Winner Values",
                    value: "W stands for winner. **Remember**, the maximum giveaway winner count should be less than 15."
                }
            ]
        }})
        let winners = args[1];
        if (!winners) return message.channel.send({ embed: {
            title: "An Error Occured.",
            description: `Please provide a valid winner count! \n Ex: \`${config.prefix}gstart 1d 1w Discord Nitro\``,
            fields: [
                {
                    name: "Time Values",
                    value: "TiS = second.\nH = hour. \n D = day. \n W = week. \n These do not have to be in capital. \n **Remember**, a giveaway can only last 20 days maximum.",
                },
                {
                    name: "Winner Values",
                    value: "W stands for winner. **Remember**, the maximum giveaway winner count should be less than 15."
                }
            ],
            footer: {text: "Imagine a giveaway without any winners-"}
        }})
        winners = num(winners, 1);
        if (winners > 15) return message.channel.send({ embed: {
            title: "An Error Occured.",
            description: `The giveaway winners should be lesser than 15. \n Ex: \`${config.prefix}gstart 1d 8w Discord Nitro\``,
            fields: [
                {
                    name: "Time Values",
                    value: "TiS = second.\nH = hour. \n D = day. \n W = week. \n These do not have to be in capital. \n **Remember**, a giveaway can only last 20 days maximum.",
                },
                {
                    name: "Winner Values",
                    value: "W stands for winner."
                }
            ]
        }})
        let prize = args.slice(2).join(" ");
        if (!prize) return message.channel.send({ embed: {
            title: "An Error Occured.",
            description: `Please mention a valid giveaway prize! \n Ex: \`${config.prefix}gstart 1d 1w Discord Nitro\``,
            fields: [
                {
                    name: "Time Values",
                    value: "TiS = second.\nH = hour. \n D = day. \n W = week. \n These do not have to be in capital. \n **Remember**, a giveaway can only last 20 days maximum.",
                },
                {
                    name: "Winner Values",
                    value: "W stands for winner. **Remember**, the maximum giveaway winner count should be less than 15."
                }
            ]
        }})
        this.client.giveawaysManager.start(message.channel, {
            time: ms(time),
            winnerCount: winners,
            prize: prize,
            hostedBy: message.author,
            messages: {
                giveaway: `${emojis.giveaways} **Giveaway** ${emojis.giveaways}`,
                giveawayEnded: "🎊 **Giveaway Ended!** 🎊",
                timeRemaining: "Time left: **{duration}**!",
                inviteToParticipate: "React with \"🎉\" to participate!",
                winMessage: "🎊 Congrats, {winners} for winning **{prize}**!",
                embedFooter: `${this.client.user.tag}`,
                noWinner: "Nobody won because of the invalid participations!",
                hostedBy: "Hosted by: {user}",
                winners: "winner(s)",
                endedAt: "Ended at",
                units: {
                    seconds: "seconds",
                    minutes: "minutes",
                    hours: "hours",
                    days: "days"
                }
            }
        });
        if (message.deletable) message.delete();
        return;
    }
}

Why is `this.client` coming up as undefined?

**Comment by Nico105** [comment]
Show how you create your manager

**Comment by Dragonizedpizza** [comment]
I suppose it is...

**Comment by Dragonizedpizza** [comment]
TypeError: Cannot read property 'giveaways' of undefined

**Comment by Dragonizedpizza** [comment]
const { GiveawaysManager } = require('discord-giveaways');
    message.client.giveawaysManager = new GiveawaysManager(client, {
     storage: "./data/giveaways.json",
     updateCountdownEvery: 6969,
     default: {
        botsCanWin: false,
        embedColor: "#FF0000",
        reaction: "🎉"
    }
})

**Comment by Dragonizedpizza** [comment]
ah wait I thought I'd used this.client.giveawaysManager

**Comment by Dragonizedpizza** [comment]
But it shouldn't matter though, why does it come up as undefined?

**Comment by Nico105** [comment]
> ```
> const { GiveawaysManager } = require('discord-giveaways');
> message.client.giveawaysManager = new GiveawaysManager(client, {
>  storage: "./data/giveaways.json",
>  updateCountdownEvery: 6969,
>  default: {
>     botsCanWin: false,
>     embedColor: "#FF0000",
>     reaction: "🎉"
> }
> ```
> 
> })

you don't do that in your command file....

```js
const client = new Disocrd.Client()
const { GiveawaysManager } = require('discord-giveaways');
const manager = new GiveawaysManager(client, {
 storage: "./data/giveaways.json",
 updateCountdownEvery: 6969,
 default: {
    botsCanWin: false,
    embedColor: "#FF0000",
    reaction: "🎉"
}
client.giveawaysManager = manager;
```
you should do it like that in your startup (index or bot .js) file or some other file which gets required on startup

**Comment by Dragonizedpizza** [comment]
I don't, I do it in my client.

**Comment by Nico105** [comment]
show me that

**Comment by Dragonizedpizza** [comment]
const Discord = require('discord.js');
const client = new Discord.Client();
const config = require('../../config.json');
client.on('message', async message => {

    const prefixMention = new RegExp(`^<@!?${client.user.id}>( |)$`);
    if (message.content.match(prefixMention)) {
    return message.channel.send(`Hii! <@${message.author.id}>, My prefix is \`${config.prefix}\`!`);
 }
    if(message.author.bot || message.channel.type === "dm") return;
    if (!message.content.startsWith(config.prefix)) return;
    if (!message.guild) return;
    if (!message.member) message.member = await message.guild.fetchMember(message);
    const args = message.content.slice(config.prefix.length).trim().split(/ +/g);
    const cmd = args.shift().toLowerCase();
    if (cmd.length == 0) return;
    let command = client.commands.get(cmd)
    if (!command) command = client.commands.get(client.aliases.get(cmd));
    if (command) command.run(client, message, args)

    const { GiveawaysManager } = require('discord-giveaways');
    client.giveawaysManager = new GiveawaysManager(client, {
     storage: "./data/giveaways.json",
     updateCountdownEvery: 6969,
     default: {
        botsCanWin: false,
        embedColor: "#FF0000",
        reaction: "🎉"
    }
})
  }) 
const mongoconnect = require('../utilities/mongoconnect.js')

const connectmongo = async () => {
  await mongoconnect().then((mongoose) => {
    try {
      console.log('MongoDB Connected!')
    } finally {
      mongoose.connection.close()
    }
    })
  } 
connectmongo()

module.exports = client;

**Comment by Nico105** [comment]
```js
const Discord = require('discord.js');
const client = new Discord.Client();
const config = require('../../config.json');

const { GiveawaysManager } = require('discord-giveaways');
client.giveawaysManager = new GiveawaysManager(client, {
 storage: "./data/giveaways.json",
 updateCountdownEvery: 6969,
 default: {
    botsCanWin: false,
    embedColor: "#FF0000",
    reaction: "🎉"
}
})

client.on('message', async message => {

const prefixMention = new RegExp(`^<@!?${client.user.id}>( |)$`);
if (message.content.match(prefixMention)) {
return message.channel.send(`Hii! <@${message.author.id}>, My prefix is \`${config.prefix}\`!`);
}
if(message.author.bot || message.channel.type === "dm") return;
if (!message.content.startsWith(config.prefix)) return;
if (!message.guild) return;
if (!message.member) message.member = await message.guild.fetchMember(message);
const args = message.content.slice(config.prefix.length).trim().split(/ +/g);
const cmd = args.shift().toLowerCase();
if (cmd.length == 0) return;
let command = client.commands.get(cmd)
if (!command) command = client.commands.get(client.aliases.get(cmd));
if (command) command.run(client, message, args)
})
const mongoconnect = require('../utilities/mongoconnect.js')

const connectmongo = async () => {
await mongoconnect().then((mongoose) => {
try {
console.log('MongoDB Connected!')
} finally {
mongoose.connection.close()
}
})
}
connectmongo()

module.exports = client;
```

**Comment by Dragonizedpizza** [comment]
`TypeError: Cannot read property 'giveawaysManager' of undefined`

**Comment by Nico105** [comment]
in your command file you now have to use `client.giveawaysManger` without the .this

**Comment by Nico105** [comment]
If it does not work then try changing
```js
const manager = new GiveawaysManager(client, {
 storage: "./data/giveaways.json",
 updateCountdownEvery: 6969,
 default: {
    botsCanWin: false,
    embedColor: "#FF0000",
    reaction: "🎉"
}
})
client.giveawaysManager = manager
```

**Comment by Dragonizedpizza** [comment]
@Nico105 any idea why its happening?

**Comment by Nico105** [comment]
show the line where the error happens

**Comment by Nico105** [comment]
`module.exports = client;` btw what do you do with that?

**Comment by Dragonizedpizza** [comment]
in index.js I define my client using that

**Comment by Dragonizedpizza** [comment]
also line 17 is
`        if (this.client.giveawaysManager.giveaways.filter((g) => g.guildID === message.guild.id && !g.ended).length + 1 > 10) return message.channel.send({ embed: {`

**Comment by Nico105** [comment]
> in index.js I define my client using that

so you do `class extends`?

**Comment by Dragonizedpizza** [comment]
nah I just do const client = require(path)

**Comment by Nico105** [comment]
kk

**Comment by Nico105** [comment]
> also line 17 is
> ` if (this.client.giveawaysManager.giveaways.filter((g) => g.guildID === message.guild.id && !g.ended).length + 1 > 10) return message.channel.send({ embed: {`

i said you should remove the this... or is it the same error without the this?

**Comment by Dragonizedpizza** [comment]
what do I do tho-

**Comment by Dragonizedpizza** [comment]
oh

**Comment by Dragonizedpizza** [comment]
I'd remove it, but I'd like 10 gws max limit.
Along with that, its picking up `this.client` as undefined, meaning when starting the giveaway, I'd get the same error.

**Comment by Nico105** [comment]
`if (client.giveawaysManager.giveaways.filter((g) => g.guildID === message.guild.id && !g.ended).length + 1 > 10) return message.channel.send({ embed: {`
`client.giveawaysManager.start(message.channel, {`
I am just talking about removing the `this`, not the whole line....

**Comment by Dragonizedpizza** [comment]
I'm pretty sure it won't change much, but I'll try.

**Comment by Dragonizedpizza** [comment]
Take it back, it worked now.

**Comment by Dragonizedpizza** [comment]
Idk how it made a difference though...

**Comment by Nico105** [comment]
What you don't say....

> Take it back, it worked now.

**Comment by Nico105** [comment]
> Idk how it made a difference though...

because you `this.client !== client` and you used `client.giveawaysManager = new GiveawaysManager`
Just think logicall........

**Comment by Dragonizedpizza** [comment]
alright
also, if I set the storage to a mongodb uri, does it automatically handle the mongodb for me?

**Comment by Nico105** [comment]
https://github.com/Androz2091/discord-giveaways/blob/develop/examples/custom-databases/mongoose.js
Look at this

**Comment by Dragonizedpizza** [comment]
So it doesn't.

**Comment by Nico105** [comment]
no

**Comment by Dragonizedpizza** [comment]
also, if I changed client in the client.js to message.client, would it have allowed me to use this.client?

**Comment by Nico105** [comment]
> also, if I changed client in the client.js to message.client, would it have allowed me to use this.client?

no and you should 100% not put your manager code in your `message` event.....

**Comment by Dragonizedpizza** [comment]
oh
alright, tysm for all your help!

**Comment by Nico105** [comment]
https://github.com/Androz2091/giveaways-bot
That is the example bot of this package, look at the code if you need to better understand

**Comment by Nico105** [comment]
> oh
> alright, tysm for all your help!

np

**Comment by Dragonizedpizza** [comment]
@Nico105 wait nvm I wanted to ask 1 more thing, 
`
        exemptPermissions: ['MANAGE_MESSAGES', 'ADMINISTRATOR'],` 
        what does that mean?
        Is that the perms allowed to host a giveaway?

**Comment by SimonLeclere** [comment]
These are the permissions required to win the giveaway

**Comment by SimonLeclere** [comment]
Oh no sorry these are the permissions that can't win the giveaway

**Comment by Dragonizedpizza** [comment]
ah
ty!

**Comment by Dragonizedpizza** [comment]
I tried to use the example code, got this. 
`MongoError: user is not allowed to do action [find] on [dragon-night.giveaways]`
I  gave the user dbAdminAnyDatabase so-

**Comment by Nico105** [comment]
Ahm you're sure gave write and read permission?

**Comment by Dragonizedpizza** [comment]
@Nico105 
![image](https://user-images.githubusercontent.com/70718540/106051670-c35cb000-610e-11eb-817e-3c7c34b62160.png)
I gave it more than just that

**Comment by Dragonizedpizza** [comment]
@Nico105 Have you tested it?

**Comment by Nico105** [comment]
yeah, it works totally fine

**Comment by Dragonizedpizza** [comment]
Weird. Is it worth mentioning that I replaced `mongoose.connect('mongodb://localhost/giveaways', { useFindAndModify: false });` and replaced it with `mongoose.connect(config.mongouri, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
  useFindAndModify: true
});`

**Comment by Nico105** [comment]
`mongoose.connect(config.mongouri, { useFindAndModify: false });` just use this to test for now

**Comment by Dragonizedpizza** [comment]
```(node:17928) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:17928) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Giveaway DB connected to MongoDB!
MongoDB Connected!
(node:17928) UnhandledPromiseRejectionWarning: MongoError: user is not allowed to do action [find] on [dragon-night.giveaways]

**Comment by Dragonizedpizza** [comment]
https://stackoverflow.com/questions/46649390/mongoerror-user-is-not-allowed-to-do-action
@Nico105 best I could find on the internet. Not much valid there...
Is it also worth mentioning that I'm using MongoDB version 5.11.13

**Comment by Dragonizedpizza** [comment]
@Nico105 ok nvm fixed it, tysm for all the help

**Comment by Dragonizedpizza** [comment]
nvm
`MongooseError: Operation `giveaways.insertOne()` buffering timed out after 10000ms`

**Comment by Dragonizedpizza** [comment]
oh wait no that's prolly cos im hosting on my laptop xd

**Comment by Dragonizedpizza** [comment]
useNewUrlParser: true,
  useUnifiedTopology: true,
  useFindAndModify: false,

**Comment by Dragonizedpizza** [comment]
alright so somehow DBAdmin doesn't have write permissions
