### ISSUE TITLE
Mongoose/MongoDB does not connect properly | Buffering timed out

### ISSUE THREAD

**Issue by Dragonizedpizza** [Androz2091/discord-giveaways#198]
Hi, whenever a user deletes the giveaway message, my console gets spammed. It gets spammed with Discord API errors saying unknown message. This would continue until the giveaway time has finished. Any idea how to stop this?

**Comment by Dragonizedpizza** [comment]
also, when I try to use the Mongoose.js example in the develop branch, I get this error: ```MongooseError: Operation `giveaways.insertOne()` buffering timed out after 10000ms

**Comment by Nico105** [comment]
> Hi, whenever a user deletes the giveaway message, my console gets spammed. It gets spammed with Discord API errors saying unknown message. This would continue until the giveaway time has finished. Any idea how to stop this?

`npm i Androz2091/discord-giveaways#develop` should have the fix, will get released with the next version

**Comment by Dragonizedpizza** [comment]
> also, when I try to use the Mongoose.js example in the develop branch, I get this error: MongooseError: Operation `giveaways.insertOne()` buffering timed out after 10000ms
What about this?

**Comment by Nico105** [comment]
https://github.com/Automattic/mongoose/issues/9732
Look through this

**Comment by Dragonizedpizza** [comment]
@Nico105 none worked

**Comment by Nico105** [comment]
Which line does even cause this error? Because in the example `.insertOne()` does not get used. Is the error in the code of the "mongoose" package?

**Comment by Dragonizedpizza** [comment]
I'll send both the errors.
```(node:20788) UnhandledPromiseRejectionWarning: MongooseError: Operation `giveaways.insertOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\akyra\Desktop\Bots\DragonNight\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:185:20)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20788) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```


```(node:20788) UnhandledPromiseRejectionWarning: MongooseError: Operation `giveaways.findOneAndUpdate()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\akyra\Desktop\Bots\DragonNight\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:185:20)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:20788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)```

**Comment by Dragonizedpizza** [comment]
> Which line does even cause this error? Because in the example `.insertOne()` does not get used. The error in the code of the "mongoose" package right?

@Nico105 yes I think

**Comment by Nico105** [comment]
`mongoose.connect(config.mongouri, { useFindAndModify: false });` is it still there if you use the connect method without your custom options?

**Comment by Dragonizedpizza** [comment]
@Nico105 I connect through this:
```mongoose.connect(config.mongouri, { 
  useNewUrlParser: true,
  useUnifiedTopology: true,
  useFindAndModify: false,
});```

**Comment by Nico105** [comment]
As said try it with the default (my) one

**Comment by Dragonizedpizza** [comment]
```(node:24544) UnhandledPromiseRejectionWarning: MongooseError: Operation `giveaways.insertOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\akyra\Desktop\Bots\DragonNight\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:185:20)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:24544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24544) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Dragonizedpizza** [comment]
@Nico105 same error.

**Comment by Nico105** [comment]
`.catch(error => console.error(error));` add this after `.cconnect()` and btw are you sure the IP you're connecting from is whitelisted?

**Comment by Dragonizedpizza** [comment]
I switched on allow connections from everywhere @Nico105...

**Comment by Nico105** [comment]
"was resolved by removing the node_module 
folder, *.json (=package) files and reinstalling the mongoose module."
https://www.codegrepper.com/code-examples/csharp/MongooseError%3A+Operation+%60warns.findOne%28%29%60+buffering+timed+out+after+10000ms

**Comment by Dragonizedpizza** [comment]
@Nico105 I don't have a folder ending with .json lmao

**Comment by Nico105** [comment]
No folder, the package.lock.json

**Comment by Dragonizedpizza** [comment]
the instructions aren't very clear but ok

**Comment by Nico105** [comment]
1. Delete package.lock.json
2. Delete "node_modules" folder
3. `npm i`
You could be glad I'm even trying to help because this is not a issue of `discord-giveaways` in the first place...

**Comment by Dragonizedpizza** [comment]
yes yes, I am very grateful :)

**Comment by Dragonizedpizza** [comment]
```Operation `giveaways.insertOne()` buffering timed out after 10000ms```

**Comment by Dragonizedpizza** [comment]
@Nico105 didn't work ):

**Comment by Dragonizedpizza** [comment]
> 1. Delete `package.lock.json` file
> 2. Delete `node_modules` folder
> 3. `npm i`
> 
> You could be glad I'm even trying to help because this is not a issue of `discord-giveaways` in the first place...

Also, it kinda is cos the examples in the discord-giveaways package is invalid.

**Comment by Nico105** [comment]
> > 1. Delete `package.lock.json` file
> > 2. Delete `node_modules` folder
> > 3. `npm i`
> > 
> > You could be glad I'm even trying to help because this is not a issue of `discord-giveaways` in the first place...
> 
> Also, it kinda is cos the examples in the discord-giveaways package is invalid.

Wrong, the example code is 100% valid and functioning, what is wrong here are just mongoDB/mongoose connection/network/setting issues, `discord-giveaways` is not the fault of this, the error clearly said that it was in the mongoose folder and from what i found about "buffering", what it says in your error is, that you pretty much can "use" mongoose things before you connected to the actual DB but only for a certain time => "timeout after 10000ms", because it couldn't connect even after the buffer time.
It is not the example codes fault, for enough people it just worked fine first try.
As said it has smth to do with mongoDB configuration/access/perms or smth
Don't expect that we can "magically" change smth in the example code and make it work for you.
Things just don't work the same on different PC's on different networks, on differents settings/configuration
It would't even have gotten merged into the develop branch if it wouldn't have functioned.

**Comment by Dragonizedpizza** [comment]
Uh-
Ok then-

**Comment by Dragonizedpizza** [comment]
do I still get help?

**Comment by Nico105** [comment]
If someone knows a solution and sees this, then such a person will very likely tell it to you, but because this is just a discord.js giveaway module not too many know-solution persons will see this, so you should start searching elsewhere for answers, you could maybe make a issue on the github mongoose page or find a discord server or some forum which deals with mongo errors. :)

**Comment by Nico105** [comment]
Btw what you could try is making a completely new mongoDB project/cluster with all default settings (exept allow all IPs) and connect to that one to test

**Comment by Dragonizedpizza** [comment]
alright, ty!

**Comment by MaximKing1** [comment]
Have you fixed this @Dragonizedpizza ? I have added a connection string below to try I had this error and this fixed for me.
```he
mongoose.connect(process.env.MONGO_DB, { useNewUrlParser: true, useUnifiedTopology: true, useCreateIndex: true, useFindAndModify: false }); 
```

**Comment by Dragonizedpizza** [comment]
@MaximKing1 nope.

**Comment by Dragonizedpizza** [comment]
Forgot about this.

The problem was that I was using MongoDB's free cluster, which supports only one connection at a time.
