### ISSUE TITLE
undefined value in winners

### ISSUE THREAD

**Issue by KiwiTerra** [Androz2091/discord-giveaways#199]
If you start a giveaway with more winners than participants at the end, an error occurs here because the array will fill up with an undefined value (L#329) and produce an error L#333: `TypeError: Cannot read property 'id' of undefined`. It's in Giveaway.js

**Comment by Nico105** [comment]
Line 329 to `const rolledWinners = users.random(Math.min(winnerCount || this.winnerCount, users.size));`
Will be included in the release where #187 will have been merged.

**Comment by Nico105** [comment]
🎉 v4.5.0 is now released!
