### ISSUE TITLE
Having a problem

### ISSUE THREAD

**Issue by MarijoMiksa** [Androz2091/discord-giveaways#20]
So, this is confusing to me because im not really in coding, i started like 3 weeks ago, so , i need to create `Settings.js` file and then paste Lunch example?

**Comment by Androz2091** [comment]
No, you need to create a `main.js` file, for example, then use the examples of the README.md file.

**Comment by MarijoMiksa** [comment]
Ohh okay

**Comment by MarijoMiksa** [comment]
Im having a issue with this `` giveaways.start(message.channel, {`` saying message is not ``defined``

**Comment by Androz2091** [comment]
You have to learn how to use the discord.js before using discord-giveaways. Please join this server discord if you want more basic help: https://discord.gg/8FV5Jq.
