### ISSUE TITLE
.reroll doesnt work.

### ISSUE THREAD

**Issue by jameslinimk** [Androz2091/discord-giveaways#202]
I had a giveaway with 3 reactions when it ended (Mine, the bots, and another user) and then I won. I re-rolled 15 times, and each time I rerolled the winner was me. Doing 
```js
message.client.giveawaysManager.giveaways.find(g => !g.ended && g.messageID === '805493149228728360').options
```
Returned 
```js
  options: {
    startAt: 1612114931942,
    endAt: 1612978931942,
    winnerCount: '1',
    winnerIDs: [],
    channelID: '757280403202768996',
    guildID: '712323497380020314',
    ended: false,
    prize: 'gay',
    hostedBy: '<@400029130219061260>',
    messages: {
      giveaway: '🎉🎉 **GIVEAWAY** 🎉🎉',
      giveawayEnded: '🎉🎉 **GIVEAWAY ENDED** 🎉🎉',
      inviteToParticipate: 'React with 🎉 to participate!',
      timeRemaining: 'Time remaining: **{duration}**!',
      winMessage: 'Congratulations, {winners}! You won **{prize}**!\n{messageURL}',
      embedFooter: 'Giveaways',
      noWinner: 'Giveaway cancelled, no valid participations.',
      winners: 'winner(s)',
      endedAt: 'Ended at',
      hostedBy: 'Hosted by: {user}',
      units: [Object]
    },
    reaction: '🎉',
    botsCanWin: undefined,
    exemptPermissions: undefined,
    exemptMembers: undefined,
    embedColor: '#EFDEB2',
    embedColorEnd: '#2f3136',
    extraData: undefined
  },
```
Images:
![image](https://user-images.githubusercontent.com/63650909/106393140-62a9cd80-63c3-11eb-924f-b483c108dae3.png)
![image](https://user-images.githubusercontent.com/63650909/106393148-705f5300-63c3-11eb-92d3-d0bb29d0a194.png)

Note: I edited the giveaway before stopping, it and here is my code.
```js
        message.client.giveawaysManager.edit(giveaway.messageID, {
            setEndTimestamp: Date.now() + ms(giveawayDuration),
            newWinnerCount: giveawayNumberWinners,
            newPrize: giveawayPrize,
        })
        .then(() => {
            message.channel.send('Giveaway edited.');
        })
        .catch((e) => {
            if(e.startsWith(`Giveaway with message ID ${giveaway.messageID} is already ended.`)){
                message.channel.send('This giveaway is already ended!');
            } else {
                message.channel.send('An error occured...');
            }
        });
```

**Comment by Nico105** [comment]
![image](https://user-images.githubusercontent.com/63612668/106395357-32355400-6402-11eb-954b-2de04c3305ef.png)
Worked fine for me.
Are you using the latest version of the module?
And when you create your `giveawaysManager` do you have set `exemptMembers` or `exemptPermissions` there?

**Comment by jameslinimk** [comment]
> ![image](https://user-images.githubusercontent.com/63612668/106395357-32355400-6402-11eb-954b-2de04c3305ef.png)
> Worked fine for me.
> Are you using the latest version of the module?
> And when you create your `giveawaysManager` do you have set `exemptMembers` or `exemptPermissions` there?

Damn. fuck me, exemptPermissions is there. Thanks
