### ISSUE TITLE
Edit The Giveaway Embed.

### ISSUE THREAD

**Issue by MaximKing1** [Androz2091/discord-giveaways#204]
At the moment we can only edit the text but could we maybe have a way so we can edit the whole embed as im adding it to the actual package but whens its updated it clears all of it...

**Comment by Nico105** [comment]
```
generateMainEmbed(giveaway) {
        const embed = new Discord.MessageEmbed();
        embed
            .setAuthor(giveaway.prize)
            .setColor(giveaway.embedColor)
            .setFooter(`${giveaway.winnerCount} ${giveaway.messages.winners} • ${giveaway.messages.embedFooter}`)
            .setDescription(
                giveaway.messages.inviteToParticipate +
                    '\n' +
                    giveaway.remainingTimeText +
                    '\n' +
                    (giveaway.hostedBy ? giveaway.messages.hostedBy.replace('{user}', giveaway.hostedBy) : '')
            )
            .setTimestamp(new Date(giveaway.endAt).toISOString());
        return embed;
    }
```
![image](https://user-images.githubusercontent.com/63612668/106447561-ee822f00-6481-11eb-81f1-4c3ad97b8d07.png)
If you already use a custom DB like in the ss, then you can just add the "generate..Embed" functions to the `class extends` and customize it.

**Comment by Nico105** [comment]
```js
const { GiveawaysManager } = require('discord-giveaways');
class CustomGiveawaysManager extends GiveawaysManager {
    generateMainEmbed(giveaway) {
        const embed = new Discord.MessageEmbed();
        embed
            .setAuthor(giveaway.prize)
            .setColor(giveaway.embedColor)
            .setFooter(`${giveaway.winnerCount} ${giveaway.messages.winners} • ${giveaway.messages.embedFooter}`)
            .setDescription(
                giveaway.messages.inviteToParticipate +
                    '\n' +
                    giveaway.remainingTimeText +
                    '\n' +
                    (giveaway.hostedBy ? giveaway.messages.hostedBy.replace('{user}', giveaway.hostedBy) : '')
            )
            .setTimestamp(new Date(giveaway.endAt).toISOString());
        return embed;
    }
};

const manager = new CustomGiveawaysManager(client, {
    storage: './giveaways.json',
    updateCountdownEvery: 10000,
    hasGuildMembersIntent: false,
    default: {
        botsCanWin: false,
        exemptPermissions: ['MANAGE_MESSAGES', 'ADMINISTRATOR'],
        embedColor: '#FF0000',
        reaction: '🎉'
    }
});
// We now have a giveawaysManager property to access the manager everywhere!
client.giveawaysManager = manager;
```
So like this

**Comment by MaximKing1** [comment]
Oh perfect thanks will this work with the custom DB mongoose and Sharding?

**Comment by Nico105** [comment]
Sure

**Comment by MaximKing1** [comment]
Would this work? 
`    db.once("ready", async () => {
        if ((await db.get("giveaways")) === null) await db.set("giveaways", []);
      });
      const { GiveawaysManager } = require("discord-giveaways");
      class GiveawayManagerWithOwnDatabase extends GiveawaysManager {
            generateMainEmbed(giveaway) {
        const embed = new Discord.MessageEmbed();
        embed
            .setAuthor(giveaway.prize)
            .setColor(giveaway.embedColor)
            .setFooter(`${giveaway.winnerCount} ${giveaway.messages.winners} • ${giveaway.messages.embedFooter}`)
            .setDescription(
                giveaway.messages.inviteToParticipate +
                    '\n' +
                    giveaway.remainingTimeText +
                    '\n' +
                    (giveaway.hostedBy ? giveaway.messages.hostedBy.replace('{user}', giveaway.hostedBy) : '')
            )
            .setTimestamp(new Date(giveaway.endAt).toISOString());
        return embed;
    }
        async refreshStorage() {
        // This should make all shard refreshing their cache with the updated database
        return client.shard.broadcastEval(() => this.giveawaysManager.getAllGiveaways());
        }
        async getAllGiveaways() {
            return await db.get("giveaways");
        }
        async saveGiveaway(messageID, giveawayData) {
            await db.push("giveaways", giveawayData);
            return true;
        }
        async editGiveaway(messageID, giveawayData) {
            const giveaways = await db.get("giveaways");
            const newGiveawaysArray = giveaways.filter((giveaway) => giveaway.messageID !== messageID);
            newGiveawaysArray.push(giveawayData);
            await db.set("giveaways", newGiveawaysArray);
            return true;
        }
        async deleteGiveaway(messageID) {
            const data = await db.get("giveaways");
            const newGiveawaysArray = data.filter((giveaway) => giveaway.messageID !== messageID);
            await db.set("giveaways", newGiveawaysArray);
            return true;
        }
      };

    const manager = new GiveawayManagerWithOwnDatabase(client, {
        storage: false,
        updateCountdownEvery: 10000,
        hasGuildMembersIntent: true,
        default: {
          botsCanWin: false,
          embedColor: "#002df7",
          embedColorEnd: "#FF0000",
          exemptPermissions: [ 'ADMINISTRATOR' ],
          reaction: '🎉'
    }});
    client.giveawaysManager = manager; `

**Comment by MaximKing1** [comment]
Sorry for the formatting it’s a bit strange I could not get it working..

**Comment by Nico105** [comment]
Np, it should work

**Comment by MaximKing1** [comment]
I didn’t know if I had to make seprate ones or I can just add to the Sharding or Giveawy thingy etc

**Comment by Nico105** [comment]
Nah, all fine you can add every function you find here: https://github.com/Androz2091/discord-giveaways/blob/master/src/Manager.js
into the `class extends` and customize it.

**Comment by MaximKing1** [comment]
Thanks all working with Sharding and custom db and custom embed
