### ISSUE TITLE
Giveaways stop updating

### ISSUE THREAD

**Issue by Ult1m1** [Androz2091/discord-giveaways#206]
Hi, Sometimes it happens to me that the giveaway stops updating after a while

    "discord-giveaways": "^4.4.3",

**Comment by Nico105** [comment]
"A while" is after what time?

**Comment by Ult1m1** [comment]
It stopped working for about 3 days, and sometimes it stops working for a while and sometimes after a few hours

**Comment by Nico105** [comment]
Do the giveaways still automatically end or not?

**Comment by Ult1m1** [comment]
I'm going to try the 10h test now, I'll let you know

**Comment by Ult1m1** [comment]
but so far it has stopped working on its own. There was nothing in the database either

**Comment by Ult1m1** [comment]
Now it stopped working in a few minutes

**Comment by Nico105** [comment]
> but so far it has stopped working on its own. There was nothing in the database either

So it gets removed from the DB automatically?

**Comment by Ult1m1** [comment]
Only sometimes, It's not gone now
https://prnt.sc/y8rpw0

**Comment by Nico105** [comment]
If you use vsc, could you maybe try debugging (breakpoints) the `_checkGiveaway` function inside the `Manager.js` file to find out where it stops.

**Comment by MaximKing1** [comment]
@Ult1m1 ik getting this error aswell any fixes yet? If your still facing the issue let me know...

**Comment by Nico105** [comment]
```js
const manager = new GiveawayManagerWithOwnDatabase(client, {
    default: {
    }
}, false); // Set auto initalization to false
```
Bot Ready Event
```js
client.giveawaysManager._init();
```
@Ult1m1 This seems to have fixed it for Maxim, pls try it.

**Comment by Ult1m1** [comment]
Everything is already working well

**Comment by Nico105** [comment]
Did you do smth?
