### ISSUE TITLE
undefined value in extraData...

### ISSUE THREAD

**Issue by MaximKing1** [Androz2091/discord-giveaways#209]
When using giveaway.extraData in my embed for the module it shows undefined??

`generateMainEmbed(giveaway) {
        const embed = new discord.MessageEmbed();
        embed
            .setTitle(giveaway.prize)
            .setDescription(
                    giveaway.remainingTimeText +
                    '\n' +
                    (giveaway.hostedBy ? giveaway.messages.hostedBy.replace('{user}', giveaway.hostedBy) : '') +
                    '\n' +
                    ("**Prize:** " + `${giveaway.prize}`)
            ).addField(`📣 Requirements:`, giveaway.extraData)
            .setTimestamp(new Date(giveaway.endAt).toISOString());
        return embed;
}
`

**Comment by Nico105** [comment]
Then it was not properly defined. Never experienced that error or what?
I can guarantee you it works if you do it right.
It's your job as a dev to figure out such simple things (= debugging), or at least try, before you seek for help.

```js
client.giveawaysManager.start(giveawayChannel, {
		// The giveaway duration
		time: ms(giveawayDuration),
		// The giveaway prize
		prize: giveawayPrize,
		// The giveaway winner count
		winnerCount: parseInt(giveawayNumberWinners),
		// Who hosts this giveaway
		hostedBy: client.config.hostedBy ? message.author : null,
		// Messages
		messages: {
			giveaway: (client.config.everyoneMention ? '@everyone\n\n' : '') + '🎉🎉 **GIVEAWAY** 🎉🎉',
			giveawayEnded: (client.config.everyoneMention ? '@everyone\n\n' : '') + '🎉🎉 **GIVEAWAY ENDED** 🎉🎉',
			timeRemaining: 'Time remaining: **{duration}**!',
			inviteToParticipate: 'React with 🎉 to participate!',
			winMessage: 'Congratulations, {winners}! You won **{prize}**!, {messageURL}',
			embedFooter: 'SOMETEXTHERE',
			noWinner: 'Giveaway cancelled, no valid participations.',
			hostedBy: 'Hosted by: {user}',
			winners: 'winner(s)',
			endedAt: 'Ended at',
			units: {
				seconds: 'seconds',
				minutes: 'minutes',
				hours: 'hours',
				days: 'days',
				pluralS: false, // Not needed, because units end with a S so it will automatically removed if the unit value is lower than 2
			},
		},
		extraData = 'smth'
		// or
		extraData = { req: 'smth' }
	});
```
You have it like that?

**Comment by MaximKing1** [comment]
I’m not blaming the package but I have defined the extraData and in the DB it doesn’t save either so it could be a package error... and if it was saving to the database I could at least pull it like that but I can’t! Idk why it isn’t saving but I even tried just using that in a standalone bot I’m using the same code on the Mongose Examples not quickMongo but it saved in quickMongo and it was showing in QuickMongo but when I switched to Your Mongoose Model it stopped working ...

**Comment by Nico105** [comment]
`extraData: 'smth'` wouldn't work, my bad.
`extraData: { req: 'smth' }` you have to make it a object, because its defined as a object in the mongoose schema.

**Comment by MaximKing1** [comment]
Ahh thank you sorry I’m dumb

**Comment by MaximKing1** [comment]
Also when I restart my bot this is with Sharding and using 14.5.1 Nodejs and Latest discord updated 20 mins ago it won’t see current giveaways I can confirm it sees in the database but doesn’t register the giveaway after restarted. Should I put the giveaway thing in the Sharding file and attach to the manager?

**Comment by MaximKing1** [comment]
Also that is workign thank you.. ^^

**Comment by Nico105** [comment]
> Also when I restart my bot this is with Sharding and using 14.5.1 Nodejs and Latest discord updated 20 mins ago it won’t see current giveaways I can confirm it sees in the database but doesn’t register the giveaway after restarted. Should I put the giveaway thing in the Sharding file and attach to the manager?

Nah, it has to be attached to the client.
This issue is probably the same that 2 other people currently have but unfortunately they haven't responded to my debugging suggestions.
I will let you know if I figure smth out and you can make a new issue for that if you want.

**Comment by MaximKing1** [comment]
Will do 👍
