### ISSUE TITLE
[FR] Décalage entre le temps restant et l'heure de fin

### ISSUE THREAD

**Issue by LePtitMetalleux** [Androz2091/discord-giveaways#21]
Bonjour,
Comme dit dans le titre et comme vous pourrez le voir dans le screen ci-dessous, lorsque je lance un giveaway, au bout d'un certain temps un décalage se forme entre la date affichée et la date de fin du giveaway (Présente dans le footer de l'embed). Car à en croire le screen, le giveaway doit se terminer le 25 à 00:00 or si on suit le temps restant indiqué, le giveaway se termine le 25 à 00:35.
Le temps indiqué se resynchronise lorsque je redémarre le bot mais à chaque fois un écart se creuse et c'est problématique car lors du tirage (À l'heure indiquée dans le footer), s'il y a ce problème, le bot tire des personnes à l'infini et l'embed de fin ne s'affiche pas.
Je fais remonter ce problème ici mais il se peut que le décalage soit du à du lag du bot éventuellement (mais bon 25 de ping ça devrait aller)

Merci de votre aide
Cordialement
- LePtitMetalleux

![image](https://user-images.githubusercontent.com/59097429/71355733-3dbc1780-2580-11ea-8580-75fb0f0e0dd2.png)

**Comment by Androz2091** [comment]
Bonjour,
Quel interval avez-vous entré dans la fonction `launch()` pour la mise à jour des messages ?

**Comment by LePtitMetalleux** [comment]
> Bonjour,
> Quel interval avez-vous entré dans la fonction `launch()` pour la mise à jour des messages ?

![image](https://user-images.githubusercontent.com/59097429/71359950-8549a000-258e-11ea-896a-6c06b68c35ff.png)
5 secondes (5000ms)

**Comment by Androz2091** [comment]
> 5 secondes (5000ms)
Est-ce que le fait d'incrémenter cette valeur (par exemple à 15 000 ms) règle le problème ?

**Comment by LePtitMetalleux** [comment]
> > 5 secondes (5000ms)
> 
> Est-ce que le fait d'incrémenter cette valeur (par exemple à 15 000 ms) règle le problème ? En effet cela pourrait être du a un lag du bot (surement, d'ailleurs)

Je viens de relancer le bot avec un gap de 15s (15 000ms) entre chaque update. Je vous refais signe dans 30 minutes - 1h pour voir le résultat

**Comment by LePtitMetalleux** [comment]
Bon bah ça à l'air de mieux fonctionner ^^ Merci beaucoup pour le travail que vous faites ainsi que pour votre aide !

**Comment by Androz2091** [comment]
Parfait ! Je vais mettre un message d'avertissement lorsque l'interval est inférieur à 5k.
