### ISSUE TITLE
🐛 Giveaway Freeze After Restart

### ISSUE THREAD

**Issue by MaximKing1** [Androz2091/discord-giveaways#210]
After I restart the bot it will freeze the giveaway I’m using the MongoDB example not QuickMongo I tried to play around with some of the delete after finish options didn’t work either any idea...

**Comment by MaximKing1** [comment]
I’m trying to upgrade my NodeJS version aswell to see if this fixes error also the Database is hosted locally on the server using the example exactly, Bot is using the CustomDB + ShardingManager + Custom Embed for the manager.

**Comment by MaximKing1** [comment]
Maybe an idea would to be after the ready event it Refresh's all the giveaways in the database or fetches them however you say it haha..

**Comment by MaximKing1** [comment]
I’m now on the latest LTS Version of NodeJS but still didn’t work after restart also what’s strange is that I have the manager send a message when they react it says when they reacted to the giveaway after the restart when reacting to it it don’t fire the event like the giveaway don’t exists...

**Comment by MaximKing1** [comment]
@Nico105 is there Gunna be a fix for this soon?

**Comment by Nico105** [comment]
Could you maybe try debugging the _checkGiveaway function inside the Manager.js file of the package with breakpoints to find out where it stops.
If the _checkGiveaway function does not even get called then debug the _init function in the same file.

You read my msg on the other issue right? I would not have asked if I would have been aware of it/knew why it happens.
I cannot even start coming up with a fix if I don't even know exactly why it happens.
Unfortunately I couldn't reproduce the problem myself, so someone has to give me a exact cause so I can start thinking about he fix.

**Comment by MaximKing1** [comment]
I will try and debug later Im out atm, but like I’m using Docker-Compose and on a Sharding Manager with these options could you try and reproduce with these please?

**Comment by MaximKing1** [comment]
```js
const mongoose = require("mongoose");
const discord = require("discord.js");

module.exports = async (client) => {

// Connect to database
const db = mongoose.connection;

// Check the connection
db.on('error', console.error.bind(console, 'Connection error:'));
db.once('open', () => {
    console.log('Connected to MongoDB.');
});

// Create the schema for giveaways
const giveawaySchema = new mongoose.Schema({
    messageID: String,
    channelID: String,
    guildID: String,
    startAt: Number,
    endAt: Number,
    ended: Boolean,
    winnerCount: Number,
    prize: String,
    messages: {
        giveaway: String,
        giveawayEnded: String,
        inviteToParticipate: String,
        timeRemaining: String,
        winMessage: String,
        embedFooter: String,
        noWinner: String,
        winners: String,
        endedAt: String,
        hostedBy: String,
        units: {
            seconds: String,
            minutes: String,
            hours: String,
            days: String,
            pluralS: Boolean,
        },
    },
    hostedBy: String,
    winnerIDs: [],
    reaction: String,
    botsCanWin: Boolean,
    embedColor: String,
    embedColorEnd: String,
    exemptPermissions: [],
    extraData: {}
});

// Create the model
const giveawayModel = mongoose.model('giveaways', giveawaySchema);
    
      const { GiveawaysManager } = require("discord-giveaways");
      const GiveawayManagerWithOwnDatabase = class extends GiveawaysManager { 
       async refreshStorage() {
        // This should make all shard refreshing their cache with the updated database
        return client.shard.broadcastEval(() => this.giveawaysManager.getAllGiveaways());
}
       
async getAllGiveaways() {
    return await giveawayModel.find({});
}

// This function is called when a giveaway needs to be saved in the database (when a giveaway is created or when a giveaway is edited).
async saveGiveaway(messageID, giveawayData) {
    await giveawayModel.create(giveawayData);
    return true;
}

// This function is called when a giveaway needs to be edited in the database.
async editGiveaway(messageID, giveawayData) {
    await giveawayModel
        .findOneAndUpdate({ messageID: messageID }, giveawayData)
        .exec();
    return true;
}

// This function is called when a giveaway needs to be deleted from the database.
async deleteGiveaway(messageID) {
    await giveawayModel
        .findOneAndDelete({ messageID: messageID })
        .exec();
    return true;
}
      };

    const manager = new GiveawayManagerWithOwnDatabase(client, {
        storage: false,
        updateCountdownEvery: 15000,
        hasGuildMembersIntent: true,
        endedGiveawaysLifetime: 500000,
        default: {
          botsCanWin: false,
          embedColor: "#002df7",
          embedColorEnd: "#FF0000",
          exemptPermissions: [ 'ADMINISTRATOR' ],
          reaction: '🎉'
    }});

client.giveawaysManager = manager;

manager.on('giveawayEnded', (giveaway, winners) => {
        winners.forEach((member) => {
            const embed = new discord.MessageEmbed().setTitle(`<:pin:785224364785139722> YOU WON`).setDescription(`<a:gif:785224385811185744> Congratulations, ${member.user.username}, You Won: ${giveaway.prize}`).setColor('#3EB489').setFooter("Strider Givaways", "https://striderbot.net/StriderLogo.jpeg");
            member.send(embed);
    }); 
});

manager.on('giveawayRerolled', (giveaway, winners) => {
    winners.forEach((member) => {
        const embed1 = new discord.MessageEmbed().setTitle(`<:pin:785224364785139722> YOU WON`).setDescription(`<a:gif:785224385811185744> Congratulations, ${member.user.username}, You Won: ${giveaway.prize}`).setColor('#3EB489').setFooter("Strider Givaways", "https://striderbot.net/StriderLogo.jpeg");
        member.send(embed1);
    }); 
});

manager.on('giveawayReactionAdded', (giveaway, member, reaction) => {
    const embed2 = new discord.MessageEmbed().setTitle(`ENTRY ACCEPTED <:Giveaway_Approved:800461412739710976>`).setDescription(`Your entry into [this giveaway](${giveaway.messageURL}) has been approved!`).setColor('#3EB489').setFooter("Strider Givaways", "https://striderbot.net/StriderLogo.jpeg");
    member.send(embed2);
});

manager.on('endedGiveawayReactionAdded', (giveaway, member, reaction) => {
    const embed3 = new discord.MessageEmbed().setTitle(`GIVEAWAY ENDED <a:Strider_offline:785224620751978506>`).setDescription(`Your entry to this giveaway has been denied. \n**Reason:** Already Ended`).setColor('#C40234').setFooter("Strider Givaways", "https://striderbot.net/StriderLogo.jpeg");
    member.send(embed3);
    return reaction.users.remove(member.user);
});
}; `

**Comment by MaximKing1** [comment]
@Nico105 if the above stuff works tell me and I know it’s a issue my side if not then we know what the issue is...

**Comment by Nico105** [comment]
As said other people have the problem too, one even with the most basic configuration and without sharding.
An your config works for me yeah, but that does not say anything.

**Comment by MaximKing1** [comment]
Okay I was just trying to tick every box you know if we’re gunna fix this we have to try eveything 👍 sorry I haven’t debugged yet I’ve been spending time with the family I’ll do it tonight nothink like a late code. @Nico105

**Comment by Nico105** [comment]
Yeah, np. I won't force or stress you, take your time, this is open source after all :D

**Comment by MaximKing1** [comment]
Morning,
I will take a look in a minute and debug it

**Comment by TakeFy** [comment]
Hey it’s doing the same for me it was doing perfect since 1week ago when i restart bot with over 1k guild the gaw don’t edit the time anymore and don’t roll when time is ended i’m using mysql configuration as the tutorial. So i don’t know.

**Comment by Nico105** [comment]
> Morning,
> I will take a look in a minute and debug it

Btw if it goes through the function smoothly then you can remove the `.catch(() => {})` to see if some error happens.

**Comment by TakeFy** [comment]
so i test on my dev bot it's perfectly working but as soon as it's on the main bot it's not working ...

**Comment by MaximKing1** [comment]
Yeah same here @TakeFy

**Comment by TakeFy** [comment]
So yeah we don't know what is issues  i try to clear the db same issue though

**Comment by MaximKing1** [comment]
Umm same here, I have done the different steps but nothink is working for me maybe a case of after the restart we need to add something to the ready event to fetch all giveaways etc?


Sent from Mail for Windows 10

**Comment by Nico105** [comment]
It fetches all giveaways automatically on manager initialization

**Comment by Nico105** [comment]
```js
const manager = new GiveawayManagerWithOwnDatabase(client, {
    default: {
    }
});
}, false);
```
Bot Ready Event
```js
client.giveawaysManager._init();
```
Could you maybe try this to see if a delay helps.

**Comment by TakeFy** [comment]
> ```js
> const manager = new GiveawayManagerWithOwnDatabase(client, {
>     default: {
>     }
> });
> }, false);
> ```
> 
> Bot Ready Event
> 
> ```js
> client.giveawaysManager._init();
> ```
> 
> Could you maybe try this to see if a delay helps.

where should we pub a delay ?

**Comment by Nico105** [comment]
? You add the `false` thing and put `client.giveawaysManager._init();` into your own ready event and then try it on your not-correctly-functioning bot.

**Comment by MaximKing1** [comment]
I'm gunna do that now thanks 👍

**Comment by MaximKing1** [comment]
@Nico105 umm where are you getting the extra }; from looks like there is too many? Sorry if I'm wrong...

**Comment by MaximKing1** [comment]
Oh I see sorry bout that I'm trying it now..

**Comment by Nico105** [comment]
> @Nico105 umm where are you getting the extra }; from looks like there is too many? Sorry if I'm wrong...

My bad sry

**Comment by MaximKing1** [comment]
omg thanks so much your a life savour it's all working fine now maybe need to fix the auto fetch thingy as that worked for me @TakeFy need any help feel free to ask and I'll share mine..

**Comment by Nico105** [comment]
`maybe need to fix the auto fetch thingy as that worked for me`
Hdym?

**Comment by MaximKing1** [comment]
Well when adding the thingy to the giveaway manager and ready event it worked so maybe you should get people to do that anyway... or make it have a delay or so people can set a delay?

**Comment by Nico105** [comment]
After Line 451 in `Manager.js` `console.log(this.client.readyAt)´ could you maybe add that and remove the delay temporarily?

**Comment by MaximKing1** [comment]
Okay sure thing let me get back onto my pc and do some testing!!

**Comment by MaximKing1** [comment]
Do remember when Sharding it takes longer to get ready, wait gives me an idea for a feature. Have a option called `isSharded: Boolean,` which adds a delay to the startup etc

**Comment by MaximKing1** [comment]
Okay I found another strange issue when not restarting I cannot win as I have admins perms but look after I restarted and done the test it made me win? When admins can't in the giveaway manager...
![image](https://user-images.githubusercontent.com/73140396/107144512-82954000-6933-11eb-882c-7bc9df463db8.jpeg)

**Comment by Nico105** [comment]
> Do remember when Sharding it takes longer to get ready, wait gives me an idea for a feature. Have a option called `isSharded: Boolean,` which adds a delay to the startup etc

Yeah, but some had the problem and don't shard @TakeFy do you shard?

**Comment by MaximKing1** [comment]
> > Do remember when Sharding it takes longer to get ready, wait gives me an idea for a feature. Have a option called `isSharded: Boolean,` which adds a delay to the startup etc
> 
> 
> 
> Yeah, but some had the problem and don't shard @TakeFy do you shard?
> 
> 
> 
> 

This is very strange aswell maybe if a bot has more guilds etc could be the reason or due to client options. Also @TakeFy what are your Clint options please and discord.js version

**Comment by Nico105** [comment]
> Okay I found another strange issue when not restarting I cannot win as I have admins perms but look after I restarted and done the test it made me win? When admins can't in the giveaway manager...
> ![image](https://user-images.githubusercontent.com/73140396/107144512-82954000-6933-11eb-882c-7bc9df463db8.jpeg)

Will look into that have some reason in mind.

**Comment by MaximKing1** [comment]
> > Okay I found another strange issue when not restarting I cannot win as I have admins perms but look after I restarted and done the test it made me win? When admins can't in the giveaway manager...
> 
> > ![image](https://user-images.githubusercontent.com/73140396/107144512-82954000-6933-11eb-882c-7bc9df463db8.jpeg)
> 
> 
> 
> Will look into that, I have some reason in mind.

Thanks

**Comment by Nico105** [comment]
> After Line 451 in `Manager.js` `console.log(this.client.readyAt)` could you maybe add that and remove the delay temporarily?
> Because if it is `false` then we know why nothing updates.

And also check `rawGiveaways.length`

**Comment by MaximKing1** [comment]
Give me a second and I'll do thoses both also what is your theory why after restarted the except perms don't work?

**Comment by Nico105** [comment]
I checked and it wasn't exactly what I though but that doesn't matter.
It's because of mongoose, in the schema we said `exemptPermissions: []` which means that if `exemptPermissions` of the giveaway obejct has no value then per default it will save `exemptPermissions` as an empty array in the DB. _Note: defaults can be changed_
And so after a restart the manager will pull the data from the DB.
```js
get exemptPermissions() {
        return this.options.exemptPermissions || this.manager.options.default.exemptPermissions;
    }
```
But because `this.options.exemptPermissions` is a empty array, because of mongoose schema config, `||` will accept it as valid and give returns it instead of `this.manager.options.default.exemptPermissions // ADMINISTRATOR`.
#211 has the fix included (coincidence 😆)
Or you do
```js
exemptPermissions: {
    type: [],
    default: undefined
  }
```
For now

**Comment by TakeFy** [comment]
> > Do remember when Sharding it takes longer to get ready, wait gives me an idea for a feature. Have a option called `isSharded: Boolean,` which adds a delay to the startup etc
> 
> Yeah, but some had the problem and don't shard @TakeFy do you shard?

no don't need shard for the moment and when i tryied to shard i don't know how to do it with shard support and db

**Comment by TakeFy** [comment]
> > > Do remember when Sharding it takes longer to get ready, wait gives me an idea for a feature. Have a option called `isSharded: Boolean,` which adds a delay to the startup etc
> > 
> > 
> > Yeah, but some had the problem and don't shard @TakeFy do you shard?
> 
> This is very strange aswell maybe if a bot has more guilds etc could be the reason or due to client options. Also @TakeFy what are your Client options please and discord.js version

my discord v is 12.5.1 and client option is restTimeOffSet : 0 and partial

**Comment by TakeFy** [comment]
So to fix our problem is to put delay ?

**Comment by TakeFy** [comment]
> ? You add the `false` thing and put `client.giveawaysManager._init();` into your own ready event (= that is the delay) and then try it on your not-correctly-functioning bot if possible.

i've tryied this not working for me still freezing

**Comment by Nico105** [comment]
Below Line 451 `Manager.js` `console.log(this.client.readyAt)` is it `null`?

**Comment by TakeFy** [comment]
> Below Line 451 `Manager.js` `console.log(this.client.readyAt)` is it `null`?

no and it's logging even after the bot is ready 
![image](https://user-images.githubusercontent.com/62612084/107157937-3ecc2600-6987-11eb-9660-3056127c0605.png)

**Comment by Nico105** [comment]
That's normal

**Comment by TakeFy** [comment]
> That's normal because it's inside of a `setInterval`

yeah i  know but it's not working

**Comment by Nico105** [comment]
But so I guess I can only ask you to look into the `checkGiveaway` function which is above the `init` function and see if it does not get to the `.edit` part.

**Comment by TakeFy** [comment]
> But so I guess I can only ask you to look into the `checkGiveaway` function which is above the `init` function and see if it does not get to the `.edit` part and if probably yes, then debug to see why.

how do I do though

**Comment by Nico105** [comment]
you just put some `console.log('test')` into it or you use a debugger (vscode has one built in) and breakpoints.

**Comment by TakeFy** [comment]
> you just put some `console.log('test')` into it or you use a debugger (vscode has one built in) and breakpoints.

yeah but you if i need to restart bot each time : (

**Comment by Nico105** [comment]
then if you use vscode as said you can use the built in debugger and just add breakpoints, google it if you don't know how.

**Comment by TakeFy** [comment]
![image](https://user-images.githubusercontent.com/62612084/107158335-a2efe980-6989-11eb-8c22-9165529cf5fe.png)

**Comment by TakeFy** [comment]
so it is receiving edit

**Comment by TakeFy** [comment]
but not editing

**Comment by Nico105** [comment]
` giveaway.message.edit(giveaway.messages.giveaway, { embed });`
So that `console.log` was after this? But it did not update the embed?

**Comment by TakeFy** [comment]
> ` giveaway.message.edit(giveaway.messages.giveaway, { embed });`
> So that `console.log` was after this? But it did not update the embed?

no i put it in start of function

**Comment by TakeFy** [comment]
wait i retry like you said

**Comment by Nico105** [comment]
![image](https://user-images.githubusercontent.com/63612668/107158437-30333e00-698a-11eb-9ba2-7831c1a448cf.png)
Or as said you can do this to make the process easier

**Comment by TakeFy** [comment]
ok so now it's not logging when i put it

**Comment by Nico105** [comment]
check `console.log(this.giveaways.length)` at the beggining, if it is not 0, then go through each line and find out where exactly it stops

**Comment by TakeFy** [comment]
![image](https://user-images.githubusercontent.com/62612084/107158509-f282e500-698a-11eb-9858-d9a8684120ea.png)
so it's blocking after the 3 and the lenght is logging 19

**Comment by TakeFy** [comment]
so when it's hitting _`if(!giveaway.channel)`_ it's returning ?

**Comment by Nico105** [comment]
Seems so, some other person also had that but that's weird.
pls try `console.log(giveaway.channel)` and` console.log(giveaway.channeldID)` and if possible then check if the logged channelID is really a existing channelID

**Comment by TakeFy** [comment]
![image](https://user-images.githubusercontent.com/62612084/107159495-b6eb1980-6990-11eb-952e-3a381236aa20.png)
when restarting

**Comment by TakeFy** [comment]
when i created a gaw first one is not undefiedn but then when i restart both undefind

**Comment by Nico105** [comment]
i made a typo giveaway.channel**d**ID did you copy it?

**Comment by Nico105** [comment]
`console.log(await this.client.channels.fetch(giveaway.channelID))` does this work after a restart?

**Comment by TakeFy** [comment]
> i made a typo giveaway.channel**d**ID did you copy it? this: `giveaway.channelID` is without the typo

oups yeah i reset

**Comment by TakeFy** [comment]
![image](https://user-images.githubusercontent.com/62612084/107159602-8061ce80-6991-11eb-9532-b294a0d9521f.png)
![Uploading image.png…]()

**Comment by TakeFy** [comment]
same issue

**Comment by TakeFy** [comment]
> ```js
> const manager = new GiveawayManagerWithOwnDatabase(client, {
>     default: {
>     }
> }, false); // Set auto initalization to false
> ```
> 
> Bot Ready Event
> 
> ```js
> client.giveawaysManager._init();
> ```
> 
> Could you maybe try this to see if a delay helps.

also i have this config though

**Comment by Nico105** [comment]
does "id" have a value before you restart? Should have right?
could you try and look into you mysql DB to see if it has a value there after a restart?

**Comment by Nico105** [comment]
> > ```js
> > const manager = new GiveawayManagerWithOwnDatabase(client, {
> >     default: {
> >     }
> > }, false); // Set auto initalization to false
> > ```
> > 
> > 
> > Bot Ready Event
> > ```js
> > client.giveawaysManager._init();
> > ```
> > 
> > 
> > Could you maybe try this to see if a delay helps.
> 
> also i have this config though

doesn't matter

**Comment by Nico105** [comment]
> `console.log(await this.client.channels.fetch(giveaway.channelID))` does this work after a restart?

And as said try this after a restart

**Comment by TakeFy** [comment]
![image](https://user-images.githubusercontent.com/62612084/107159857-f450a680-6992-11eb-8024-1d356bf3a940.png)
so yeah and i going to try abose

**Comment by TakeFy** [comment]
![image](https://user-images.githubusercontent.com/62612084/107159907-3e398c80-6993-11eb-8599-96dad64c9a28.png)
not found it's logical bc channelID = undefined

**Comment by Nico105** [comment]
K then remove that.
After line 448 `console.log(giveaway.channelID)`, after a restart, dies that work.

**Comment by TakeFy** [comment]
![image](https://user-images.githubusercontent.com/62612084/107160827-e2720200-6998-11eb-9af2-e40a4ffe8378.png)
logging nothing

**Comment by Nico105** [comment]
After line **448***...

**Comment by TakeFy** [comment]
it is

**Comment by TakeFy** [comment]
i know why it's my db
i'm using mariadb and mariadb = json = longtext so i need to json parse where it's fetching db

**Comment by Nico105** [comment]
I forgot you still have the console.logs thats why its not the eight line

In the init function after
`rawGiveaways.forEach((giveaway)`
this line i mean

**Comment by TakeFy** [comment]
> i know why it's my db
> i'm using mariadb and mariadb = json = longtext so i need to json parse where it's fetching db

this is issue 100% because longtext is not json

**Comment by TakeFy** [comment]
it's string so i need to json parse

**Comment by Nico105** [comment]
Ahm didn't you say you used the mysql example?

**Comment by TakeFy** [comment]
> Ahm didn't you say you use the mysql example?

i'm using but in mysql they is a json format in my localhost pc i use json format so working. But on vps it's maria db  and mariadb don't support json so i need to find where you retrieve information from db

**Comment by TakeFy** [comment]
![image](https://user-images.githubusercontent.com/62612084/107161023-1994e300-699a-11eb-958c-570c5575f388.png)
not that the issue because it's already json parsing and i try what u told me but no log

**Comment by TakeFy** [comment]
> ![image](https://user-images.githubusercontent.com/62612084/107161023-1994e300-699a-11eb-958c-570c5575f388.png)
> not that the issue because it's already json parsing and i try what u told me but no log

ok no i find it i try wait

**Comment by Nico105** [comment]
`getAllGiveaways` in your extended manager class...

**Comment by Nico105** [comment]
> > ![image](https://user-images.githubusercontent.com/62612084/107161023-1994e300-699a-11eb-958c-570c5575f388.png)
> > not that the issue because it's already json parsing and i try what u told me but no log
> 
> ok no i find it i try wait

Bro, that is if you use default `giveaway.json` file to save giveawaxs.
You have extended the class to use your custom DB...

**Comment by TakeFy** [comment]
ok update : 
I've fixed it, it was what i was thinking

**Comment by Nico105** [comment]
![Screenshot_20210207-231906_Chrome](https://user-images.githubusercontent.com/63612668/107161163-25cd7000-699b-11eb-8550-dea83af81458.jpg)
So you edited smth here right?
Everything working now?

**Comment by TakeFy** [comment]
I find the issue it was wher i'm extending the class i was not json parse the data that was the issue

**Comment by TakeFy** [comment]
> ![Screenshot_20210207-231906_Chrome](https://user-images.githubusercontent.com/63612668/107161163-25cd7000-699b-11eb-8550-dea83af81458.jpg)
> So you edited smth here right?
> Everything working now?

yep

**Comment by Nico105** [comment]
Aha, so this has to be done so that `mariaDB` works? If yes, then you can, if you want, make a pr with a `mariaDB` example.

**Comment by TakeFy** [comment]
> Aha, so this "json parse the data" has to be done so that `mariaDB` works with this package?
> If yes, then you can, if you want, make a pr with a `mariaDB` example if you really had to only change that little thing so everything works.
> Or if you don't want to, then you can give me what you changed and I will make one, if everything else works.

Yeah sure how can I do a maria db example ?

**Comment by TakeFy** [comment]
but you need to edit the default mysql exemple because it's not correct, it's bugged

**Comment by Nico105** [comment]
> but you need to edit the default mysql exemple because it's not correct, it's bugged

It's only bugged if you use `mariaDB` right? If you use normal `mysql` then it works fine right? It does for me.

**Comment by TakeFy** [comment]
line edit with this so mysql is working    ` const giveaways = res.map((row) => row.data);`

**Comment by TakeFy** [comment]
> > but you need to edit the default mysql exemple because it's not correct, it's bugged
> 
> It's only bugged if you use `mariaDB` right? If you use normal `mysql` then it works fine right? It does for me.

exactly it's bugged with maria db

**Comment by TakeFy** [comment]
but the mysql example is not working because you are trying to json parse already json type so it throwing error

**Comment by TakeFy** [comment]
so wheir i can put the maria db exemple ?

**Comment by TakeFy** [comment]
this is the code `const Discord = require('discord.js'),
    client = new Discord.Client(),
    settings = {
        prefix: 'g!',
        token: 'Your Discord Token'
    };

// Load mysql
const MySQL = require('mysql2');
const sql = MySQL.createConnection({
    host     : 'localhost',
    user     : 'Your MySQL user',
    password : 'Your MySQL password',
    database : 'Your MySQL database name'
});
sql.connect( (err) => {
    if (err){
        console.error('Impossible to connect to MySQL server. Code: ' + err.code);
        process.exit(99); // stop the process if we can't connect to MySQL server
    } else {
        console.log('[SQL] Connected to the MySQL server! Connexion ID: ' + sql.threadId);
    }
});

// Create giveaways table
sql.query(`
	CREATE TABLE IF NOT EXISTS \`giveaways\`
	(
		\`id\` INT(1) NOT NULL AUTO_INCREMENT,
		\`message_id\` VARCHAR(64) NOT NULL,
		\`data\` LONGTEXT NOT NULL,
		PRIMARY KEY (\`id\`)
	);
`, (err) => {
    if (err) console.error(err);
    console.log('[SQL] Created table `giveaways`');
});

const { GiveawaysManager } = require('discord-giveaways');
const GiveawayManagerWithOwnDatabase = class extends GiveawaysManager {

    // This function is called when the manager needs to get all the giveaway stored in the database.
    async getAllGiveaways(){
        return new Promise(function (resolve, reject) {
            sql.query('SELECT `data` FROM `giveaways`', (err, res) => {
                if (err) {
                    console.error(err);
                    return reject(err);
                }
                const giveaways = res.map((row) => JSON.parse(row.data));
                resolve(giveaways);
            });
        });
    }

    // This function is called when a giveaway needs to be saved in the database (when a giveaway is created or when a giveaway is edited).
    async saveGiveaway(messageID, giveawayData){
        return new Promise(function (resolve, reject) {
            sql.query('INSERT INTO `giveaways` (`message_id`, `data`) VALUES (?,?)', [messageID, JSON.stringify(giveawayData)], (err, res) => {
                if (err) {
                    console.error(err);
                    return reject(err);
                }
                resolve(true);
            });
        });
    }

    async editGiveaway(messageID, giveawayData){
        return new Promise(function (resolve, reject) {
            sql.query('UPDATE `giveaways` SET `data` = ? WHERE `message_id` = ?', [JSON.stringify(giveawayData), messageID], (err, res) => {
                if (err) {
                    console.error(err);
                    return reject(err);
                }
                resolve(true);
            });
        });
    }

    // This function is called when a giveaway needs to be deleted from the database.
    async deleteGiveaway(messageID){
        return new Promise(function (resolve, reject) {
            sql.query('DELETE FROM `giveaways` WHERE `message_id` = ?', messageID, (err, res) => {
                if (err) {
                    console.error(err);
                    return reject(err);
                }
                resolve(true);
            });
        });
    }
};

// Create a new instance of your new class
const manager = new GiveawayManagerWithOwnDatabase(client, {
    storage: false, // Important - use false instead of a storage path
    updateCountdownEvery: 10000,
    default: {
        botsCanWin: false,
        exemptPermissions: [ 'MANAGE_MESSAGES', 'ADMINISTRATOR' ],
        embedColor: '#FF0000',
        reaction: '🎉'
    }
});
// We now have a giveawaysManager property to access the manager everywhere!
client.giveawaysManager = manager;

client.on('ready', () => {
    console.log('I\'m ready !');
});

client.login(settings.token);`

**Comment by Nico105** [comment]
Fork this repo, change to `develop` branch and add a `mariaDB.js` file to the examples folder, put the changed code into it, then make a pr.

**Comment by TakeFy** [comment]
> Fork this repo, change to `develop` branch and add a `mariaDB.js` file to the examples folder, put the changed code into it, then make a pr.

ok

**Comment by Nico105** [comment]
but wait, wouldn'T it be better to use `https://www.npmjs.com/package/mariadb` this npm package for that?

**Comment by TakeFy** [comment]
> but wait, wouldn't it be better to use https://www.npmjs.com/package/mariadb this npm package for the mariaDB example?
> So we have a clear difference to the mysql example?

nop i use mysql2 https://github.com/Androz2091/discord-giveaways/pull/212
