### ISSUE TITLE
Error when winnerCount > participations

### ISSUE THREAD

**Issue by ghost** [Androz2091/discord-giveaways#214]
**When I host a giveaway of 2 and only 1 enters it freezes at 1 second if the time is finished and only if 1 out of a giveaway having 2 winners.. But when a new member reacts it declares both the 1st reactor and the second as the winners then gives me this error:**

**(node:17344) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined**

**Comment by Nico105** [comment]
We're aware of this and have already fixed it in the `develop` branch, you can do `npm i Androz2091/discord-giveaways#develop` to already install it if you like.
It will be included in the next release.

**Comment by Nico105** [comment]
🎉 v4.5.0 is now released!
