### ISSUE TITLE
Giveaway End's and get's deleted.

### ISSUE THREAD

**Issue by Lebyy** [Androz2091/discord-giveaways#215]
If you have an endedGiveawayLifetime configured the running Giveaways on bot restart get's deleted for some reason when they haven't even ended yet.

**Comment by Nico105** [comment]
What did you set `endedGiveawayLifeTime` to?

**Comment by Lebyy** [comment]
> What did you set `endedGiveawayLifeTime` to?

86400000 (1 Day)

**Comment by Lebyy** [comment]
I'll try implementing #214 if that fixes the problem.

**Comment by Nico105** [comment]
Ahm no it does not, how do you assume that?
Your issue and that issue/the fix to that issue are not related.

**Comment by Nico105** [comment]
Unless you want to say that your "active" giveaways just look "active" because the #214 error happens and that does not edit the embed?

**Comment by Lebyy** [comment]
> Unless you want to say that your "active" giveaways just look "active" because the #214 error happens and that does not edit the embed?

Exactly the giveaway just freezes and when I search the json file the data is not there it's just missing

**Comment by Nico105** [comment]
Sure it freezes when there is no data, but my question was if it was already frozen with data still saved because of the #214 error.
Or why did you mention #214? As said it shouldn't be related to your problem...

**Comment by Lebyy** [comment]
> Sure it freezes when there is no data, but my question was if it was already frozen with data still saved because of the #214 error.
> Or why did you mention #214? As said it shouldn't be related to your problem...

Sorry I was just goin through the issues and I thought my problem would be fixed by switching to develop branch

**Comment by Lebyy** [comment]
![image](https://user-images.githubusercontent.com/45114019/108023215-1bb90a80-7048-11eb-9f82-b89fcfc034ee.png)
Sometimes this happens aswell

**Comment by Nico105** [comment]
> ![image](https://user-images.githubusercontent.com/45114019/108023215-1bb90a80-7048-11eb-9f82-b89fcfc034ee.png)
> Sometimes this happens aswell

Did you restart between these messages or was your bot online the entire time?

**Comment by Lebyy** [comment]
> > ![image](https://user-images.githubusercontent.com/45114019/108023215-1bb90a80-7048-11eb-9f82-b89fcfc034ee.png)
> > Sometimes this happens aswell
> 
> Did you restart between these messages or was your bot online the entire time?

It was online the whole time.

**Comment by Nico105** [comment]
> If you have an endedGiveawayLifetime configured the running Giveaways on bot restart get's deleted for some reason when they haven't even ended yet.

And if you remove `endedGiveawaysLifetime` then it really does not happen?

**Comment by Nico105** [comment]
> > > ![image](https://user-images.githubusercontent.com/45114019/108023215-1bb90a80-7048-11eb-9f82-b89fcfc034ee.png)
> > > Sometimes this happens aswell
> > 
> > 
> > Did you restart between these messages or was your bot online the entire time?
> 
> It was online the whole time.

And nothing special happen in the time (with your bot)? No error, nothing? 
Because the time space is pretty unusual, when we had multiple-ending-problems versions ago, the messages got sent in seconds and not hours.

**Comment by Lebyy** [comment]
> > If you have an endedGiveawayLifetime configured the running Giveaways on bot restart get's deleted for some reason when they haven't even ended yet.
> 
> And if you remove `endedGiveawaysLifetime` then it really does not happen?

Yep

**Comment by Lebyy** [comment]
> > > > ![image](https://user-images.githubusercontent.com/45114019/108023215-1bb90a80-7048-11eb-9f82-b89fcfc034ee.png)
> > > > Sometimes this happens aswell
> > > 
> > > 
> > > Did you restart between these messages or was your bot online the entire time?
> > 
> > 
> > It was online the whole time.
> 
> And nothing special happend in that time (with your bot)? No error, nothing?
> Because the time space is pretty unusual, when we had multiple-ending-problems versions ago, the messages got sent in seconds and not hours.

Yep, no errors.

**Comment by Nico105** [comment]
Before you restart, pls you check your .json if the active giveaways really have `ended: false` and if those still get deleted.
Because `.filter((g) => g.ended && ((g.endAt + this.options.endedGiveawaysLifetime) <= Date.now()))` should normally make it impossible for `ended: false` giveaways to get deleted.
And you did not extend any other function than the embed ones in your custom class right?

**Comment by Lebyy** [comment]
> Before you restart, pls you check your .json if the active giveaways really have `ended: false` and if those still get deleted.
> Because `.filter((g) => g.ended && ((g.endAt + this.options.endedGiveawaysLifetime) <= Date.now()))` should normally make it impossible for `ended: false` giveaways to get deleted.
> And you did not extend any other function than the embed ones in your custom class right?

The data is missing it's just not present there and nope I didn't extend anything

**Comment by Nico105** [comment]
Or maybe, just maybe, do you use heroku or glitch to host your bot?

**Comment by Lebyy** [comment]
> I mean you make a **new** giveaway, check `ended: false` inside the .json and then restart and see if it really gets deleted, cause as said it shouldn't be possible unless `ended` changes to `true` somehow.
> It does delete the active ones after every restart right, or only sometimes or what? So you should just be able to test it...

Just did that and no the giveaway didn't freeze it only happens with long Giveaways I think.

**Comment by Lebyy** [comment]
> Or maybe, just maybe, do you use heroku or glitch to host your bot? But that should delete .jsons only after 1 day, so I think the answer is "no" right?

Nope I use a Ubuntu vps to host it.

**Comment by Nico105** [comment]
Did it happen only once? And was it more than 1 active giveaway? => Were it all the active giveaways?
Did they all were active in the same server/channel?

**Comment by Lebyy** [comment]
> Did it happen only once? And was it more than 1 active giveaway? => Were it all the active giveaways?
> Did they all were active in the same server/channel?

It has happened more than once and yep I had tested it on 2 different servers they all froze.

**Comment by Lebyy** [comment]
@Nico105 After implementing the fix in #214 the issue got re-solved but the strange thing is when I didn't apply any fixes it didn't show the cannot read property of Id error infact nothing.

**Comment by Nico105** [comment]
Very weird, because I couldn't find any real fix to the problem in the dev branch compared to the master branch.
I guess we just say it's fixed there, but if it happens again then we habe to check further.

**Comment by Lebyy** [comment]
@Nico105 It is still freezing and get's deleted from the db when I have removed the endedgiveawayslifetime option.

**Comment by Lebyy** [comment]
And console is clear, no errors.

**Comment by Lebyy** [comment]
Is it because I am using repl.it to host my bot?

**Comment by Nico105** [comment]
`Error: Discord Method not allowed` any path for that?

**Comment by Nico105** [comment]
You could try using https://github.com/Androz2091/discord-giveaways/blob/develop/examples/custom-databases/quickmongo.js
so that the data is not stored locally. But I did not really find any issue that repl.it would delete data.
The only other function that would delete giveaways would be when there is no message anymore, but then you would get an error.

**Comment by Nico105** [comment]
If you have `hasmembersIntent: true` and really have the intent enabled then there should be no issue.

**Comment by Lebyy** [comment]
> If you have `hasmembersIntent: true` and really have the intent enabled then there should be no issue.

Hmmm and the most suprising thing is that the giveaway automatically rolls a winner when there is no data present after the time being done

**Comment by Lebyy** [comment]
> `Error: Discord Method not allowed` any path for that?

Sorry but I couldn't get the error properly repl.it error logs suck big time

**Comment by Nico105** [comment]
> > If you have `hasmembersIntent: true` and really have the intent enabled then there should be no issue.
> 
> Hmmm and the most suprising thing is that the giveaway automatically rolls a winner when there is no data present after the time being done

This shouldn't be possible...

**Comment by Lebyy** [comment]
> > > If you have `hasmembersIntent: true` and really have the intent enabled then there should be no issue.
> > 
> > 
> > Hmmm and the most suprising thing is that the giveaway automatically rolls a winner when there is no data present after the time being done
> 
> This shouldn't be possible...

True here is the example 
![image](https://user-images.githubusercontent.com/45114019/109274632-bdefa400-7839-11eb-9c8f-d7816e4c37c3.png)
The giveaway has been picking winners itself automatically somehow

**Comment by Nico105** [comment]
But then the data still had to exist before it ended, otherwise we would talk about "magic"

**Comment by Lebyy** [comment]
> You could try using https://github.com/Androz2091/discord-giveaways/blob/develop/examples/custom-databases/quickmongo.js
> so that the data is not stored locally. But I did not really find any issue that repl.it would delete data.
> The only other function that would delete giveaways would be when there is no message anymore, but then you would get an error.

@Nico105 But how can I move the current going on giveaways here?

**Comment by Lebyy** [comment]
> But then the data still had to exist before it ended, otherwise we would talk about "magic"

Haha I think its something from repl's side

**Comment by Lebyy** [comment]
https://user-images.githubusercontent.com/45114019/109276306-dbbe0880-783b-11eb-9c6e-81f9c44baf5b.mp4

Oops I think the onreact event get's triggered twice here, dk why.

**Comment by Lebyy** [comment]
`(node:901) UnhandledPromiseRejectionWarning: Giveaway with message ID 814777773486112778 is already ended
(node:901) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id:`
Console

**Comment by Lebyy** [comment]
![image](https://user-images.githubusercontent.com/45114019/109276812-7d455a00-783c-11eb-90be-d7a9902cc290.png)
Also I think it'll be better if you could use the `db.pull()` method as quickmongo does have it

**Comment by Nico105** [comment]
The problem is that we only have the `messageID` and not the whole object, but `pull()` would only work if we would have the whole object.

**Comment by Umut-Ozkan** [comment]
What happens when we don't put the `endedGiveawayLifeTime`, what happens when we put it

**Comment by Nico105** [comment]
> What happens when we don't put the `endedGiveawayLifeTime`, what happens when we put it

if you don't set it then nothing happens
when you set it, then on startup all ended giveaways get checked and if they have been ended longer than the time you have set, then they get deleted from the DB

**Comment by Lebyy** [comment]
#235 fixed it.
