### ISSUE TITLE
embedColorEnd ne fonctionne pas

### ISSUE THREAD

**Issue by LePtitMetalleux** [Androz2091/discord-giveaways#22]
Bonsoir,
J'ai ajouté une couleur d'embed pour la fin des giveaways (#262626 = Couleur de Discord) or celle-ci ne s'applique pas, l'embed devient toujours noir à la fin des giveaways.
Est-ce un bug ou une erreur de ma part ? Je ne suis pas le seul à rencontrer ce problème, c'est d'ailleurs pour ça que je viens signaler ce problème.
Cordialement

- LePtitMetalleux

![image](https://user-images.githubusercontent.com/59097429/71485279-a3bece00-2810-11ea-87fb-907f7b93a14b.png)
![image](https://user-images.githubusercontent.com/59097429/71485354-ea142d00-2810-11ea-9012-812bd150ce8e.png)
![image](https://user-images.githubusercontent.com/59097429/71485363-f00a0e00-2810-11ea-83ae-08672b584c40.png)

**Comment by Feldup** [comment]
Effectivement, on l'a trouvé à deux. :)

**Comment by Androz2091** [comment]
Closed in 80eaf8ca7421eca0ad3cd7c2a6e88dc6d0317dfe
