### ISSUE TITLE
Bonus entries not accurate.

### ISSUE THREAD

**Issue by Lebyy** [Androz2091/discord-giveaways#221]
I dont think so bonus entries are accurate
(I have installed develop branch)

Here is my giveaway 
![image](https://user-images.githubusercontent.com/45114019/108953374-1a638f80-7691-11eb-9658-f986c9635dfa.png)
My alt has the role test and it should receive 100000 entries but still I win
![image](https://user-images.githubusercontent.com/45114019/108953471-3f580280-7691-11eb-802f-0017eb494fda.png)

My code of how I supply it.
```
bonus: new Function('member', `return (member) => member.roles.cache.some((r) => r.name === \'${entriesrolearg}\') ? ${entries} : null`),
cumulative: false
```

**Comment by Nico105** [comment]
```js
const user1 = [];
const user2 = [];
const user3 = [];
const user4 = [];
const user5 = [];

// 1000 giveaways
for (let i = 0; i < 1000; i++) {
    const users = new Array(10000).fill('user1') // 10000 entries for "user1"
    users.push('user2') // 1 entrie for "user2"
    for (let j = 0; j < 10; j++) users.push('user3') // 10 entries for "user3"
    for (let j = 0; j < 100; j++) users.push('user4') // 100 entries for "user4"
    for (let j = 0; j < 1000; j++) users.push('user5') // 1 entrie for "user5"

    const winner = Array.from({
        length: 1 // 1 winner
    }, () => users.splice(Math.floor(Math.random() * users.length), 1)[0])

    if (winner[0] === 'user1') user1.push(1);
    if (winner[0] === 'user2') user2.push(1);
    if (winner[0] === 'user3') user3.push(1);
    if (winner[0] === 'user4') user4.push(1);
    if (winner[0] === 'user5') user5.push(1);
}

console.log('"user1" won: ' + user1.length + 'times')
console.log('"user2" won: ' + user2.length + 'times')
console.log('"user3" won: ' + user3.length + 'times')
console.log('"user4" won: ' + user4.length + 'times')
console.log('"user5" won: ' + user5.length + 'times')
```
Our rolling mechanism

**Comment by Nico105** [comment]
You do provide it like this? `bonusEntries: [{}]`?
You don't use mongoose?
Have you checked your DB if the functions gets saved properly?

**Comment by Lebyy** [comment]
> You do provide it like this? `bonusEntries: [{}]`?
> You don't use mongoose?
> Have you checked your DB if the `bonus` function gets saved properly?

Yep it does

**Comment by Nico105** [comment]
I suggest you go into the `roll` function (Giveaway.js) and check `userArray.length`

**Comment by Lebyy** [comment]
> I suggest you go into the `roll` function (Giveaway.js) and check `userArray.length`

Everything is proper here?

**Comment by Nico105** [comment]
?
You should just check it so that we know if the bonus entries got accepted, if they are not then please check the `checkBonusEntries` function.

**Comment by Nico105** [comment]
Ah, I know why it does not work, you returned a function with the `new Function`
`bonus: new Function('member', `return member.roles.cache.some((r) => r.name === \'${entriesrolearg}\') ? ${entries} : null`),`
change your it to this.
_I will change it in the README too, sry_

**Comment by Lebyy** [comment]
:o Alright lmao.

**Comment by Lebyy** [comment]
> Ah, I know why it does not work, you returned a function with the `new Function`
> 
> ```js
> bonus: new Function('member', `return member.roles.cache.some((r) => r.name === \'${entriesrolearg}\') ? ${entries} : null`)
> ```
> 
> change it to this.
> _I will change it in the README too, sry_

Still I win xD

**Comment by Nico105** [comment]
could you pls check `userArray.length` in the `roll` function of the module

**Comment by Nico105** [comment]
And try `member.user.username === 'nameOfYourAlt'` instead of role

**Comment by Lebyy** [comment]
> And try `member.user.username === 'nameOfYourAlt'` instead of role

doing that worked

**Comment by Nico105** [comment]
I mean was your role name really right/does your alt really have it?

**Comment by Nico105** [comment]
If you try it with the ID? `member.roles.cache.get('roleID')`
