### ISSUE TITLE
options.winnerCount is not a positive integer, when value = 1

### ISSUE THREAD

**Issue by Lebyy** [Androz2091/discord-giveaways#222]
![image](https://user-images.githubusercontent.com/45114019/109325342-d2549080-787b-11eb-97cd-4d29c942c615.png)
Here is a screenshot of the console, I used the number `1` for number of winners

**Comment by Lebyy** [comment]
Same error with every number

**Comment by Lebyy** [comment]
#223 might fix it.

**Comment by Nico105** [comment]
ahm it seems that your provided strings instead of numbers

**Comment by Lebyy** [comment]
> ahm it seems that your provided strings instead of numbers

Nope they are numbers, it used to work before the develop update xD

**Comment by Lebyy** [comment]
> > ahm it seems that your provided strings instead of numbers
 Oh lemme check

**Comment by Nico105** [comment]
`winnerCount: parseInt()`
you have to do this

**Comment by Lebyy** [comment]
> `winnerCount: parseInt(args[1])`
> you have to do this

Yep this command is from the example btw might need to change it there aswell

**Comment by Nico105** [comment]
Yeah, that bot needs a lot of updates
