### ISSUE TITLE
Giveaways re-roll on thier own after finishing.

### ISSUE THREAD

**Issue by Lebyy** [Androz2091/discord-giveaways#226]
![Screenshot_20210301-171400](https://user-images.githubusercontent.com/45114019/109492884-a7538200-7ab1-11eb-8cba-f599ae7f3b26.jpg)
Only happens on the develop branch

**Comment by Nico105** [comment]
Did you maybe figure something out?

**Comment by Lebyy** [comment]
#235 fixed it.
