### ISSUE TITLE
Giveaway start not working

### ISSUE THREAD

**Issue by S4qib** [Androz2091/discord-giveaways#227]
Hey,
so i've been using this for my bot, but when i wanted to switch to mongo db i used the example provided for mongodb with quickmongo. however when i try to start a giveaway i get this:

```
(node:39) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:39) UnhandledPromiseRejectionWarning: options.winnerCount is not a positive integer. (val=1)
(node:39) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```
I am using the developement version for discord-giveaways as if i dont use that i just get some mongodb  buffer errors.

**Comment by Nico105** [comment]
1st error should get fixed with [new version of quickmongo, for what I know](https://github.com/DevSnowflake/quickmongo/releases new )
2nd error is because you have to pass `winnerCount` with `parseInt` = `winnerCount: parseInt(args[1])`

**Comment by S4qib** [comment]
Ok, thanks so much!
