### ISSUE TITLE
Giveaways don’t save.

### ISSUE THREAD

**Issue by SoCuul** [Androz2091/discord-giveaways#228]
When I start a giveaway, it randomly stops updating, and seems to be deleted from the db. I've tried json and SQLite.

**Comment by Nico105** [comment]
You never got a `Unable to fetch message with ID` error and you don't use `endedGiveawaysLifeTime`?

**Comment by SoCuul** [comment]
No, I don't. The giveaway just randomly stops. Note: I am using repl.it

**Comment by SoCuul** [comment]
Also the giveaway doesn't end, the giveaway message just freezes.

**Comment by Nico105** [comment]
> No, I don't. The giveaway just randomly stops. Note: I am using repl.it

Good that you say that, because some other guy has basically the same issue and also uses repl.it
Could you maybe try using the [quickmongo](https://github.com/Androz2091/discord-giveaways/blob/develop/examples/custom-databases/quickmongo.js) example with a mongoDB free cluster, so you can say if it really is because of repl.it

**Comment by Nico105** [comment]
> Also the giveaway doesn't end, the giveaway message just freezes.

if the data got deleted then that's for sure

**Comment by Nico105** [comment]
> No, I don't. The giveaway just randomly stops. Note: I am using repl.it

https://repl.it/talk/ask/Why-is-my-json-data-not-saving/45409
I guess that's it

**Comment by SoCuul** [comment]
Oh really? I've never had any problems with it before.

**Comment by SoCuul** [comment]
I do have it on always on mode though.

**Comment by Nico105** [comment]
as mentioned you can try to use https://github.com/Androz2091/discord-giveaways/tree/develop/examples/custom-databases one of the mongoDB examples so that we can be sure it's because of the local storage on repl.it

**Comment by Nico105** [comment]
or you can try to use #235

**Comment by hasib-rashid** [comment]
are you using nodemon in Repl.it? or just normal `node .`

**Comment by Nico105** [comment]
![Screenshot_20210324-132412_Chrome](https://user-images.githubusercontent.com/63612668/112309924-41b77780-8ca4-11eb-8bdc-e95c646c51d0.jpg)
He 90% just has to switch to replit db or mongoDB

**Comment by Nico105** [comment]
Closed because json does not work with replit and sqlite probably also doesn't since it's also local stored. 
Switch to mongoDB or their own replit DB in order to use this package on replit.
