### ISSUE TITLE
Eris Support

### ISSUE THREAD

**Issue by DynamoYT** [Androz2091/discord-giveaways#229]
You should add support for Eris library.

**Comment by NotMarx** [comment]
Good idea in my opinion.

**Comment by Nico105** [comment]
If you guys have time, you can test out my branch and roast my first eris usage. 😂

**Comment by NotMarx** [comment]
you will  make a version where it can work with Eris? I

**Comment by Nico105** [comment]
look at the linked pr and if you want to test: `npm i Nico105/discord-giveaways#patch-3`

**Comment by NotMarx** [comment]
Neat!! I’ll be testing it right away and I’ll give feedback about it when I have chance to do. Thanks by the way.

**Comment by NotMarx** [comment]
So far, I've tried to create some giveaways, but it won't respond/countdown isn't updating, and found out this error:
`(node:19040) UnhandledPromiseRejectionWarning: TypeError: (intermediate value)(intermediate value)(intermediate value).catch is not a function`

**Comment by Nico105** [comment]
fixed it

**Comment by NotMarx** [comment]
Just test it out again and yeah, it does work well. Thanks, @Nico105 for this! Now I can work out a whole rewrite for my bot with Eris 😄 

Keep up the work!! ❤️

**Comment by Nico105** [comment]
_See pr_
