### ISSUE TITLE
Des suggestions

### ISSUE THREAD

**Issue by Feldup** [Androz2091/discord-giveaways#23]
**Bonjour Androz :D**

_J'aurais des suggestions pour le module actuellement :_
- Ça serait possible de faire un système en plus ou pas ? Sais ta dire, une option qui permet d'envoyé un message privé au gagnant en plus que le bot l'annonce dans le salon ou le giveaway à été lancé (changeable dans le code seulement).

- Mettre des conditions pour le gagnant du giveaway , exemple si l'on dit 'la personne doit disposez tel et tel rôle" et qu'il ne possède pas le bot dit que les conditions ne sont pas rempli donc il ne gagne pas.

**Contacte moi sur discord si t'a pas compris. 😓**
Bonne soirée.

**Comment by Androz2091** [comment]
Ces deux suggestions ont été intégrées en v3.0:
* DM custom: https://cdn.statically.io/gh/Androz2091/discord-giveaways/master/docs/GiveawaysManager.html#event:end
* Condition role: https://cdn.statically.io/gh/Androz2091/discord-giveaways/master/docs/GiveawaysManager.html#start
