### ISSUE TITLE
Bot Removing Reactions Immediately

### ISSUE THREAD

**Issue by alima566** [Androz2091/discord-giveaways#230]
I just noticed an issue where when a giveaway is started and someone were to go react to enter, the bot immediately removes their reactions.

See attached video for reference.

https://user-images.githubusercontent.com/14950662/110059828-3bc41b80-7d22-11eb-89f6-ecf28260a888.mov

**Comment by Nico105** [comment]
You don't use the `giveawayReactionAdded` and accidently remove it there?
Maybe in your normal `message` event?
Because in the whole source code of the module we don't have a line that removes reactions, you can check yourself if you want.

**Comment by WideIrenaKan2** [comment]
Can I see your giveaway code?

**Comment by Nico105** [comment]
@alima566 could you send your manager config

**Comment by alima566** [comment]
Oh hi, sorry. It turns out this issue was caused by another npm package that I was using. It wasn't something wrong with this package after all.

Sorry about this inconvenience.
