### ISSUE TITLE
opportunity for abuse

### ISSUE THREAD

**Issue by Umut-Ozkan** [Androz2091/discord-giveaways#233]
Everything is here :)[](url)

https://user-images.githubusercontent.com/68606364/110248165-c1450700-7f80-11eb-8603-bf6785b12808.mp4

**Comment by Nico105** [comment]
We're aware of it and will add a warning with a solution to the README in the next release. https://github.com/Androz2091/discord-giveaways/tree/develop#-attention

**Comment by Umut-Ozkan** [comment]
ok pls add bug labels

**Comment by Galaxy-Network-Projekt** [comment]
lol

**Comment by AcrenoZ** [comment]
Hello, this got fixed for me when I added "guildID", for example (I have this is my end command)

let giveaway = this.client.giveawaysManager.giveaways.find((g) => g.messageID === giveawayID && g.guildID === message.channel.guild.id);

You can add this to your reroll, end, delete commands. Please let me know if this is a good idea or not

**Comment by Dragonizedpizza** [comment]
Nico referenced what to do

**Comment by Umut-Ozkan** [comment]
@Nico105 

If the Bot is kicked from the server, is there a feature to delete giveaways in the server?

**Comment by Nico105** [comment]
> @Nico105
> 
> If the Bot is kicked from the server, is there a feature to delete giveaways in the server?

```js
client.giveawaysManager.giveaways.filter(g => !client.guilds.cache.get(g.guildID)).forEach(g => client.giveawaysManager.deleteGiveaway(g.messageID))
```
Deletes every giveaway from the db where the bot cannot find the guild in the cache anymore (to be safe try fetching too)
But next time make a new issue for such a unrelated question pls.

**Comment by Dragonizedpizza** [comment]
```js
client.on('guildRemove', async (guild, client) => {
// nico code
}
```

**Comment by Dragonizedpizza** [comment]
I forgot if it was guildRemove or guildDelete, but that's how it should be

**Comment by Umut-Ozkan** [comment]
> > @Nico105
> > If the Bot is kicked from the server, is there a feature to delete giveaways in the server?
> 
> ```js
> client.giveawaysManager.giveaways.filter(g => !client.guilds.cache.get(g.guildID)).forEach(g => client.giveawaysManager.deleteGiveaway(g.messageID))
> ```
> 
> Deletes every giveaway from the db where the bot cannot find the guild in the cache anymore (to be safe also check if you cannot fetch it anymore)
> But next time make a new issue for such a unrelated question pls.

not worked

**Comment by Nico105** [comment]
> > > @Nico105
> > > If the Bot is kicked from the server, is there a feature to delete giveaways in the server?
> > 
> > 
> > ```js
> > client.giveawaysManager.giveaways.filter(g => !client.guilds.cache.get(g.guildID)).forEach(g => client.giveawaysManager.deleteGiveaway(g.messageID))
> > ```
> > 
> > 
> > Deletes every giveaway from the db where the bot cannot find the guild in the cache anymore (to be safe also check if you cannot fetch it anymore)
> > But next time make a new issue for such a unrelated question pls.
> 
> not worked

Instead of forEach try a for loop with await
and try debugging on your own

**Comment by Nico105** [comment]
```js
const giveaways = client.giveawaysManager.giveaways.filter(async g => !client.guilds.cache.get(g.guildID) && !(await client.guilds.fetch(g.guildID))
console.log(giveaways.length)
for (const g of giveaways) await client.giveawaysManager.deleteGiveaway(g.messageID)
```

**Comment by Umut-Ozkan** [comment]
> ```js
> const giveaways = client.giveawaysManager.giveaways.filter(async g => !client.guilds.cache.get(g.guildID) && !(await client.guilds.fetch(g.guildID))
> console.log(giveaways.length)
> for (const g of giveaways) await client.giveawaysManager.deleteGiveaway(g.messageID)
> ```

return `undefined` 
![image](https://user-images.githubusercontent.com/68606364/113016899-96b52b00-9187-11eb-814f-1147c2280153.png)

**Comment by Nico105** [comment]
> > ```js
> > const giveaways = client.giveawaysManager.giveaways.filter(async g => !client.guilds.cache.get(g.guildID) && !(await client.guilds.fetch(g.guildID))
> > console.log(giveaways.length)
> > for (const g of giveaways) await client.giveawaysManager.deleteGiveaway(g.messageID)
> > ```
> 
> return `undefined`
> ![image](https://user-images.githubusercontent.com/68606364/113016899-96b52b00-9187-11eb-814f-1147c2280153.png)
> 
> ```js
> client.on("guildDelete",async guild=>{
>  //await client.giveawaysManager.giveaways.filter(g => !client.guilds.cache.get(g.guildID)).forEach(g => client.giveawaysManager.deleteGiveaway(g.messageID))
>  const giveaways = client.giveawaysManager.giveaways.filter(async g => !client.guilds.cache.get(g.guildID) && !(await client.guilds.fetch(g.guildID)))
>  console.log(giveaways.length)
>   for (const g of giveaways) await client.giveawaysManager.deleteGiveaway(g.messageID).then(x=>console.log(x))
> })
> ```
> ```

Sure, the function is not supposed to return anything and btw the code i sent is just if you want to check all giveaways in all kicked servers
With the `guildDelete` event it is enough to do
```js
const giveaways = client.giveawaysManager.giveaways.filter(g => g.guildID === guild.id)
console.log(giveaways.length)
for (const g of giveaways) await client.giveawaysManager.deleteGiveaway(g.messageID)
```
because you already know the guild which you got kicked from

**Comment by Nico105** [comment]
since the `deleteGiveaways` function does not filter the local giveaway array anymore (some extended db's do but still), use `.delete(g.messageID, true)` instead of `.deleteGiveaway(g.messageID)` if you have the latest dev branch installed

**Comment by Nico105** [comment]
🎉 v4.5.0 is now released!

**Comment by umutfahriozkan** [comment]
can somebody delete this issuse? @Nico105 @Androz2091
