### ISSUE TITLE
Bot considering participations as invalid.

### ISSUE THREAD

**Issue by Dragonizedpizza** [Androz2091/discord-giveaways#236]
Proof: 

https://user-images.githubusercontent.com/70718540/111072874-c227ec80-84dc-11eb-8782-c3022e9aaa97.mp4

Code: https://github.com/HurricanoBot/Hurricano

I'm making an open source bot, this is not just to show you my code lol.

**Comment by Dragonizedpizza** [comment]
Also, parts to reference:

client.giveawaysManager initializer: https://github.com/HurricanoBot/Hurricano/blob/main/bot/Client.js
the giveaways handler: https://github.com/HurricanoBot/Hurricano/blob/main/bot/schemas/giveaway.js
The mongoose schema: https://github.com/HurricanoBot/Hurricano/blob/main/bot/utilities/giveaway.js

**Comment by Nico105** [comment]
You very likely have the `ADMINISTRATOR` permission in that server as it is specified in `exemptPermissions` because i downloaded your bot and it works fine.

**Comment by Dragonizedpizza** [comment]
ah yes 
im such a moron lmfao
