### ISSUE TITLE
Giveaway always getting cancelled and saying no participations.

### ISSUE THREAD

**Issue by shreypatel1** [Androz2091/discord-giveaways#238]
When the giveaway ends, it just says "Giveaway cancelled, no valid participations." even though there are participations. I have also checked and removed exemptPermissions but it still doesn't work. The video below shows what happens. I have also previously tried it with a person who has no permissions but it still says no participation.

https://user-images.githubusercontent.com/71745787/111462594-fe359a00-86f4-11eb-8362-591015f0ecca.mov

![Screenshot 2021-03-17 at 7 37 43 AM](https://user-images.githubusercontent.com/71745787/111462664-13122d80-86f5-11eb-9643-7b1468e9fac6.png)

**Comment by Nico105** [comment]
For custom reactions you only have to provide the ID (the numbers) of the reaction, so you just have to do `reaction: 76896...`, that's why it doesn't recognize any users

**Comment by shreypatel1** [comment]
Oh ok. That works. I ran it again after changing the value to the emoji's ID and it successfully chose a winner. I didn't think about that at first because I thought that they were not relatable. Thank you for the help.
