### ISSUE TITLE
Error: cannot read property 'forEach' of undefined.

### ISSUE THREAD

**Issue by FC5570** [Androz2091/discord-giveaways#239]
Hello, im getting an error from this package, (/src/Manager.js:448), heres the error: 
![unknown](https://user-images.githubusercontent.com/68158483/111650501-5ec6f300-882b-11eb-90d4-940eb1f58fd6.png)

If you need any more info, please mention me. Thanks.

**Comment by Nico105** [comment]
@FC5570 which DB are you using?

**Comment by Dragonizedpizza** [comment]
@FC5570 hello comrade
Could you show us your code, along with which DB you're using, as Nico said?

**Comment by FC5570** [comment]
I use quickmongo (https://npmjs.com/package/quickmongo), something like quick.db but stores data to mongodb.

Also, after taking a look at the code of this package, it looks like this error occured because I don't have a getAllGiveaways() function.

**Comment by Nico105** [comment]
https://github.com/Androz2091/discord-giveaways/blob/develop/examples/custom-databases/quickmongo.js
Add it like that and take note to add the line 70 part

**Comment by FC5570** [comment]
Alright, I'll try that, thanks

**Comment by FC5570** [comment]
I still get an error, this is a weird one, it says it cant read property 'fetch' of undefined in `getAllGiveaways()` function, 
this is my code: https://sourceb.in/B7oXNRt1Eq,
the error is from the line where I return the fetched giveaways in `getAllGiveaways()` function, line 3 in the above code

**Comment by Dragonizedpizza** [comment]
@FC5570 could you show us your database initialization?

**Comment by FC5570** [comment]
> @FC5570 could you show us your database initialization?

`const { Database } = require("quickmongo");
this.db = new Database('uri');
    this.db.on('ready', async () => {
      if (!Array.isArray(await this.db.get('giveaways'))) await this.db.set('giveaways', []);
      this.giveawaysManager._init();
  });
`

**Comment by Nico105** [comment]
Could you try moving the class extends and db creation (assign to const) outside of your client extending, so like this https://github.com/Androz2091/discord-giveaways/issues/190

**Comment by FC5570** [comment]
Yea that worked, thanks
