### ISSUE TITLE
Winners designated on bot restart

### ISSUE THREAD

**Issue by RunyardHartley** [Androz2091/discord-giveaways#24]
After restarting the bot, the giveaway designates a new winner while I have nothing to ask. There is a problem in the module.

**Comment by Androz2091** [comment]
@RunyardHartley Can you give more informations about this problem? For example, does it only designate winners, or the giveaway ends completely?

**Comment by RunyardHartley** [comment]
En faite, le giveaway est complètement terminé et a déjà désigné un gagnant. Mais le Problème c'est dès qu'on re démarre ça re sélectionne un gagnant. Je suis obligé d'enlever toutes les réactions a chaque fois pour ça ne désigne plus.  Tu peux simplement faire un système qui enlève toutes les réactions du giveaway dès que c'est la fin et que la gagnant a déjà été désigné comme ça c'est réglé

**Comment by Androz2091** [comment]
Est-ce que cela se produit en boucle (à chaque fois que tu redémarres le bot, ça tire de nouveaux gagnants pour un même giveaway) ?

**Comment by RunyardHartley** [comment]
Oui

**Comment by RunyardHartley** [comment]
Ne te casse pas la tête tu peux juste faire un clearAllReactions et c'est réglé

**Comment by Androz2091** [comment]
Désolé de t'embêter mais je préfère régler ça proprement.

En attendant, tu peux régler le problème comme ça:
```js
client.giveawaysManager.on('end', (giveaway) => {
    giveaway.message.clearReactions();
});
```

Est-il possible que tu reproduises le bug (donc que tu aies un giveaway qui désigne de nouveaux winners à chaque restart) et de m'envoyer ton fichier giveaways.json s'il te plait ?

**Comment by RunyardHartley** [comment]
Dacc merci, et je vais voir pour t'envoyer le fichier json :)

**Comment by Androz2091** [comment]
@RunyardHartley des nouvelles ? 😅

**Comment by RunyardHartley** [comment]
Re! Le bug ne se reproduit plus depuis bien quelques semaines!

**Comment by RunyardHartley** [comment]
Mais il y a des problèmes de compteur qui bug parfois

**Comment by Androz2091** [comment]
Des problèmes de compteur ?

**Comment by RunyardHartley** [comment]
Oui, après redémarrage, des fois le compteur ne reprend et reste bloqué, j'ai eu plusieurs signalements avec mon bot

**Comment by Androz2091** [comment]
> ne reprend et reste bloqué

Donc le giveaway ne se termine jamais?

**Comment by RunyardHartley** [comment]
Tout à fait !

**Comment by RunyardHartley** [comment]
Vas-tu faire une autre version de stockage ? Car avec JSON c'est vraiment pas top

**Comment by RunyardHartley** [comment]
Tu as better-sqlite3 si tu veux qui est simple d'utilisation

**Comment by Androz2091** [comment]
Tu as pu debugger un peu le bug ? En regardant par exemple dans le fichier json les informations concernant le giveaway dont le compteur est figé ?



> Vas-tu faire une autre version de stockage ? Car avec JSON c'est vraiment pas top

Hmm... c'est parce que le json est simple et ne demande pas de grosse installation, justement tout ce qui est `better-sqlite3`, donc `quick.db` par exemple c'est assez lourd. Et je ne veux pas demander aux utilisateurs d'installer une plus grosse bdd comme MongoDB ou PostgreSQL

**Comment by RunyardHartley** [comment]
Ouais en effet, mais ça serait bien de faire une autre pour les plus gros bots ? D'instaurer better-sqlite3 qui d'ailleurs ne require qu'une installation et un fichier .sqlite. Car ton projet c'est vraiment du lourd faut qu'il va plus loin

**Comment by RunyardHartley** [comment]
Et le problème avec JSON certe oui c'est très simple, mais il peut tout vider à tout moment... Il est habitué à lire que d'écrire ce qui est dommage

**Comment by Androz2091** [comment]
Une autre issue (#32) a été ouverte pour cette fonctionnalité, donc je ferme cette issue qui concernait à la base un bug.
