### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by soudblox** [Androz2091/discord-giveaways#240]
I have the giveawayEnded event, but when a giveaway is ended, it sends the default ended message and the custom one, how can I prevent this?
![image](https://user-images.githubusercontent.com/73058244/111767037-d141dc80-88d8-11eb-9886-b14a515a22f5.png)

**Comment by Nico105** [comment]
https://discord-giveaways.js.org/global.html#GiveawayMessages
You just add/edit the `winMessage` property of the giveaway object

**Comment by soudblox** [comment]
> https://discord-giveaways.js.org/global.html#GiveawayMessages
> You just add/edit the `winMessage` property of the giveaway object, instead of sending it with the event

Thanks, what options can i use other than {winners} and {prize}?

**Comment by Nico105** [comment]
`{messageURL}` so that you get a link like in your ss

**Comment by soudblox** [comment]
is there a way to get host id?

**Comment by Nico105** [comment]
You can just set that in your `winMessage: `Giveaway hosted by ${message.author}``

**Comment by soudblox** [comment]
Thanks!
