### ISSUE TITLE
Footer can't be changed with embedFooter: " ",

### ISSUE THREAD

**Issue by ArchVision** [Androz2091/discord-giveaways#245]
const ms = require("ms");
const Discord = require("discord.js");
const config = require("../config.json")

module.exports.run = (client, message, args) => {
    if(!message.member.hasPermission("MANAGE_MESSAGES")){
        return message.channel.send("You don't have permission")
    }

    let channel = message.mentions.channels.first();
    if(!channel){
        return message.channel.send("Please mention the channel")
    }
    let giveawayDuration = args[1];

    if (!giveawayDuration || isNaN(ms(giveawayDuration))){
        return message.channel.send("Specify giveaway duration!")
    }

    let giveawayWinners = args[2];

    if(isNaN(giveawayWinners) || (parseInt(giveawayWinners) <= 0)) {
        return message.channel.send("Please specify number of winers")
    }

    let giveawayPrize = args.slice(3).join(" ");

    if(!giveawayPrize){
        return message.channel.send("Please specify reward")
    }
    

    client.giveawaysManager.start(channel, {
        time: ms(giveawayDuration),
        prize: giveawayPrize,
        winnerCount: giveawayWinners,
        hostedBy: true ? message.author : null,
        

        messages: {
            giveaway: (config.everyoneMention ? "@everyone" : "") + "GIVEAWAY",
            giveawayEnded: (config.everyoneMention ? "@everyone" : "") + "Giveaway ended!",
            timeRemaining: "Remaining time: **{duration}**",
            inviteToParticipate: "React with 🎉 to participate",
            winMessage: "GG {winners}, you got **{prize}**",
            embedFooter: " Giveaway time! ", //Doesnt change the footer text, look at the picture.
            noWinner: "No Winners",
            winners: "Winner(s)",
            ededAt: "Ended at",
            units: {
                seconds: "seconds",
                minutes: "minutes",
                hours: "hours",
                pluralS: false
            } 
        }
    })

    message.channel.send('Giveaway started')
}

module.exports.help = {
    name: "gstart",
    aliases: ["gstart"]
}
![Capture](https://user-images.githubusercontent.com/77930942/111911396-d23f4f00-8a3b-11eb-904f-278f3b8f3090.PNG)

**Comment by Nico105** [comment]
Ahm, sure it does not work if you have `**_embedFooter:`...
 it just needs to be `embedFooter:

**Comment by ArchVision** [comment]
No, I was just emphasizing its there. I had it as embedFooter: "",

**Comment by Nico105** [comment]
You didn't change the package code somehow/where, did you?
![image](https://user-images.githubusercontent.com/63612668/111912684-0120e980-8a6b-11eb-9a1b-eb9dfb15f1ea.png)
I suggest you log the value of `options.messages.embedFooter` at the beggining of the start function in the Manager.js file of the module

**Comment by ArchVision** [comment]
No, I'm guessing there is no way of changing it because I am on repl.it, but how would I change it if I was on visual studio?

**Comment by Nico105** [comment]
Question, do you use .json storage fir giveaways on repl.it and restarted your bot during your test giveaway?

**Comment by ArchVision** [comment]
I used giveaways.json and no when the bot was running the tests, I did not restart it.

**Comment by Nico105** [comment]
What is the value of embedFooter inside of the .json?

**Comment by ArchVision** [comment]
"embedFooter":"Powered by the discord-giveaways package"

**Comment by Nico105** [comment]
Weird, this can only mean that it thinks that embedFooter is undefined or null because you could change the other message properties after all. But i tested it with the exact same string and it worked for me...
I mean you did add embedFooter to your code before you started your bot right?

**Comment by ArchVision** [comment]
Yes I did.

**Comment by Nico105** [comment]
I guess "I suggest you log the value of options.messages.embedFooter at the beggining of the start function in the Manager.js file of the module" in vscode then if your are able to, because I can't see anything wrong

**Comment by ArchVision** [comment]
So, I guess you cant change it on Replt only on VS?

**Comment by Nico105** [comment]
If you don't have a `node_modules` folder when you open your project in vsc then you just have to do `npm i` and in that folder is the package code

**Comment by ArchVision** [comment]
No I have one in VS, so in the package code I can change that okay thanks.

**Comment by Nico105** [comment]
Bro, I didn't said that that is the fix for the problem, I only said you should try logging the value to see if it changes/why it does not get accepted

**Comment by ArchVision** [comment]
I said I im going to try it in VS, this issue is from repl

**Comment by Nico105** [comment]
yeah, but it could theoretically also happen in vsc, it does not 100% have to be repl.it's fault, so until you proof something/find the exact issue, you should leave this issue open

**Comment by ArchVision** [comment]
Alright, ill see in vs right now ill reply to see if it works.

**Comment by ArchVision** [comment]
My NPM isnt even working I cant download anything.

**Comment by Nico105** [comment]
try reinstalling node.js i guess

**Comment by ArchVision** [comment]
So I just uninstall it and then reinstall?

**Comment by Nico105** [comment]
yeah

**Comment by ArchVision** [comment]
Alright I have everything set-up, now how do I change the footer?

**Comment by Nico105** [comment]
`node_modules/discord-giveaways/src/Manager.js` at the beginning of the  `start function`, log `options.messages.embedFooter`

**Comment by Nico105** [comment]
`node_modules/discord-giveaways/src/Manager.js` at the beginning of the  `start function`, log `options.messages.embedFooter`

**Comment by ArchVision** [comment]
So where every const is, ill put options.messages.embedFooter: "Example"

**Comment by Nico105** [comment]
you should just log it so that we can figure out why it does not work for you...

**Comment by ArchVision** [comment]
ReferenceError: options is not defined I put options.messages.embedFooter, "Example" ReferenceError: options is not defined

**Comment by Dragonizedpizza** [comment]
bruh moment

**Comment by Nico105** [comment]
BRO, YOU SHOULD JUST LOG IT = `console.log(options.messages.embedFooter)`

**Comment by ArchVision** [comment]
I CANT FIND IT LOL

**Comment by Dragonizedpizza** [comment]
_nico has left the chat_

**Comment by ArchVision** [comment]
IM SORRY IDK MAN

**Comment by Nico105** [comment]
![image](https://user-images.githubusercontent.com/63612668/111919690-9338ea00-8a8b-11eb-89f2-d6f0fcb391ea.png)

**Comment by Dragonizedpizza** [comment]
![image](https://user-images.githubusercontent.com/70718540/111919796-0c384180-8a8c-11eb-897f-b4cf1a173fe8.png)
just realized I have the old discord-giveaways, feeling good

**Comment by Nico105** [comment]
nah, my ss is just from the dev branch

**Comment by ArchVision** [comment]
Okay, it works, I guess just not on repl you cant change it

**Comment by Dragonizedpizza** [comment]
> nah, my ss is just from the dev branch

damn
is dev branch stable enough

**Comment by Dragonizedpizza** [comment]
> Okay, it works, I guess just not on repl you cant change it

that is just not possible is it

**Comment by ArchVision** [comment]
I wish there was a way lmao

**Comment by Dragonizedpizza** [comment]
also nico can I add you on Discord :D

**Comment by Dragonizedpizza** [comment]
> I wish there was a way lmao

there... is though...

**Comment by ArchVision** [comment]
Yeah sure. JakeFromStateFarm#9999 Hurry

**Comment by ArchVision** [comment]
> > I wish there was a way lmao
> 
> there... is though...

tell me

**Comment by Dragonizedpizza** [comment]
nico's notifications go brrr

**Comment by Dragonizedpizza** [comment]
> > > I wish there was a way lmao
> > 
> > 
> > there... is though...
> 
> tell me

its just the default way of doing it, you screwed something up in repl...

**Comment by ArchVision** [comment]
Tell me how I can open node_modules on repl

**Comment by ArchVision** [comment]
> > > > I wish there was a way lmao
> > > 
> > > 
> > > there... is though...
> > 
> > 
> > tell me
> 
> its just the default way of doing it, you screwed something up in repl...

No, there never was one

**Comment by Dragonizedpizza** [comment]
wtf @Nico105 is this true

**Comment by Dragonizedpizza** [comment]
> Tell me how I can open node_modules on repl

you just logged it there, how does that matter in the entire output

**Comment by Dragonizedpizza** [comment]
also nico's notifications go brrr

**Comment by Dragonizedpizza** [comment]
did I just post it again LMAO

**Comment by Dragonizedpizza** [comment]
> > nah, my ss is just from the dev branch
> 
> damn
> is dev branch stable enough

Nico just to make your work easier, just answer these

**Comment by Dragonizedpizza** [comment]
> also nico can I add you on Discord :D

.

**Comment by Dragonizedpizza** [comment]
> wtf @Nico105 is this true

and this

**Comment by ArchVision** [comment]
Im closing this everything works.  REPL doesnt show node_modules, thanks for the help Nico.

**Comment by Dragonizedpizza** [comment]
@Nico105 can I please add you on Discord

**Comment by Nico105** [comment]
dev is stable

Nico105#0005 (you just can join the support discord btw, https://discord.gg/J4hDbDEQpr, i noticed we should include that in the readme)

and the package should normally work no matter the host when the bot does not get restarted (because then the giveaway data would be from the db which could be invalid), but in this case it was in the same session so it really does not make sense to me why it does not work there, though i asked some person on dc who uses replit too if it works for him or not (waiting for response)

**Comment by Dragonizedpizza** [comment]
> Nico105#5

uh.
you have a 1 number tag?
![image](https://user-images.githubusercontent.com/70718540/111920351-badd8180-8a8e-11eb-9e5e-c19810df49b3.png)

**Comment by Nico105** [comment]
yeet, #0005

**Comment by Nico105** [comment]
> dev is stable
> 
> Nico105#5 (you just can join the support discord btw, https://discord.gg/J4hDbDEQpr, i noticed we should include that in the readme)
> 
> and the package should normally work no matter the host when the bot does not get restarted (because then the giveaway data would be from the db which could be invalid), but in this case it was in the same session so it really does not make sense to me why it does not work there, though i asked some person on dc who uses replit too if it works for him or not (waiting for response)/ but I already had tested it myself on replit and it worked for me, so idk...

the guy i asked also said it works for him, so i really don't know what's the issue with replit for you

**Comment by Dragonizedpizza** [comment]
![image](https://user-images.githubusercontent.com/70718540/111920776-304a5180-8a91-11eb-92a7-587e66767c43.png)

**Comment by Dragonizedpizza** [comment]
:mmLol:

**Comment by WideIrenaKan2** [comment]
> No, I'm guessing there is no way of changing it because I am on repl.it, but how would I change it if I was on visual studio?

Im on repl.it and the embedFooter feature works fine. Idk what is wrong with yours though.

**Comment by WideIrenaKan2** [comment]
Can you try reinstall discord-giveaways on repl.it? Maybe it's outdated lmao idk.

**Comment by Dragonizedpizza** [comment]
why did I get a notification here

**Comment by Dragonizedpizza** [comment]
![image](https://user-images.githubusercontent.com/70718540/114231940-6c2f5300-997b-11eb-9575-86b23c9a11c8.png)
?

**Comment by Nico105** [comment]
someone replied to your msg but deleted the msg cause he didn't saw that the issue was already closed
