### ISSUE TITLE
Could not determine Winner

### ISSUE THREAD

**Issue by hasib-rashid** [Androz2091/discord-giveaways#246]
Whenever a a giveaway ends if comes with a message, `Could not determine a winner`. Is it any bug or am I doing something wrong?

**Comment by Nico105** [comment]
It's probably because of `exemptPermissions` or because you pass your (if you use it) custom emoji wrong.

**Comment by hasib-rashid** [comment]
### Here is the Code of the Command Handling Giveaway File
![Here is the Code of the Command Handling Giveaway File](https://user-images.githubusercontent.com/69360193/112354607-0eea9f00-8cf7-11eb-84be-666e1cfc7822.png)

### Here is the main bot.js file
![Here is the main bot.js file](https://user-images.githubusercontent.com/69360193/112354754-317cb800-8cf7-11eb-93be-fad8ee769a24.png)

**Comment by hasib-rashid** [comment]
I dont think there is something wrong here

**Comment by Nico105** [comment]
![image](https://user-images.githubusercontent.com/63612668/112358531-b99b9700-8cd0-11eb-993c-48e4c7432dd0.png)
As mentioned.
`exemptPermissions` will prevent any user from winning who has any of the permissions in the array, so just adjust it.

**Comment by hasib-rashid** [comment]
Oh ok I will try it

**Comment by hasib-rashid** [comment]
Thank you dude. It worked! Keep on the project!
