### ISSUE TITLE
[Bug] Too large winner count.

### ISSUE THREAD

**Issue by Dragonizedpizza** [Androz2091/discord-giveaways#247]
![image](https://user-images.githubusercontent.com/70718540/112606888-db079a80-8e18-11eb-9bd6-2cbfae080e86.png)
If there's a giveaway with a larger winner count then the number of people who participated, I get that error.

**Comment by Nico105** [comment]
We're aware of this and have already fixed it in the develop branch, you can do `npm i Androz2091/discord-giveaways#develop` to already install it if you like.
It will be included in the next release.

**Comment by Dragonizedpizza** [comment]
how do you guys know of every bug ;-;
