### ISSUE TITLE
The manager is not ready yet.

### ISSUE THREAD

**Issue by Dragonizedpizza** [Androz2091/discord-giveaways#251]
```js
const { MessageEmbed } = require('discord.js');

module.exports = {
    name: "messageUpdate",
    run: async (oldMessage, newMessage, client) => {

  if (newMessage.webhookID) return;
  if (
    newMessage.member && 
    newMessage.id === newMessage.member.lastMessageID &&
    !oldMessage.command
  ) {
    client.emit('message', newMessage);
  }
}
}```
if I edit a message and trigger this event and try to host a giveaway, why do I get that error?

**Comment by Nico105** [comment]
Ahm does it really only happen after you edited some message?
Because if the manager is not ready then it is because he still checks giveaways/the provided client is invalid/the giveaway.json file does not contain an array

**Comment by Dragonizedpizza** [comment]
{
  "stack": "TypeError: guild.member is not a function
    at Giveaway.checkWinnerEntry (/home/container/node_modules/discord-giveaways/src/Giveaway.js:302:30)
    at Giveaway.roll (/home/container/node_modules/discord-giveaways/src/Giveaway.js:333:45)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/container/node_modules/discord-giveaways/src/Giveaway.js:400:29"
}
Just started using master branch of discord.js, I see the problem

**Comment by Nico105** [comment]
Yeah they removed the getter in master, I will adjust it when I have time

**Comment by Dragonizedpizza** [comment]
@Nico105 the fix is pretty simple, just guild.members.cache.get(user.id)

**Comment by Dragonizedpizza** [comment]
_could you like tell me when you adjust it though so I can reinstall discord-giveaways_

**Comment by Dragonizedpizza** [comment]
_yeah nvm just changed it myself kekw_
