### ISSUE TITLE
Giveaway Bot removing reactions

### ISSUE THREAD

**Issue by mkgamingx** [Androz2091/discord-giveaways#256]
It removes reactions after it starts but then after some time they work as normal. Eg after 1 minute they work

**Comment by Dragonizedpizza** [comment]
are you using custom reaction emoji

**Comment by mkgamingx** [comment]
> are you using custom reaction emoji

yes

**Comment by mkgamingx** [comment]
but this problem only happened now, for like 3-4 months its been good

**Comment by mkgamingx** [comment]
i didnt touch code

**Comment by Dragonizedpizza** [comment]
could you show your giveawayManager initialization, with custom emoji?

**Comment by Nico105** [comment]
he does it right, it's just the same problem as #230

**Comment by Dragonizedpizza** [comment]
ok

**Comment by Dragonizedpizza** [comment]
it could happen though, I don't think they're removing reactions in the giveawayReactionAdded part.

my bot automatically removed giveaway reactions if I put the entire custom reaction, like <:foo:12345>

**Comment by Nico105** [comment]
most who did that just got "no valid participation" on giveaway end, but no auto removing of reactions 🤷‍♂️
and for the protocol
```js
client.giveawaysManager = new GiveawaysManager(client, {
    storage: "./giveaways.json",
    updateCountdownEvery: 5000,
    default: {
        botsCanWin: false,
        embedColor: "#fdcbcd",
        embedColorEnd: "#ff999d",
        reaction: "800350154853974016",
    }
});
```
this is mkgamingx config

**Comment by mkgamingx** [comment]
i think its a problem with discord cuz i used another bot and another npm and both have the same problem 🤷‍♂️

**Comment by Nico105** [comment]
@mkgamingx are you using `WOKCommands` ?

**Comment by mkgamingx** [comment]
> @mkgamingx are you using `WOKCommands` ?

ye

**Comment by Frostysy** [comment]
If you use wok commands you need to remove it from index.js

**Comment by Nico105** [comment]
it seems whyever, that `WOKCommands` is removing the reactions, idk why.
I tried to look in their source code but it doesn't openly appear to me where it happens.

**Comment by Nico105** [comment]
@mkgamingx are you using 1.3.5 of wokcommands? if not could you try to use that version cause I searched and maybe they fixed it there,

**Comment by mkgamingx** [comment]
> @mkgamingx are you using 1.3.5 of wokcommands? if not could you try to use that version cause I searched and maybe they fixed it there,

ok thanks

**Comment by Nico105** [comment]
pls report back if it got fixed

**Comment by mkgamingx** [comment]
ye it did

**Comment by Nico105** [comment]
alright, thank you
