### ISSUE TITLE
Giveaway embed color bug on bot restart

### ISSUE THREAD

**Issue by Feldup** [Androz2091/discord-giveaways#26]
Bonsoir ou bonjour !

Je pense que j'ai trouvé un bug avec l'embed start elle change tout le temps de couleur, j'ai juste relancé le bot pendant qu'un giveaway était lancé ^^

[Lien vers la vidéo](https://cdn.discordapp.com/attachments/563999519751012363/668508602394476567/2020-01-19_18-34-07.mp4)

**Comment by Huskydog9988** [comment]
The way I can see this happening via reading the code is that it is a client-side bug or somehow the bot is setting the wrong color when editing the embed. The bot does update the embed rather quickly so the latter theory is more plausible, but I have to question how it got the wrong color variable, but then later got the correct one.
