### ISSUE TITLE
Custom Embeds

### ISSUE THREAD

**Issue by Dragonizedpizza** [Androz2091/discord-giveaways#261]
What if I wanted to make the embed format different? What if I wanted to make the prize a field, and the title a footer?

**Comment by Nico105** [comment]
https://github.com/Androz2091/discord-giveaways/issues/204#issuecomment-770760259

**Comment by Dragonizedpizza** [comment]
this.me.brains === null

**Comment by Dragonizedpizza** [comment]
shouldve' searched up myself
