### ISSUE TITLE
Giveaway stops when the number of members that join or less than the specified amount of winners

### ISSUE THREAD

**Issue by jettofHosts** [Androz2091/discord-giveaways#266]
For example: .gstart `channel` `time` `winner count` `prize`

If the **winner count** is **5** and only 4 join. The giveaway doesn't decide a winner but throws an error. 
This problem is solved in [this npm package](https://www.npmjs.com/package/reconlx) under the **giveaway section**. Probably the owner of this package can incorporate some of its code to fix this issue

**Comment by Nico105** [comment]
We're aware of this and have already fixed it in the `develop` branch, you can do `npm i Androz2091/discord-giveaways#develop` to already install it if you like.
It will be included in the next release.

**Comment by Nico105** [comment]
🎉 v4.5.0 is now released!
