### ISSUE TITLE
GiveawaysManager.delete() doesn't work if giveaway message is deleted

### ISSUE THREAD

**Issue by RunyardHartley** [Androz2091/discord-giveaways#27]
Bonsoir, 

Je sais pas si c'est un bug mais je préfère le dire, en faite, quand on veut delete un giveaway de la base de données avec une commande mais que le message du giveaway lui-même a été supprimé bas ça ne veut pas alors que j'ai bien l'id. 

C'est la fonction client.giveawaysManager.delete du coup ça serait possible de faire si le message giveaway n'est pas > je supprime quand même en base de données

**Comment by Androz2091** [comment]
Fixed!
