### ISSUE TITLE
Update countdown based on remaining giveaway duration

### ISSUE THREAD

**Issue by emino07** [Androz2091/discord-giveaways#272]
**Is your feature request related to a problem? Please describe.**  

Setting updateCountdownEvery to a high amount causes some problems and delays, lowering it is a waste of resources and may cause rate limits if too many giveaways are running in the same channel.

**Describe the solution you'd like**

Update cooldowns should be based on the giveaway duration, e.g. if the giveaway is 2 days long then it should be only updated once every few hours, not every 10 seconds for example. and if its only an hour long then it should be updated after 30 minutes, 20 minutes, 10 minutes, 5, and so on...

**Describe alternatives you've considered**  

Probably a function that checks and saves when the giveaway was last updated and does some math.

**Comment by Nico105** [comment]
`npm i Nico105/discord-giveaways#patch-1`
I tried to implement it and it works mostly I think.
But I am not to sure if it's the right approach since I used recursive setTimeout's basically and idk how that would go out with many gaws running.
and I'm not sure if that system does have flaws

btw can you specify what those problems are that you mentioned?

**Comment by emino07** [comment]
> `npm i Nico105/discord-giveaways#patch-1`
> I tried to implement it and it works mostly I think.
> But I am not to sure if it's the right approach since I used recursive setTimeout's basically and idk how that would go out with many gaws running.
> and I'm not sure if that system does have flaws (e.g. timouts overlap/if the performance could suffer)
> 
> btw can you specify what those problems are that you mentioned?

I was thinking of something simpler like this
```js
if (giveaway.lastCheck && (giveaway.remainingTime / 10 > Date.now() - giveaway.lastCheck)) return;
giveaway.lastCheck = Date.now();
```
I added that before fetching the message and it works great with a low `updateCountdownEvery`! Probably it should be saved in the giveaway data as well to prevent mass updates when the bot reboots.

**Comment by Nico105** [comment]
hmm, I just thought you wanted to get rid of the property as a whole

**Comment by Nico105** [comment]
#330 would technically fix this drama

**Comment by Androz2091** [comment]
Indeed, the message is not edited anymore as we now use Discord Timestamps.
