### ISSUE TITLE
A pre occupied giveaway appears all the time 

### ISSUE THREAD

**Issue by typhoon11** [Androz2091/discord-giveaways#276]
**Describe the bug**  

When running list giveaways the current giveaways of that server should be sent. But a pre-registered giveaway is being sent all the time even if that giveaway never took place on that guild and it's not in the database too.

**Error**  

GUILD - 1
https://typhoon.shx.is/AvunLl
GUILD - 2
https://typhoon.shx.is/ewoAdz
Nowhere in Database
https://typhoon.shx.is/JDvkmD

**To Reproduce**  

Using giveAway manager to fetch the data for the message guild and displaying it.

**Expected behavior**  

The current running giveaway should be shown but instead, another preoccupied giveaway is shown too

**Comment by Nico105** [comment]
Restarting does not remove it I assume?

**Comment by typhoon11** [comment]
Yeah, I have restarted the bot cleared the database but that pre-defined giveaway is still there

**Comment by Nico105** [comment]
very weird, shouldn't be possible.
You don't maybe have a second giveaway manager with the giveaways.json DB running, where that giveaway is saved?
Or maybe you .push it somewhere in your code?

Otherwise, did this just started appearing all of a sudden or can you remember that you changed some code before it started appearing?

**Comment by typhoon11** [comment]
No last month only I implemented the list giveaway command that showed the active giveaways that are running on that guild. I checked the command during implementation and after that at I used the command in many guilds too. Suddenly that day when I raised the question on GitHub I was using the list giveaway command and saw that in all guild a pre-defined giveaway is shown all the time and the time limit is also in `-`

**Comment by typhoon11** [comment]
Oh, wait nvm that giveaway got automatically disappeared today. 
![image](https://user-images.githubusercontent.com/66431066/117392292-63e11e00-af0f-11eb-967c-e06ea7aa33c1.png)
