### ISSUE TITLE
Delete giveaway when it ends

### ISSUE THREAD

**Issue by RunyardHartley** [Androz2091/discord-giveaways#28]
I'm really sorry with all the questions, but I have another one.  I would like to know if we can put a functionality in the "end" function which allows to remove the giveaway from the JSON file but not the message.  Because otherwise it accumulates ...

**Comment by Androz2091** [comment]
Yes, you can. Update the package to `3.0.12` and then:
```js
client.giveawaysManager.on('end', (giveaway) => {
    // Delete the giveaway, but don't delete the message
    client.giveawaysManager.delete(giveaway.messageID, false);
});
```
Also, you won't be able to reroll the giveaway once it's deleted.

**Comment by RunyardHartley** [comment]
Oh thank u !! ❤ We did not add one: After X ms delete the giveaway in the JSON file ?

**Comment by Androz2091** [comment]
You can do this:
```js
client.giveawaysManager.on('end', (giveaway) => {
	setTimeout(() => {
    	// Delete the giveaway, but don't delete the message
    	client.giveawaysManager.delete(giveaway.messageID, false);
	}, 60000*10); // wait 10 minutes before deleting it
});
```
but if you restart your bot, it will clear the timeout

**Comment by RunyardHartley** [comment]
I just tried but the message is also deleted

**Comment by Androz2091** [comment]
> Update the package to `3.0.12` and then:

Are you sure you did this?

**Comment by RunyardHartley** [comment]
Yes, the package is "discord-giveaways": "^3.0.12",

**Comment by Androz2091** [comment]
Oh, my bad, replace:
```js
client.giveawaysManager.delete(giveaway.messageID, false);
```
with:
```js
client.giveawaysManager.delete(giveaway.messageID, true);
```

**Comment by RunyardHartley** [comment]
Thank u so much !!!!!
