### ISSUE TITLE
How do I stop a user from participating?

### ISSUE THREAD

**Issue by Dragonizedpizza** [Androz2091/discord-giveaways#280]
How do I stop a user from participating? I know I can remove the reaction, but what if I don't want to remove the reaction, and only want their participation to be cancelled?

**Comment by Nico105** [comment]
https://github.com/Androz2091/discord-giveaways#exempt-members
With that you prevent users from winning without removing reactions.

**Comment by Dragonizedpizza** [comment]
exempt-members is what I was looking for, thanks.
