### ISSUE TITLE
Bug options.winnerCount is not a positive integer. [ParseInt]

### ISSUE THREAD

**Issue by CarlosMunozT** [Androz2091/discord-giveaways#285]
**Error**  
![image](https://user-images.githubusercontent.com/38010460/118388623-3836f580-b5eb-11eb-8645-9a39ee1476db.png)

**Additional context**

* `discord-giveaways` version:  4.5.1 
* `discord.js` version: 12
* Custom Database (if you use one): json

**Fix:**
Manager.js
Line: 199
Bug line: if (!Number.isInteger(options.winnerCount) || options.winnerCount < 1) {
Fix Line: if (!Number.isInteger(parseInt(options.winnerCount)) || parseInt(options.winnerCount) < 1) {

**Comment by Nico105** [comment]
We just require the dev to parse it when using the start function, since `winnerCount` is documented as a number.
So providing a string is a wrong value. 
(It is not an integer as the log says)
We do that so that the dev is aware of what he is providing.
