### ISSUE TITLE
Be able to specify allowed mentions

### ISSUE THREAD

**Issue by Androz2091** [Androz2091/discord-giveaways#286]
**Is your feature request related to a problem? Please describe.**  

We can't allow @everyone in the giveaway message if we disabled this mentions using the `allowedMentions` property in the Discord.js client constructor.

**Describe the solution you'd like**

Be able to do something like:
```js
start(channel, {
	messageOptions: {
		allowedMentions: {
			parse: ['everyone']
		}
	}
});
```

**Additional context**  

be sure to support discord.js v13 (the master branch of [discordjs/discord.js](https://github.com/discordjs/discord.js)) before

**Comment by Nico105** [comment]
Ahm I'm not sure if I understood correctly, but do you maybe want
```js
channel.send(giveaway.messages.giveaway, { embed, allowedMentions: this.client.options.allowedMentions });
```
?

**Comment by Androz2091** [comment]
Hmm, maybe that's what you wanted to say but actually, Discord.js v13 (the master branch), allows you to define default allowed mentions when you create a new client.
```js
new Discord.Client({
	allowedMentions: {
		parse: ['users', 'roles']
	}
});
```
so, now, for each message sent by the bot, only users and roles mentions will be parsed.

The thing is that for giveaway messages, users may want to override this default parameter passed to the Discord client, so @everyone can be parsed and used for the giveaway message

it would give something like:
```js
new Discord.Client({ allowedMentions: {
	parse: ['users', 'roles']
}});
```
```js
manager.start(channel, {
	messageOptions: {
		allowedMentions: {
			parse: ['everyone']
		}
	}
});
```

and 
```js
channel.send(giveaway.messages.giveaway, {
	embed,
	allowedMentions: giveaway.options.allowedMentions || this.client.options.allowedMentions
});

**Comment by Nico105** [comment]
ah, it's about overwriting, now I understand.
So I guess just move that option into the `messages` object? 
because it would be alone in an external object like "messageOptions", which is a little bit pointless... unless you want to add other options?

**Comment by Androz2091** [comment]
This has been added to v5. Run `npm install discord-giveaways@latest` to update!
