### ISSUE TITLE
Winners error.

### ISSUE THREAD

**Issue by fedesugo** [Androz2091/discord-giveaways#288]
Hi!, i have a problem with winners.
Instead of to mention the person that win the gw have a bug that in the @ and the first letter of the id is a space.
![Captura](https://user-images.githubusercontent.com/66099743/118670311-1c367e00-b7bc-11eb-9a40-7a6fbd0abf79.PNG)

**Comment by Nico105** [comment]
does this happen for every user that wins?

**Comment by fedesugo** [comment]
Yes

**Comment by Nico105** [comment]
Does it look like that in the embed aswell?

**Comment by fedesugo** [comment]
Nop only in the winners message

**Comment by Nico105** [comment]
hmm, you don't maybe use some fork of this project which has changed code?
or you maybe have otherwise customized package code through extending?

if not, can you show your `winMessage`, if you have a custom one.

**Comment by fedesugo** [comment]
yes 
![Captura](https://user-images.githubusercontent.com/66099743/118694641-e4d2cc00-b7d1-11eb-995f-ea27d314ca42.PNG)

**Comment by fedesugo** [comment]
yo can give me the line of the winners string please so i can edit the npm and solve the problem?

**Comment by Nico105** [comment]
> yes
> ![Captura](https://user-images.githubusercontent.com/66099743/118694641-e4d2cc00-b7d1-11eb-995f-ea27d314ca42.PNG)

ahem, why did you make it a function? it is supposed to just be a string

**Comment by fedesugo** [comment]
it work like that btw

**Comment by fedesugo** [comment]
the thing is a space (invisible space) in @ an the first letter of the id o the person i tried rewriting but nothing

**Comment by Nico105** [comment]
but how can this even happen, it's just;  `winners.map((w) => `<@${w.id}>`).join(', ');` nothing special about that. 
I mean you said it was like that for every user, but if you didn't change the package code it should be impossible.
and you have the latest version of this package I assume?

**Comment by fedesugo** [comment]
yes

**Comment by fedesugo** [comment]
yes i change it cause an other issue https://github.com/Androz2091/discord-giveaways/issues/285

**Comment by fedesugo** [comment]
i couldnt start the gw so i have to modifie the package

**Comment by fedesugo** [comment]
maybe if i try re-installing

**Comment by Nico105** [comment]
> yes i change it cause an other issue #285

man, you just need to use `parseInt()` when providing winnerCount...

**Comment by Nico105** [comment]
> it work like that btw

`UnhandledPromiseRejectionWarning: TypeError: this.messages.winMessage.replace is not a function`, 
you modified smth in the package code, so it's not really our problem if your code breaks...

**Comment by fedesugo** [comment]
yes i now but i use (message) => for exporting the message on the lang command

**Comment by fedesugo** [comment]
winners.map((w) => <@${w.id}>).join(', '); so this is in the api folders ?

**Comment by fedesugo** [comment]
i already update the parseInt in my command

**Comment by Nico105** [comment]
> winners.map((w) => <@${w.id}>).join(', '); so this is in the api folders ?

yeah, you should really compare what you changed with the base

**Comment by fedesugo** [comment]
already find that but i didnt find any space

**Comment by Nico105** [comment]
is it maybe cause of your discord.js vers? do you have a recent or an old one?

**Comment by fedesugo** [comment]
recent the last one actually

**Comment by fedesugo** [comment]
discord.js 12.5.3

**Comment by Nico105** [comment]
good, I checked, since i was a little behind but it's not cause of that.
hmm, i mean idk maybe try using the string without your function stuff, cause idk how you really implemented that
the package itself is fine, otherwise we would also probably have it if it were in the src code
I can just ask you to check the things that you customized/use differently than intended

**Comment by fedesugo** [comment]
Ok perfect.
