### ISSUE TITLE
Allow to use custom emotes as reactions

### ISSUE THREAD

**Issue by fluffymallow** [Androz2091/discord-giveaways#29]
When using custom emote for "reaction", the bot will not detect it and if the giveaway ended it will show the noWinner message.

**Comment by Androz2091** [comment]
@fluffymallow can you send your code (where you create a new instance of the GiveawaysManager)?

**Comment by Androz2091** [comment]
@fluffymallow any news?

**Comment by fluffymallow** [comment]
oooooh sorry sorry, i used your example bot [ https://github.com/Androz2091/giveaways-bot ]

**Comment by Androz2091** [comment]
Yes but what did you put for `reaction` for a custom emote?

**Comment by fluffymallow** [comment]
the id, sir

**Comment by Androz2091** [comment]
It's now possible. Just use ```js
new GiveawaysManager({
    default: {
         reaction: "REACTION ID"
    }
});
```
