### ISSUE TITLE
Announcement Channels 

### ISSUE THREAD

**Issue by LHCLYT** [Androz2091/discord-giveaways#297]
Hey! I have a problem, I just realised, that you can't do raffles in discord news/announcement channels.

I haven't found any way/variable to make it work?

Steps to reproduce:

- Create a normal giveaway in an announcement channel, the sweepstakes will stay shortly before the end, but will not edit the last message.

**Additional context**
* `discord-giveaways` version: 4.5.1
* `discord.js` version: 12.5.3
* Custom Database (if you use one): MySQL

**Comment by Dragonizedpizza** [comment]
How long is your giveaway?

**Comment by Dragonizedpizza** [comment]
also, Discord has a limit to cross post editing, I think 10-15 times.

**Comment by LHCLYT** [comment]
Can you think of any ideas on how to solve it?

**Comment by Nico105** [comment]
So at the end of the giveaway, it does not change the embed to the "ended" format?
Does it choose the winners?

**Comment by LHCLYT** [comment]
The draw is completed, as it saves all finished draw data in the database, but the winner's message is not edited.

**Comment by Nico105** [comment]
> The draw is completed, as it saves all finished draw data in the database, but the winner's message is not edited.

Can you send a screenshot of how the embed and the winMessage look like, cause I can't completely follow

And so in normal text channels everything works fine rigjt?

**Comment by LHCLYT** [comment]
Yeah, in normal channels works fine! But in the announcements... 

If the sweepstakes is done in an announcement channel, it sends the first countdown embed, and after a few edits, the embed stops editing.

**Comment by LHCLYT** [comment]
No... Can it be done?

I think Discord is throwing ratelimit anyway...

**Comment by Dragonizedpizza** [comment]
Cool, so I tested it on my bot, and it looks like you're cross-posting the message.

**Comment by LHCLYT** [comment]
Do you know of a possible solution? 🤔

**Comment by LHCLYT** [comment]
Hey?

**Comment by Dragonizedpizza** [comment]
There is no solution, other than not publishing the message, which is what you're doing.
...unless you're willing to set your giveaway edit timing to support Discord's limit.

**Comment by Nico105** [comment]
![image](https://user-images.githubusercontent.com/63612668/120897589-3d55f600-c627-11eb-86ff-e4966117d9ad.png)

**Comment by Dragonizedpizza** [comment]
Meaning, you must set the edit message timeout to 20 minutes.

**Comment by Nico105** [comment]
I guess we can't do/say more since we can't do anything against such guidelines.
