### ISSUE TITLE
Not enough entrants to determine a winner!

### ISSUE THREAD

**Issue by eNtee-bots** [Androz2091/discord-giveaways#298]
Everytime i start a giveaway he say :Not enough entrants to determine a winner! 
i using the custom db form the mongoose tutorial
i got no error and no message: Here some screenshots:

[Payshost Screenshot hoster](https://cloe.cheated.io/lo7WDK7w)
[Payshost Screenshot hoster](https://cloe.cheated.io/WKznlMJd)
[Payshost Screenshot hoster](https://cloe.cheated.io/cvHNcWAP)

My English is as bad as a 6 year old's  :(

**Comment by Nico105** [comment]
For custom reaction in your manager config, you only have to provide the numbers = without "<a" stuff

**Comment by eNtee-bots** [comment]
thank you for the help now it works you can close this <3
