### ISSUE TITLE
Stop

### ISSUE THREAD

**Issue by croyke** [Androz2091/discord-giveaways#3]
I want a command like
stop-giveaway - and that the giveaway stops. but i can't figure out how i would do this

**Comment by Androz2091** [comment]
Hello, 
You cannot yet make a command that will stop the giveaway, the module does not yet offer a function to do so. I will keep you informed when it is published!

**Comment by Androz2091** [comment]
When you say stop the giveway, what do you mean by that? The Giveaway ends now (drawing of winners before the end of the time)? The Giveaway stops (the timer is frozen? The Giveaway message is being deleted? The Giveaway message is edited by a message that indicates that it does not take place?

**Comment by GamingDome** [comment]
Yes stopping the giveaway removing the message, and delete all giveaway data

**Comment by Androz2091** [comment]
The module now has a `delete()` function to delete data and message from a giveaway.
Find more information [here](https://github.com/Androz2091/discord-giveaways#delete-a-giveaway).
Have a good day!
