### ISSUE TITLE
2 message at end

### ISSUE THREAD

**Issue by stijnb1234** [Androz2091/discord-giveaways#30]
Hello,

I entered to pick one winner, and it does, but it sends the "You have won" message 2 times.

Is this a bug, or am I doing something wrong?

Thanks in advance!

Kind regards,

Stijn

**Comment by Androz2091** [comment]
@stijnb1234 I'm not able to reproduce the bug, can you give more informations (like your code, whether it happens everytime or only sometimes, etc...)?
