### ISSUE TITLE
Compatibility issues with Discord.js v12 

### ISSUE THREAD

**Issue by SoulHarsh007** [Androz2091/discord-giveaways#31]
TypeError: this.message.reactions.find is not a function
keeps on showing this error while using Discord.js v12

**Comment by SoulHarsh007** [comment]
The bug still persists!

**Comment by Androz2091** [comment]
Hmm... can you send the full error?

**Comment by SoulHarsh007** [comment]
on bot reboots:
`TypeError: Cannot read property 'emoji' of null `

**Comment by Androz2091** [comment]
Did you update the package to `3.2.0`?

**Comment by SoulHarsh007** [comment]
Yes! I updated the npm package.

**Comment by Androz2091** [comment]
I can't reproduce the bug. It works perfectly for me. Can you send more details, like code, OS, etc...?

**Comment by SoulHarsh007** [comment]
Cannot send any data at the moment due to a recent hardware failure on my end.
