### ISSUE TITLE
Function to delete all giveaways that a server did

### ISSUE THREAD

**Issue by zelferry** [Androz2091/discord-giveaways#312]
I wish I had a function to delete all the DRAWS that a server did

**Comment by Nico105** [comment]
```js
client.giveawaysManager.giveaways.filter().forEach(g => client.giveawaysManager.delete(g.messageID))
```

**Comment by Dragonizedpizza** [comment]
> ```js
> filter()
> ```

why the filter function

**Comment by Nico105** [comment]
cause he said "that a server did", so he has to filter the server

**Comment by Dragonizedpizza** [comment]
> cause he said "that a server did", so he has to filter the server out

but how do they know that

**Comment by Nico105** [comment]
hdym? know what?
he just takes a server ID he wants and filter g => g.guildID === serverID

**Comment by Dragonizedpizza** [comment]
> hdym? know what?
> he just takes a server ID he wants and filter g => g.guildID === serverID

at the time, perhaps they wouldn't have known to put anything in the filter func
