### ISSUE TITLE
Support for other storage ways

### ISSUE THREAD

**Issue by Androz2091** [Androz2091/discord-giveaways#32]
Actually, the way to store giveaways is to use json files, as this doesn't require any additional packages. It would be nice to be able to use a sqlite file instead. I think the best way to add this feature is to check if an optional package like `better-sqlite3` is installed, and if so, it will use it. By default, the storage way will still be json files.

**Comment by RunyardHartley** [comment]
Yep!  It would also be nice to make a storage system like discord-backup, right?

**Comment by Androz2091** [comment]
Implemented in 4.0.0. See [Own Database](https://github.com/Androz2091/discord-giveaways#custom-database) for more informations!
