### ISSUE TITLE
Bonus Roles in Embed

### ISSUE THREAD

**Issue by typhoon11** [Androz2091/discord-giveaways#321]
**Is your feature request related to a problem? Please describe.**  

No, I want the bonus roles and the bonus entries to be displayed in the generated embed.

**Describe the solution you'd like**

Add the Bonus roles and the bonus entry of that role in the field of the embed.
```
◽ @role1 : 5 entries
◽ @role2 : 2entries
```
Something like this ^^

**Comment by Nico105** [comment]
you can just work with `\n` inside [messages.hostedBy, or if you disabled that, messages.timeRemaining](https://github.com/Androz2091/discord-giveaways#-translation)

or if you know how, just extend the `generateMainEmbed` function, add fields and save your data in `giveaway.extraData`

**Comment by typhoon11** [comment]
Okay cool I will give it a try. Thank You
