### ISSUE TITLE
Update branch discord.js-v13 to use latest v13 version

### ISSUE THREAD

**Issue by alima566** [Androz2091/discord-giveaways#326]
**Describe the bug**  

Due to new updates to the master branch of DJS, the casing of `thingID` properties has changed to `thingId` (https://deploy-preview-680--discordjs-guide.netlify.app/additional-info/changes-in-v13.html#thing-thingid), which is causing my project to error out.

**Error**  

```ts
  node_modules/discord-giveaways/node_modules/discord.js/typings/index.d.ts:886:12
    886     public ownerID: Snowflake;
                   ~~~~~~~
    'ownerID' is declared here.
```

**Comment by Nico105** [comment]
So are you on the discord.js-v13 branch of this package?

**Comment by alima566** [comment]
Yes I am.

**Comment by Nico105** [comment]
try updating our branch that should fix it I think.
Cause I updated the required package.json version of dc.js to branch to v13 recently.
Before that it was still v12 (required), thats why the error I think.

**Comment by alima566** [comment]
To update, would I do `npm i Androz2091/discord-giveaways#discord.js-v13@latest`?

**Comment by Nico105** [comment]
`npm update discord-giveaways` should be enough

**Comment by alima566** [comment]
It works now, thanks!
