### ISSUE TITLE
options.winnerCount is not a positive integer.

### ISSUE THREAD

**Issue by DarkPheonix2122** [Androz2091/discord-giveaways#329]
My error is listed below

(node:376) UnhandledPromiseRejectionWarning: options.winnerCount is not a positive integer. (val=3)
(node:376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by NotMarx** [comment]
You need to use the `parseInt` method. Referring to #222
