### ISSUE TITLE
Use new discord timestamps

### ISSUE THREAD

**Issue by DEVTomatoCake** [Androz2091/discord-giveaways#330]
**Describe the solution you'd like**

Add an option to use the new [discord timestamp formatting](https://c.r74n.com/discord/formatting#Timestamps) in giveaways to display the remaining time.

This would make the message editing every few seconds unused.

**Comment by Nico105** [comment]
You can already add it with the messages object option...

**Comment by alima566** [comment]
Which option would that be? I don't see it anywhere in the link you provided.

**Comment by Dragonizedpizza** [comment]
You could eliminate editing the message entirely with timestamp formatting.

**Comment by Nico105** [comment]
> Which option would that be? I don't see it anywhere in the link you provided.

`<t:${(Date.now() + timeVariable) / 1000}:R>`
You just edit the message...

**Comment by typhoon11** [comment]
> > Which option would that be? I don't see it anywhere in the link you provided.
> 
> `<t:${(Date.now() + timeVariable) / 1000}:R>`
> You just edit the specific message...

Don't forget to add `.toFixed(0)` or else it will give a decimal and then the formatting won't work.

**Comment by Nico105** [comment]
Ah right right, or use math.round()

**Comment by typhoon11** [comment]
But is there a way to stop the embed from editing, because even if I don't enter the `updateCountdownEvery`, it keeps on editing on its default value. So make an option if `updateCountdownEvery` is mentioned 0 it won't edit the embed

**Comment by Androz2091** [comment]
Here is my take on the potential transition to the new Discord timestamps. Even though we won't have as much control over how the date is displayed as we used to (`in 24 hours and 6 minutes` would become `in a day`), I think using them for the next version of `discord-giveaways` would be very interesting.

The benefits are significant : 
* removing all spammy requests to Discord to edit messages
* displaying the end date in the current user's language
* better Discord integration (e.g., getting the full end date by hovering over the timestamp)

I would be curious to have the opinion of owners of bots using the library, feel free to comment.

**Comment by alima566** [comment]
Removing the constant spammy requests to Discord to edit messages is a big plus. Currently removing the `updateCountdownEvery` does not work and still edits the message. Either removing this or setting this to 0, should stop the message from editing.

Also, if we have `lastChance` enabled, it should only edit the message once, once it reaches the threshold we specified.

**Comment by Nico105** [comment]
We just remove the message.edit().
The `updateCountdownEvery` would still be needed, just as `checkGiveawaysEvery`.

**Comment by Nico105** [comment]
Also, I assume we would remove the `remainingTimeText` getter, or not?
Would devs still want it?

**Comment by Dragonizedpizza** [comment]
I'd say it'd be pretty useful

**Comment by Nico105** [comment]
`drawing: 'Drawing: {timestamp}'`
And should this be the new message?
suggestions?

**Comment by Dragonizedpizza** [comment]
> `drawing: 'Drawing: {timestamp}'`
> And should this be the new message?
> suggestions?

what is drawing

**Comment by Nico105** [comment]
> > `drawing: 'Drawing: {timestamp}'`
> > And should this be the new message?
> > suggestions?
> 
> what is drawing

similar term to "rolling"
the timestamp will be "in 5 hours"
so `Drawing: in 5 hours`
you can interpret it like this I guess "I am drawing: in 5 hours" or as "The drawing will take place: in 5 hours"
as said im open to suggestions

**Comment by Androz2091** [comment]
This has been added to v5. Run `npm install discord-giveaways@latest` to update!
