### ISSUE TITLE
v13 installation & query

### ISSUE THREAD

**Issue by Dragonizedpizza** [Androz2091/discord-giveaways#338]
When installing, I get this: ![image](https://user-images.githubusercontent.com/70718540/127337389-b34b397f-63eb-4379-8a8b-9323bf6774e5.png)/

Also, does Giveaway#messageID become Giveaway#messageId?

**Comment by Nico105** [comment]
`npm i Androz2091/discord-giveaways#discord.js-v13`

**Comment by Nico105** [comment]
And concerning ID to Id...
@Androz2091 you want to change?
Im not sure since it would be an unnecessary, possible breaking change, but on the other hand discord.js makes the transition, so maybe we should adjust too?

**Comment by Dragonizedpizza** [comment]
> `npm i Androz2091/discord-giveaways#discord.js-v13`

oh wait, I'm dumb lol

**Comment by Dragonizedpizza** [comment]
![image](https://user-images.githubusercontent.com/70718540/127339913-ce723682-9a30-440e-86c6-a36d792c2375.png)
oh yeah, this is what I was encountering

**Comment by Nico105** [comment]
maybe `npm i git://github.com/Androz2091/discord-giveaways.git#discord,js-v13`
this seem to be a issue of the place wherever you try installing

**Comment by Dragonizedpizza** [comment]
zsh's issue

**Comment by Dragonizedpizza** [comment]
nvm query still stands

**Comment by Dragonizedpizza** [comment]
uh...?

**Comment by Dragonizedpizza** [comment]
messageId or messageID?

**Comment by Nico105** [comment]
you will have to wait till Androz answers, since I don't want to charge forth.
I already put it into the v13 pr questions.

**Comment by Androz2091** [comment]
Yes we should now use Id instead of ID, as discord.js v13 does

**Comment by Nico105** [comment]
> Yes we should now use Id instead of ID, as discord.js v13 does

ok, and so since this breaks things 😆
suggestion to rename `time` to `duration` for the start() options
?

**Comment by Nico105** [comment]
> Yes we should now use Id instead of ID, as discord.js v13 does

should `winnerIDs` stay or `winnerIds`?

**Comment by Dragonizedpizza** [comment]
obviously winnerIds

**Comment by Nico105** [comment]
yeah right `winnerIdentifications` is proper camelCase.
I just thought it looked a little weird to have Ids 😆

**Comment by Dragonizedpizza** [comment]
ok you thought winnerIds looked weird and winnerIdentifications didn't

**Comment by Nico105** [comment]
🤷‍♂️😆

**Comment by Androz2091** [comment]
This has been added to v5. Run `npm install discord-giveaways@latest` to update!
