### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by namekinggamerboy** [Androz2091/discord-giveaways#34]
Giveaway Command not working in master how to fix means error is RichEmbed() not a function wot to get update rich to MessageEmbed()

**Comment by Androz2091** [comment]
@namekinggamerboy can you try to update the package (`npm install discord-giveaways`)?

**Comment by namekinggamerboy** [comment]
Yes fully Update work but not edit time in master discord.js version or sable work only

**Comment by Androz2091** [comment]
I just published a new version so if you tried yesterday, please retry.
Also, can you run `npm list` please?

**Comment by namekinggamerboy** [comment]
Ok try

**Comment by namekinggamerboy** [comment]
![Screenshot_2020-03-04-18-42-25-586](https://user-images.githubusercontent.com/53903319/75882827-fa1b3f00-5e47-11ea-85bb-5ec9ac3ded23.jpeg)
Sorry but console cash

**Comment by Androz2091** [comment]
I wanted to see the other packages, you already told me you installed the latest version of discord-giveaways

**Comment by namekinggamerboy** [comment]
Please contact discord my name is discord ⏺️NAME BOY⏺️#2751
