### ISSUE TITLE
Move to slash commands

### ISSUE THREAD

**Issue by AR-Student824** [Androz2091/discord-giveaways#343]
**Is your feature request related to a problem? Please describe.**  

Discord will be locking Message Content behind an intent for verified bots in a year or so

**Describe the solution you'd like**

Slash Commands are the only way to bypass that, so this framework should move to that instead of providing custom prefixes.

**Describe alternatives you've considered**  

Make a seperate package that uses slash commands to keep custom prefixes on this one, for non verified bots.

**Additional context**  

N/A

**Comment by Nico105** [comment]
your alternative is a little over the top to say the least 😂
I already made a question about this in #336 -> what to do
But we don't really have to stress about anything since we just have it in the example readme commands and so it doesn't affect the package itself.

**Comment by Androz2091** [comment]
Custom prefixes?
In the readme you mean?

**Comment by Nico105** [comment]
> Custom prefixes?
> In the readme you mean?

yeah he means that. (and the little file in examples)
Since your on this topic. What do you want to do?
- Switch to slash. 
- Keep prefix, since it's still valid for <100 guild bots
- remove the "command" way and just display the package functions without `args`

**Comment by Androz2091** [comment]
We should use slash commands yes
Wait for djs v13 to be released to update the examples, because we don't know exactly how slash commands will be integrated get

**Comment by Dragonizedpizza** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> Discord will be locking Message Content behind an intent for verified bots in a year or so
> 
> **Describe the solution you'd like**
> 
> Slash Commands are the only way to bypass that, so this framework should move to that instead of providing custom prefixes.
> 
> **Describe alternatives you've considered**
> 
> Make a seperate package that uses slash commands to keep custom prefixes on this one, for non verified bots.
> 
> **Additional context**
> 
> N/A

...actually, you can receive all data about your own messages, which I think includes reactions?

**Comment by Nico105** [comment]
> > **Is your feature request related to a problem? Please describe.**
> > Discord will be locking Message Content behind an intent for verified bots in a year or so
> > **Describe the solution you'd like**
> > Slash Commands are the only way to bypass that, so this framework should move to that instead of providing custom prefixes.
> > **Describe alternatives you've considered**
> > Make a seperate package that uses slash commands to keep custom prefixes on this one, for non verified bots.
> > **Additional context**
> > N/A
> 
> ...actually, you can receive all data about your own messages, which I think includes reactions?

yeah sure. I think he phrased his issue a little wrong.
He's just talking about the examples in the README. Not the package code/functionality.

**Comment by DemonixDev** [comment]
Wait what? Everyone will need to move to slash commands? You wont be able to use normal ones?

**Comment by Nico105** [comment]
> Wait what? Everyone will need to move to slash commands? You wont be able to use normal ones?

if your bot is in less than 100 guilds you can still use normal prefix.

**Comment by DemonixDev** [comment]
This is actually bad, i think i will start redo my bot in half of redo  to v13, ima just do support for slash commands so i wont have to worry

**Comment by DemonixDev** [comment]
But if i want do automod i can get Access? I will probably only use the Access for chatbot and automod, rest will  be done with slash commands

**Comment by Nico105** [comment]
> But if i want do automod i can get Access? I will probably only use the Access for chatbot and automod, rest will be done with slash commands

can't really say. I suggest you ask/search that in the API server.

**Comment by AR-Student824** [comment]
> This is actually bad, i think i will start redo my bot in half of redo to v13, ima just do support for slash commands so i wont have to worry

Yeah the deadline is until August of next year I believe, just move as much stuff as you can to slash commands, and apply for the rest when it's available.

**Comment by Nico105** [comment]
So since https://github.com/discordjs/guide/pull/786 is now available,
README Suggestion

___
The slash command examples for `discord-giveaways`'s are based on the registering process of the [discord.js guide](https://github.com/discordjs/guide/blob/4a9aedc24c717e654231818a14b9a86ad502a324/guide/interactions/registering-slash-commands.md#global-commands).

The interaction handler for `discord-giveaways`'s slash command examples is assumed to be:
```js
client.on('interactionCreate', async (interaction) => {
	if (!interaction.isCommand()) return;
	const command = require(`./commands/${interaction.commandName}`);
	return await command.run();
}
```

## Start a giveaway
```js
module.exports = {
    data: { 
        name: 'start-giveaway'
        description: 'Starts a new giveaway'
        options: [ 
          {
             // to lazy to write this now.
          }
        ]
    },
    run: async (interaction) => { // or "execute" if you like that more
         interaction.client.giveawaysManager.start(interaction.channel, {
                time: ms(interaction.options.get('time').value),
                winnerCount: interaction.options.get('winnerCount').value,
                prize: interaction.options.get('prize').value
            }).then((gData) => {
                console.log(gData); // {...} (messageID, end date and more)
            });
            // And the giveaway has started!
    }
}
```
@Androz2091 your thoughts?

**Comment by adrifcastr** [comment]
you should not `return await`, command name may not be the filename, and you should definitely use the options resolver properly instead of using get().

**Comment by Nico105** [comment]
> you should not `return await`, command name may not be the filename, and you should definitely use the options resolver properly instead of using get().

i use it as an aesthetic 😅
yeah but for simplicity we should assume so no? should i add a remark, or do you really want to add a try catch?
options.data.find then? or do you just want to go with [0], but if the order is changed by the dev this wouldn't match/or should we ignore that? or am I completely thinking wrong? (this is a first for me 😆)

**Comment by adrifcastr** [comment]
You don't seem to understand the options resolver at all. I suggest you learn djs before suggesting stuff like that.

**Comment by Nico105** [comment]
😑 that doesn't answer the question/isn't helpful

**Comment by Androz2091** [comment]
Why don't you create your own pull request if you think you can improve Nico's example with your experience with Discord.js? It will probably bring much more to the project than your previous message 😉

**Comment by Androz2091** [comment]
I created an [example bot](https://github.com/Androz2091/discord-giveaways-bot) that uses discord-giveaways and slash commands.

**Comment by AR-Student824** [comment]
@Androz2091 alright sounds good
