### ISSUE TITLE
Allow to edit lastChance option in GiveawaysManager#edit

### ISSUE THREAD

**Issue by NotMarx** [Androz2091/discord-giveaways#346]
I've been searching through the [docs](https://discord-giveaways.js.org) and found that this isn't possible to do hence I'd like if we can add eg. `newLastChance` option to the `GiveawayEditOptions` to be able to edit `lastChance`.

This is also considered a problem (at least to me) since it'll be weird to have this not supported yet. 

Thoughts??

**Comment by Nico105** [comment]
I mean, will this actually be used?
Since would you really use a edit command just to edit the last chance phase of 1 giveaway, which is just temporary anyway?

**Comment by NotMarx** [comment]
> I mean, will this actually be used?
> Since would you really use a edit command just to edit the last chance phase of 1 giveaway, which is just temporary anyway?

Let's say your bot support 2 languages (English and Spanish languages) and someone start a giveaway with the English language configured on the bot. If there's no `newLastChance` option on `GiveawayEditOptions`, there's no possibility to change the `content` on `LastChaneOptions` to the Spanish language when someone edit a giveaway with the Spanish language configured within the bot 

I still considered this as a missing feature cause it can be a problem when their bots are multilingual.

**Comment by Nico105** [comment]
Added in v13 branch.

**Comment by NotMarx** [comment]
Awesome!
