### ISSUE TITLE
unused var

### ISSUE THREAD

**Issue by Dragonizedpizza** [Androz2091/discord-giveaways#348]
https://github.com/Androz2091/discord-giveaways/blob/master/src/Manager.js#L387
Why is the messageID param in there, even though its not used?

**Comment by Nico105** [comment]
For key-value DBs, like enmap.
Ik tchnically we could also get it from giveawayData, but that shouldn't matter much.

**Comment by Dragonizedpizza** [comment]
> For key-value DBs, like enmap.
> Ik tchnically we could also get it from giveawayData, but that shouldn't matter much.

eslint throws an error for unused var

**Comment by Nico105** [comment]
only if you view it through node_modules
for package development there is `'no-unused-vars': 0`

**Comment by Dragonizedpizza** [comment]
> only if you view it through node_modules and have eslint enabled for that path (I think)
> for package development there is `'no-unused-vars': 0` in the config file
I meant my eslint, when I'm extending the class

**Comment by Nico105** [comment]
ahh
yeah... I guess since we're breaking the db examples in v13 anyway, i guess i will remove it and use giveawayData.messageId

**Comment by Nico105** [comment]
Or would it be to inconvinient to add a eslint disable comment?
Since for sql dbs the key is, think, always/mostly required no?
Im unsure if it

**Comment by Androz2091** [comment]
You can simply remove the param when extending the class right? It won't throw an error.

**Comment by Nico105** [comment]
> You can simply remove the param when extending the class right? It won't throw an error.

`function(messageId, giveawayData)`
Something has to be there, or hdym "remove"?

**Comment by Dragonizedpizza** [comment]
> You can simply remove the param when extending the class right? It won't throw an error.

discord-giveaways will still internally pass the messageId param, and the method would consider it as giveawayData

**Comment by Androz2091** [comment]
This code should be valid with eslint:
```
saveGiveaway (messageID, data) {
console.log(data);
// as the second argument was used, no error is thrown for the messageID param 
}
```
Am I wrong?

**Comment by Dragonizedpizza** [comment]
yes, but the lib doesn't require the messageID param at all

**Comment by Dragonizedpizza** [comment]
also, the error was about messageID, not data, so `console.log(messageID)`

**Comment by Androz2091** [comment]
Nop, because if you use the second property, eslint will see that you have no other way than declaring messageID even if you don't use it

**Comment by Nico105** [comment]
yeah I checked it myself right now, no error when 1st is not used but 2nd is.

@Dragonizedpizza did you add args: all ? since only then would it error for me

**Comment by Dragonizedpizza** [comment]
nope

**Comment by Nico105** [comment]
> nope

weird, are you sure its not from some other rule maybe that you have customized?

**Comment by Nico105** [comment]
I will close this for now since this seems to be coming from somewhere else/the devs own settings.

**Comment by Dragonizedpizza** [comment]
> I will close this for now since this seems to be coming from somewhere else/the devs own settings.

but the messageId param is literally pointless

**Comment by Nico105** [comment]
> > I will close this for now since this seems to be coming from somewhere else/the devs own settings.
> 
> but the messageId param is literally pointless

it's more readable than referencing from the object i guess.
As said key-value, and most of the examples use it.
