### ISSUE TITLE
Cannot read property 'members' of null

### ISSUE THREAD

**Issue by waki285** [Androz2091/discord-giveaways#349]
**Describe the bug**  

I'm having this repository error:
```
       if (new Discord.Intents(this.client.options.intents).has('GUILD_MEMBERS')) await guild.members.fetch();
                                                                                               ^

TypeError: Cannot read property 'members' of null
    at Giveaway.roll (/home/runner/AuroraBot-Dev/node_modules/discord-giveaways/src/Giveaway.js:411:96)
    at /home/runner/AuroraBot-Dev/node_modules/discord-giveaways/src/Giveaway.js:517:40
```

**To Reproduce**  

1. start giveaway
2. wait to end the giveaway
3. bot restart

**Additional context**

* `discord-giveaways` version:git+https://github.com/Androz2091/discord-giveaways.git#discord.js-v13
* `discord.js` version:13.0.1
* Custom Database (if you use one):@replit/database

**Comment by Nico105** [comment]
you really are on .0.1?
I thought they had fixed this... 😑, will report.
I will add || channel.guild since they mentioned that should work.
Thanks for the letting know.

**Comment by Nico105** [comment]
Nah moment.
With 0.1 they already added || channel.guild themselves.
Hmmm tf.

**Comment by Nico105** [comment]
Also, was this a 1 time occurrence? Or did this happen for multiple giveaways?

**Comment by waki285** [comment]
Giveaway starts with the guild's text channel.
Also, I'm not using `end` or` reroll` and I can hold Giveaway normally until I reboot.

**Comment by waki285** [comment]
Additional bug,
Restarting the bot will reroll the Giveaway that should have ended.

**Comment by Nico105** [comment]
> Additional bug,
> Restarting the bot will reroll the Giveaway that should have ended.

so there were winners before the restart, but after the restart it rolled again?

**Comment by waki285** [comment]
> > Additional bug,
> > Restarting the bot will reroll the Giveaway that should have ended.
> 
> so there were winners before the restart, but after the restart it rolled again?
Yes. There was a winner, but it rerolls when I restart.

**Comment by waki285** [comment]
hmmmm... I'm very bitter about the bug that giveaway resets when I reboot.

**Comment by Nico105** [comment]
> hmmmm... I'm very bitter about the bug that giveaway resets when I reboot.

are you sure that you followed the example for the custom db correctly?
since its a known issue that replit resest local storage dbs
but if you have configured the extended class properly it should normally be fine

**Comment by waki285** [comment]
> > hmmmm... I'm very bitter about the bug that giveaway resets when I reboot.
> 
> are you sure that you followed the example for the custom db correctly?
> since its a known issue that replit resets local storage dbs (json)
> but if you have configured the extended class properly it should normally be fine

I'm using @replit/database database

**Comment by Nico105** [comment]
> > > hmmmm... I'm very bitter about the bug that giveaway resets when I reboot.
> > 
> > 
> > are you sure that you followed the example for the custom db correctly?
> > since its a known issue that replit resets local storage dbs (json)
> > but if you have configured the extended class properly it should normally be fine
> 
> I'm using @replit/database database

so you 100% do not see a "giveaways.json" file in your project right?

**Comment by waki285** [comment]
> > > > hmmmm... I'm very bitter about the bug that giveaway resets when I reboot.
> > > 
> > > 
> > > are you sure that you followed the example for the custom db correctly?
> > > since its a known issue that replit resets local storage dbs (json)
> > > but if you have configured the extended class properly it should normally be fine
> > 
> > 
> > I'm using @replit/database database
> 
> so you 100% do not see a "giveaways.json" file in your project right?

Yes, I don't see a "giveaways.json".

**Comment by Nico105** [comment]
And so the gaw resets happen every restart?

**Comment by Androz2091** [comment]
Closed due to inactivity
