### ISSUE TITLE
editing issue

### ISSUE THREAD

**Issue by Yasser-Alshinawah** [Androz2091/discord-giveaways#357]
Editing is stupid, I have the issue of when a guild kicks my bot from their server but starts a giveaway then once it try’s to edit the message it just crashes this issue can be fixed by the package switching to discord timestamps, I’m on node.js v16 and discord.js v13.1.0

**Comment by Yasser-Alshinawah** [comment]
![image](https://user-images.githubusercontent.com/73202985/129489194-732d9675-2118-4b9e-a2a0-093722d7c478.jpeg)

**Comment by Nico105** [comment]
fixed it
and regarding timestamps, will come with next release

**Comment by Androz2091** [comment]
This has been added to v5. Run `npm install discord-giveaways@latest` to update!
