### ISSUE TITLE
Support for more more winners?

### ISSUE THREAD

**Issue by menix1337** [Androz2091/discord-giveaways#36]
Is it possible to adjust the giveaway if the description embed char reaches 255 > it then possibly skips writing names into the embed description?

And eventually if hitting max limit numbers in the say text (where it prints the winners names in) make multiple messages with more names if you have more winners than maybe 20?

All of this to adjust it being able to support more than 20ish winners per giveaway? Cause currently it just doesn't roll if you have above 20-25 winners, since it hits the description char limit from embeds? (Whcih could be avoided with if limit (255) > don't paste into description & just list multiple messages with winner names) to automatic adjust for a 'x' amount of winners? 

So if winners < 20 = it can update description to include winnner names.. If > 25, it doesn't upgrade the description with names - eventually just say (Winner(s) listed below) then print alot of rows with names.

**Comment by Androz2091** [comment]
Yes, it will be added!

**Comment by menix1337** [comment]
> Yes, it will be added!

Would be awesome! I know many who uses it, and with discords with over 17.000 members its annoying having to host 4 seperate giveaways for like 70-100 Winners! ^^

I am aware of at least 10 servers myself who Could have use of it ^^

**Comment by menix1337** [comment]
Also is there a way to define each Winners discord ids? Lets say you have 100 winners (when this fix is in place)

You reckon its possible to award all Winners with a Discord rank? Provided by the bot using script - automaticly from their mentions or something.. ids?

**Comment by Androz2091** [comment]
@menix1337 You should use the `giveawayEnded` event. You will have access to an array of winners. You'll be able to do something like that:
```js
giveawaysManager.on("giveawayEnded", (giveaway, winners) => {
    winners.forEach((winner) => winner.roles.add("role ID"));
});
```
Also, can you send me your Discord? It could help me to have an idea for how to fix your problems with large giveaways.

**Comment by menix1337** [comment]
> @menix1337 You should use the `giveawayEnded` event. You will have access to an array of winners. You'll be able to do something like that:
> 
> ```js
> giveawaysManager.on("giveawayEnded", (giveaway, winners) => {
>     winners.forEach((winner) => winner.roles.add("role ID"));
> });
> ```
> 
> Also, can you send me your Discord server? It could help me to have an idea for how to fix your problems with large giveaways.

Sure, how would I go about to invite? I can easily toss up a test giveaway so you get the idea of the massive amount of people signing into it :D

**Comment by Androz2091** [comment]
Yes, you can send the link here.

**Comment by menix1337** [comment]
> Yes, you can send the link here.

Discord.gg/Asura

I am named MENIX on right side

**Comment by menix1337** [comment]
> @menix1337 You should use the `giveawayEnded` event. You will have access to an array of winners. You'll be able to do something like that:
> 
> ```js
> giveawaysManager.on("giveawayEnded", (giveaway, winners) => {
>     winners.forEach((winner) => winner.roles.add("role ID"));
> });
> ```
> 
> Also, can you send me your Discord server? It could help me to have an idea for how to fix your problems with large giveaways.

```
manager.on("giveawayEnded", async (giveaway, winners) => {
	const role = await giveaway.message.guild.roles.create({ data: { name: "GiveawayWinners" } });
	winners.forEach(winner => giveaway.message.guild.member(winner).roles.add(role.id))
});
``` 
Is the solution for that

**Comment by menix1337** [comment]
Any updates on the initial request yet - since you've been working on it?

**Comment by menix1337** [comment]
Any updates on the initial request yet - since you've been working on it back then? @Androz2091
Not sure if you ever got around to fix this (undocumented?)

**Comment by Androz2091** [comment]
No, honestly I didn't keep working on this feature. It's still something that's planned, but I can't tell you when it will be added...

**Comment by Nico105** [comment]
🎉 v4.5.0 is now released!

**Comment by menix1337** [comment]
This is awesome!

I wanna give some feedback to you guys, its been 2 years under way.

So i did a test with a 100 winners: 
https://i.imgur.com/A7XlwK2.png (Reacting) & https://i.imgur.com/bPOApQW.png (Done)

It worked so floorless, its amazing.

Then i tried to see if i could do a test with 300 winners: 
https://i.imgur.com/vwcZmis.png (Reacting) & https://i.imgur.com/bPOApQW.png (Done)

Out from 300 winners, it still only picked a 100 actually.

Is there a cap on a 100 winners? and is it possible to up this even higher? Theres enough embed space, thats for sure - because look at this here

https://i.imgur.com/5CNSWTC.png

The first message event is well filled out, however the second message event only has like 10 users or so, and could of course handle much more.

Anyhow, i know this is something hard to do - and its been underway for ages.

**Thank you so much @Nico105 @Androz2091 .**

**Comment by menix1337** [comment]
[giveaways.zip](https://github.com/Androz2091/discord-giveaways/files/6404805/giveaways.zip)
Heres a copy of the giveaways.json zip file containing both of these giveaways.

**Comment by Nico105** [comment]
The 100 limit is because default `fetch()` value is 100, but you cannot increase it, because it would be API spam or smth.
But you can fetch the other users in 100 steps because you can use a option to define the last ID you fetched because data from discord is sorted by ID. #254 would try to do that but I couldn't test it because you would need actual people for testing because you need different IDs as mentioned. You can try to test it if you want and provide feedback but there could be ratelimit errors.

**Comment by Nico105** [comment]
_For my testing I had those 170 more winners because I pushed myself that many times manually into the winner Array_

**Comment by menix1337** [comment]
> The 100 limit is because default `fetch()` value (for the reactions) is 100, but you cannot increase it, because it would be API spam or smth.
> But you can fetch the other users in 100 steps because you can use a option to define the last ID you fetched because data from discord is sorted by ID. #254 would try to do that but I couldn't test it because you would need actual people for testing because you need different IDs as mentioned. You can try to test it if you want and provide feedback but there could be ratelimit errors.

Should i just grab the pull request from that post - and toss another 300 users test up .. See what happens, and give feedback?

**Comment by Nico105** [comment]
Yeah would be nice.
But so just copy the changes and insert manually since that pr doesn't have the split-messages system

**Comment by menix1337** [comment]
> Yeah, that would be nice.
> But so just copy the changes and insert them manually since that pr doesn't have the split-messages system

![image](https://user-images.githubusercontent.com/17611705/116692334-1830f080-a9b4-11eb-8de5-7ccbc499221f.png)

I have one going, expect an answer in 10 minutes times - I've just copied in the changes in Giveaway.js.

**Comment by menix1337** [comment]
![image](https://user-images.githubusercontent.com/17611705/116694300-056beb00-a9b7-11eb-87ee-032201b93e28.png)
![image](https://user-images.githubusercontent.com/17611705/116694307-0866db80-a9b7-11eb-8848-dfb834b15ea3.png)
![image](https://user-images.githubusercontent.com/17611705/116694314-0b61cc00-a9b7-11eb-8114-2b96af5dc32f.png)

It works.. The embed itself looks a little finicky, however the long list of winning users prints out just fine!
Bot printed no errors in console or anything.

To double check this, you see i have a script saying "adding roles to 300 users" - its because i have discord auto adding a role to all the winners in the giveaway - it takes toughly 6m 50s to add a role to 300 users because of API rate limits.

But it went through, it actually did work - all users got the roles as expected, i was able to add everyone points..

It actually worked.. I feel like this is a 2 year fight, a huge relief - a battle that has lasted so long towards making this work!

around 10 minutes after payout i looked at the embed again, and it looked like this
![image](https://user-images.githubusercontent.com/17611705/116695015-e6ba2400-a9b7-11eb-81c0-1e20b2f2b6e5.png)

I honestly would deem it approved - i could test with more, but i already pinged 24.000 users 4 times with giveaways within an hour, so i better stop before they get angry.

300 people, this pull request - 100% confirmed.. 
It might not be fully tested yet if it always will work, but it for sure did a (excuse my swearing) fucking great wonder.

You guys are litteral gods.

**Comment by Nico105** [comment]
Thank you very much for testing.
and so this
![image](https://user-images.githubusercontent.com/63612668/116695468-f5590900-a9c0-11eb-8070-e6ff028152eb.png)
Changed to
![image](https://user-images.githubusercontent.com/63612668/116695504-fe49da80-a9c0-11eb-96f4-2dd691d2e2e7.png)
automatically after some time, right? = no problem?

**Comment by menix1337** [comment]
> Thank you very much for testing.
> 
> and just to confirm, this:
> ![image](https://user-images.githubusercontent.com/63612668/116695468-f5590900-a9c0-11eb-8070-e6ff028152eb.png)
> Changed to
> ![image](https://user-images.githubusercontent.com/63612668/116695504-fe49da80-a9c0-11eb-96f4-2dd691d2e2e7.png)
> automatically after some time (10m), right?
> 
> If yes, then I will request Androz's review for the pr to see if he has any comment/improvement to make and I'll merge afterwards.

If exact 10 minutes - not 100% - But yes, it did change from <@90382948725> into an actual tag, yes - a bit after the giveaway was over, inside the embed.

**Comment by menix1337** [comment]
![image](https://user-images.githubusercontent.com/17611705/116697775-80370500-a9bb-11eb-9009-1ad7f58c8954.png)
![image](https://user-images.githubusercontent.com/17611705/116697784-82995f00-a9bb-11eb-8ebd-d1a8d58678dc.png)

The final output

**Comment by menix1337** [comment]
I'm at the point thinking it could probably even take more on - 300+ 
There was no issues at all doing it at 300, no delays, no crashes, no setbacks..

It was just smooth

**Comment by Nico105** [comment]
👍 Great and thanks again, just inform me if anything strange happens somewhen.

**Comment by menix1337** [comment]
> 👍 Great and thanks again, just inform me if anything strange happens somewhen.

Will do, its probably not something that will get spammed 24/7 and tested - but i will keep you guys aware in here through time.

**Comment by Androz2091** [comment]
Hello
@Nico105's PR seems to be the best way to support +100 reactions giveaways. I merged it, you can try to clone the develop branch.

**Comment by Androz2091** [comment]
This has been added to v5. Run `npm install discord-giveaways@latest` to update!
