### ISSUE TITLE
v13 ?

### ISSUE THREAD

**Issue by irasakipkm** [Androz2091/discord-giveaways#361]
Hello
can you update the package to discord js v13, because the embed is not working.

thank you

**Comment by Nico105** [comment]
You can already install the branch for it if you want.
`npm i Androz2091/discord-giveaways#discord.js-v13`
Tho don't do that with old gaws still running.

**Comment by irasakipkm** [comment]
> npm i Androz2091/discord-giveaways#discord.js-v13

`
Since I installed version 13 of the giveaway
I tried to update the functions
the link to the giveaway message no longer works, it redirects me to my friends instead of the giveaway can you help me?

/* client's GiveawaysManager Events */
client.giveawaysManager.on('giveawayReactionAdded', async (giveaway, member, reaction) => {
    if (member.user.bot) return;
    try {
      if(giveaway.extraData){
      await client.guilds.cache.get(giveaway.extraData.server).members.fetch(member.id)
      }
      const embed1 = new MessageEmbed()
       // new Discord.MessageEmbed()
         
          .setTitle(`Giveaway entry approved`)
          .setDescription(
            `Your entry to this giveaway [${giveaway.prize}](https://discord.com/channels/${giveaway.guildID}/${giveaway.channelID}/${giveaway.messageID}) has been approved.`
          )
         
          .setColor("RANDOM")
          .setTimestamp(`${new Date(giveaway.endAt).toISOString()}`)
      
      member.send({ embeds: [embed1] });

    } catch (error) {
    }})
  `

> Vous pouvez déjà installer la branche pour cela si vous le souhaitez.
> `npm i Androz2091/discord-giveaways#discord.js-v13`
> Ne fais pas ça avec les vieux gaws toujours en marche.

**Comment by Nico105** [comment]
> > npm i Androz2091/discord-giveaways#discord.js-v13
> 
> `
> Since I installed version 13 of the giveaway
> I tried to update the functions
> the link to the giveaway message no longer works, it redirects me to my friends instead of the giveaway can you help me?
> 
> ```js
> client.giveawaysManager.on('giveawayReactionAdded', async (giveaway, member, reaction) => {
>     if (member.user.bot) return;
>     try {
>       if(giveaway.extraData){
>       await client.guilds.cache.get(giveaway.extraData.server).members.fetch(member.id)
>       }
>       const embed1 = new MessageEmbed()
>        // new Discord.MessageEmbed()
>          
>           .setTitle(`Giveaway entry approved`)
>           .setDescription(
>             `Your entry to this giveaway [${giveaway.prize}](https://discord.com/channels/${giveaway.guildID}/${giveaway.channelID}/${giveaway.messageID}) has been approved.`
>           )
>          
>           .setColor("RANDOM")
>           .setTimestamp(`${new Date(giveaway.endAt).toISOString()}`)
>       
>       member.send({ embeds: [embed1] });
> 
>     } catch (error) {
>     }})
> ```
> 
> > Vous pouvez déjà installer la branche pour cela si vous le souhaitez.
> > `npm i Androz2091/discord-giveaways#discord.js-v13`
> > Ne fais pas ça avec les vieux gaws toujours en marche.

First, I already mentioned that using try catch like that is a little counterproductive, but nvm.

What do you mean by "I tried to update the functions"? What functions?

And regarding the link, it should work fine.
What do you mean with "it redirects me to my friends"? Friends what?

**Comment by irasakipkm** [comment]
> > > npm i Androz2091/discord-giveaways#discord.js-v13
> > 
> > 
> > `
> > Since I installed version 13 of the giveaway
> > I tried to update the functions
> > the link to the giveaway message no longer works, it redirects me to my friends instead of the giveaway can you help me?
> > ```js
> > client.giveawaysManager.on('giveawayReactionAdded', async (giveaway, member, reaction) => {
> >     if (member.user.bot) return;
> >     try {
> >       if(giveaway.extraData){
> >       await client.guilds.cache.get(giveaway.extraData.server).members.fetch(member.id)
> >       }
> >       const embed1 = new MessageEmbed()
> >        // new Discord.MessageEmbed()
> >          
> >           .setTitle(`Giveaway entry approved`)
> >           .setDescription(
> >             `Your entry to this giveaway [${giveaway.prize}](https://discord.com/channels/${giveaway.guildID}/${giveaway.channelID}/${giveaway.messageID}) has been approved.`
> >           )
> >          
> >           .setColor("RANDOM")
> >           .setTimestamp(`${new Date(giveaway.endAt).toISOString()}`)
> >       
> >       member.send({ embeds: [embed1] });
> > 
> >     } catch (error) {
> >     }})
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > Vous pouvez déjà installer la branche pour cela si vous le souhaitez.
> > > `npm i Androz2091/discord-giveaways#discord.js-v13`
> > > Ne fais pas ça avec les vieux gaws toujours en marche.
> 
> First, I already mentioned that using try catch like that is a little counterproductive, but nvm.
> 
> What do you mean by "I tried to update the functions"? What functions?
> 
> And regarding the link, it should work fine.
> What do you mean with "it redirects me to my friends"? Friends what?

the link does not redirect me to the giveaway but to the friends box of Discord

**Comment by Nico105** [comment]
> .

Ah right, I forgot you're using v13, thingID changed to thingId.
you have to adjust that.
But honestly, it would be easier if you just use `giveaway.messageURL`

**Comment by irasakipkm** [comment]
thanks a lot for your help

> > .
> 
> Ah right, I forgot you're using v13, thingID changed to thingId.
> you have to adjust that.
> But honestly, it would be easier if you just use `giveaway.messageURL`

**Comment by Androz2091** [comment]
Discord Giveaways now supports Discord.js v13. Run `npm install discord-giveaways@latest` to update!
