### ISSUE TITLE
SyntaxError: Unexpected token '??='

### ISSUE THREAD

**Issue by tibbehennebel** [Androz2091/discord-giveaways#368]
So, I wanted to run a discord bot with a giveaway feature in it with this npm, but when I run it it gives the unexpected token error (see picture).
Does anybody know how to fix this? I've tried a fresh install of this npm but still the error persists.
![Screenshot_1](https://user-images.githubusercontent.com/33593071/132566065-601fc3ce-60fb-416c-bfb1-d523e60eff47.png)

**Comment by Nico105** [comment]
discord-giveaways v5 is built for discord.js v13
And v13 requires node.js v16.6 = so we do it too, since we use features from 16.6
You need to update your node.js

**Comment by tibbehennebel** [comment]
> discord-giveaways v5 is built for discord.js v13
> And v13 requires node.js v16.6 = so we do it too, since we use features from 16.6
> You need to update your node.js

Thank you so much! It works perfectly now
