### ISSUE TITLE
Giveaway Does Not End

### ISSUE THREAD

**Issue by alima566** [Androz2091/discord-giveaways#369]
**Describe the bug**  
The giveaway does not end after the time has expired, even after restarting the bot.

**Expected behavior**  
The giveaway should end automatically.

**Screenshots**  
![image](https://user-images.githubusercontent.com/14950662/132719251-e545bb5f-1941-4c1f-ac40-b39892342076.png)

**Additional context**

* `discord-giveaways` version: 5.0.1
* `discord.js` version: 13.1.0
* Custom Database (if you use one): MongoDB

**Comment by Dragonizedpizza** [comment]
probably started before db migrate

**Comment by Nico105** [comment]
> **Describe the bug**
> The giveaway does not end after the time has expired, even after restarting the bot.
> 
> **Expected behavior**
> The giveaway should end automatically.
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/14950662/132719251-e545bb5f-1941-4c1f-ac40-b39892342076.png)
> 
> **Additional context**
> 
> * `discord-giveaways` version: 5.0.1
> * `discord.js` version: 13.1.0
> * Custom Database (if you use one): MongoDB

have you adjusted to the new mongoose schema? *if you use mongoose*

**Comment by alima566** [comment]
> probably started before db migrate

You were right. For some reason, that giveaway didn't save into the DB. All other giveaways ended as expected.
