### ISSUE TITLE
embeColor option not working in GiveawayManager#start method

### ISSUE THREAD

**Issue by Shashank3736** [Androz2091/discord-giveaways#378]
**Describe the bug**  

options.embedColor is not working in GiveawayStartOption.

**To Reproduce**  

Start a giveaway and in options.embedColor put "GREEN"

**Expected behavior**  

A green color in embed for giveaway but receive default one.

**Additional context**

* `discord-giveaways` : v5.0.1
* `discord.js` version: v13.1.0
* Custom Database (if you use one): Mongo DB 

The problem is there because of [`validateEmbedColor`](https://github.com/Androz2091/discord-giveaways/blob/master/src/utils.js#L3) method. As this method do not allow `string` embedColor option.

**Comment by Tomato6966** [comment]
Same thing

I think it's because of Discord.Util.resolveColor returning Something, not changing the value you pass in
so it should be something like this:
```js
const validateEmbedColor = (embedColor) => {
    try {
        var embedColorNum = Discord.Util.resolveColor(embedColor);
        if (!isNaN(embedColorNum) && typeof embedColorNum === 'number') return true;
        else return false;
    } catch {
        return false;
    }
};
```
Proof: 
![image](https://user-images.githubusercontent.com/68145571/141840548-0965cdc1-d726-4399-85db-1521c4c0cca0.png)

**Comment by Nico105** [comment]
*the fix pr is alread merged in dev*

**Comment by Nico105** [comment]
v5.1.0 has been released
