### ISSUE TITLE
Giveaways not ending

### ISSUE THREAD

**Issue by Tomato6966** [Androz2091/discord-giveaways#380]
The giveaways are not ending

And yes they are starting

V5.0.1

D.js v13

node v16.11

![Screenshot_20211017-235757_Termius](https://user-images.githubusercontent.com/68145571/137646417-e14e4efe-e0ab-46c7-8fe8-d172cb5b388e.jpg)
![Screenshot_20211017-235714_Termius](https://user-images.githubusercontent.com/68145571/137646418-0840a172-e222-4c21-8b88-ff00548d3df5.jpg)
![Screenshot_20211017-235655_Termius](https://user-images.githubusercontent.com/68145571/137646419-63d26edb-5421-4080-8995-7455422116ec.jpg)

**Comment by Nico105** [comment]
Are they still in the db file? If yes, are they marked as ended, or not?

**Comment by Tomato6966** [comment]
They arent in the DB file anymore

**Comment by Nico105** [comment]
> Maybe i should use a different data storeage? Such as sqlite how can i do so (very easily) i already use enmap in my bot

Examples are in the example folder.

I mean do you know anything about your host "reseting" perodically? Cause for example replit has that problem = local storage for gaws is unusable.

**Comment by Nico105** [comment]
> @Nico105
> 
> I just found out i am sharding: ![image](https://user-images.githubusercontent.com/68145571/137723964-fd116009-827b-4e0c-b699-e2146ef843a5.png)
> 
> But i am sharding INTERNALLY
> 
> shards: "auto"

How many servers is your bot in?

**Comment by Nico105** [comment]
Any new knowledge?

**Comment by Tomato6966** [comment]
Yes uhm sorry for not responding, that did the Trick.
