### ISSUE TITLE
embedColor option of PauseOptions don't work

### ISSUE THREAD

**Issue by GeistFighter** [Androz2091/discord-giveaways#388]
**Describe the bug**  

Hello, the embedColor option of the PauseOptions doesn't work, the color doesn't change, can you tell me if this is from me?

![image](https://user-images.githubusercontent.com/42804270/140556028-825c031b-7135-4aa9-8ea4-77c4b9ff70fa.png)

**To Reproduce**  

Place this code to pause the giveaways : 
![image](https://user-images.githubusercontent.com/42804270/140556188-10bcfb5f-a50a-47ed-ae07-5471ecf27ee6.png)

**Additional context**

* `discord-giveaways` version: 5.0.1
* `discord.js` version: 13.3.1
* `NodeJs` version: 16.13.0

**Comment by Nico105** [comment]
*gforce experience glitch*
https://user-images.githubusercontent.com/63612668/140560022-73299e96-a9dc-4b64-a761-23b9e7d03dbb.mp4

works fine for me...

**Comment by GeistFighter** [comment]
Mmmm, after a test, the color change works (it goes to yellow) but if you put another color than yellow, it still goes to yellow, so there is still a bug.

**Comment by Nico105** [comment]
v5.1.0 has been released
