### ISSUE TITLE
isDrop giving unexpected error

### ISSUE THREAD

**Issue by typhoon11** [Androz2091/discord-giveaways#389]
**Describe the bug**  

When isDrop is true, it's throwing an error
![image](https://user-images.githubusercontent.com/66431066/140600687-a56b1440-ffb4-4423-aec2-a760b09ba2c8.png)

This error is not coming when isDrop is false.

**To Reproduce**  

Make isDrop true

**Expected behavior**  

Giving range error

**Additional context**

* `discord-giveaways` version: 5.0.1
* `discord.js` version: 13.3.1
* Custom Database (if you use one): MongoDB

**Comment by Nico105** [comment]
_for the record: issue was because custom `generateMainEmbed` function didn't match v5_
