### ISSUE TITLE
Embed in start function

### ISSUE THREAD

**Issue by itzLBaandatube** [Androz2091/discord-giveaways#395]
I want to know how to change entire embed in start function

**Comment by itzLBaandatube** [comment]
In fact. I try to do.it but seems like its dosen't work
```js
bot.giveaway.start(msg.channel, {
            duration: ms(time), winnerCount: parseInt(winners), prize: prize, messages: { content: '', embed: new MessageEmbed().setAuthor(`${this.prize}`, msg.guild.iconURL({dynamic: true})).setImage(msg.attachments.first() ?? null).setDescription(`🎁 Prize : **${this.prize}**}n🏅 Winner Count : **${this.winnerCount}**\n⏱️ Duration : **{duration}**\n📨 Hosted By ${msg.author}`) }
        })
```
![Why you look at name of the image?](https://user-images.githubusercontent.com/92731667/141885116-bc24da59-5839-4739-ac78-1b66959fd16d.png)

**Comment by Shashank3736** [comment]
You can create a custom manager and overwrite the [generateMainEmbed](https://discord-giveaways.js.org/GiveawaysManager.html#generateMainEmbed) method to edit embed completely. Make sure to return Discord.MessageEmbed in the method.

**Comment by itzLBaandatube** [comment]
> You can create a custom manager and overwrite the [generateMainEmbed](https://discord-giveaways.js.org/GiveawaysManager.html#generateMainEmbed) method to edit embed completely. Make sure to return Discord.MessageEmbed in the method.

I don't understand where to use this method in code

**Comment by Shashank3736** [comment]
> I don't understand where to use this method in code

Create a class `CustomManager` that extends `GiveawaysManager`  create a method `generateMainEmbed` in your custom class. `generateMainEmbed` take `giveaway` as a variable and returns `Discord.MessageEmbed` as value. Now use that class as your giveaway manager. A simple example of using custom manager is available [here](https://github.com/Androz2091/discord-giveaways/blob/master/examples/sharding.js#L14) in this example @Androz2091 overwrites method refreshStorage to support sharding. We will overwrite `generateMainEmbed` to support custom embed.
