### ISSUE TITLE
Custom embed

### ISSUE THREAD

**Issue by SomeoneThatForkAnythingHeNeeds** [Androz2091/discord-giveaways#398]
Hey . I have same priblem as [this guy](https://github.com/Androz2091/discord-giveaways/issues/395). I see the solution. But I'm didn't understand. I want an example or something

**Comment by Nico105** [comment]
https://github.com/Androz2091/discord-giveaways/issues/204#issuecomment-770760259

**Comment by SomeoneThatForkAnythingHeNeeds** [comment]
> [#204 (comment)](https://github.com/Androz2091/discord-giveaways/issues/204#issuecomment-770760259)

Ok i do the same but with other embed. Now. I want to know what is the giveaway?
Because i deal with it like rhe giveaway that we start
```js
class CustomGiveawaysManager extends GiveawaysManager {
    generateMainEmbed(giveaway) {
        const embed = new MessageEmbed();
        embed.setAuthor(`${giveaway.prize}`, giveaway.message.guild.iconURL({dynamic: true})).setImage(giveaway.message.attachments?.first() || null).setDescription(`🎁 ${giveaway.prizeTitle} : **${giveaway.prize}**}n🏅 ${giveaway.winnerTitle} : **${giveaway.winnerCount}**\n⏱️ ${giveaway.timeTitle} : **${giveaway.duration}**\n📨 ${giveaway.hostedbyTitle} ${giveaway.message.author}`) 
        return embed;
    }
};
```
My start :
```js
bot.giveaway.start(lb.channel, {
            duration: ms(time), winnerCount: parseInt(winners), prize: prize, message: lb, hostedbyTitle: 'Hosted By', timeTitle: 'Duration', winnerTitle: 'Winner Count', prizeTitle: 'Prize'})
```

**Comment by SomeoneThatForkAnythingHeNeeds** [comment]
![Screenshot_2021-11-28-14-50-56-93](https://user-images.githubusercontent.com/94541840/143768547-c56f03c0-5c90-4d2d-8dd8-fa9d1155128d.png)

**Comment by Nico105** [comment]
> > [#204 (comment)](https://github.com/Androz2091/discord-giveaways/issues/204#issuecomment-770760259)
> 
> Ok i do the same but with other embed. Now. I want to know what is the giveaway? Because i deal with it like rhe giveaway that we start
> 
> ```js
> class CustomGiveawaysManager extends GiveawaysManager {
>     generateMainEmbed(giveaway) {
>         const embed = new MessageEmbed();
>         embed.setAuthor(`${giveaway.prize}`, giveaway.message.guild.iconURL({dynamic: true})).setImage(giveaway.message.attachments?.first() || null).setDescription(`🎁 ${giveaway.prizeTitle} : **${giveaway.prize}**}n🏅 ${giveaway.winnerTitle} : **${giveaway.winnerCount}**\n⏱️ ${giveaway.timeTitle} : **${giveaway.duration}**\n📨 ${giveaway.hostedbyTitle} ${giveaway.message.author}`) 
>         return embed;
>     }
> };
> ```
> 
> My start :
> 
> ```js
> bot.giveaway.start(lb.channel, {
>             duration: ms(time), winnerCount: parseInt(winners), prize: prize, message: lb, hostedbyTitle: 'Hosted By', timeTitle: 'Duration', winnerTitle: 'Winner Count', prizeTitle: 'Prize'})
> ```

Please provide understandable sentences.
And just as a notice, you cannot add properties like `hostedByTitle` like you do. It will not get stored in the db.
Use `extraData` for custom properties.

**Comment by Nico105** [comment]
> ![Screenshot_2021-11-28-14-50-56-93](https://user-images.githubusercontent.com/94541840/143768547-c56f03c0-5c90-4d2d-8dd8-fa9d1155128d.png)

giveaway.message can be null. fetch it if it is.

**Comment by SomeoneThatForkAnythingHeNeeds** [comment]
> > > [#204 (comment)](https://github.com/Androz2091/discord-giveaways/issues/204#issuecomment-770760259)
> > 
> > 
> > Ok i do the same but with other embed. Now. I want to know what is the giveaway? Because i deal with it like rhe giveaway that we start
> > ```js
> > class CustomGiveawaysManager extends GiveawaysManager {
> >     generateMainEmbed(giveaway) {
> >         const embed = new MessageEmbed();
> >         embed.setAuthor(`${giveaway.prize}`, giveaway.message.guild.iconURL({dynamic: true})).setImage(giveaway.message.attachments?.first() || null).setDescription(`🎁 ${giveaway.prizeTitle} : **${giveaway.prize}**}n🏅 ${giveaway.winnerTitle} : **${giveaway.winnerCount}**\n⏱️ ${giveaway.timeTitle} : **${giveaway.duration}**\n📨 ${giveaway.hostedbyTitle} ${giveaway.message.author}`) 
> >         return embed;
> >     }
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > My start :
> > ```js
> > bot.giveaway.start(lb.channel, {
> >             duration: ms(time), winnerCount: parseInt(winners), prize: prize, message: lb, hostedbyTitle: 'Hosted By', timeTitle: 'Duration', winnerTitle: 'Winner Count', prizeTitle: 'Prize'})
> > ```
> 
> Please provide understandable sentences. And just as a notice, you cannot add properties like `hostedByTitle` like you do. It will not get stored in the db. Use `extraData` for custom properties.

And how ro use extraData

**Comment by Nico105** [comment]
https://discord-giveaways.js.org/global.html#GiveawayStartOptions

**Comment by SomeoneThatForkAnythingHeNeeds** [comment]
> https://discord-giveaways.js.org/global.html#GiveawayStartOptions It can be anything you like

So its be like that on start options? :
```js
extraData: {message: 'bla bla', something: 'bla''}
```

**Comment by SomeoneThatForkAnythingHeNeeds** [comment]
And when i call it on the manger?
`giveaway.extraData.something`

**Comment by Nico105** [comment]
yeah and yeah

**Comment by SomeoneThatForkAnythingHeNeeds** [comment]
> yeah and yeah

Another question. How to get the duration on custom embed?

**Comment by Nico105** [comment]
> > yeah and yeah
> 
> Another question. How to get the duration on custom embed?

`giveaway.duration` just read the docs...

**Comment by SomeoneThatForkAnythingHeNeeds** [comment]
> > > yeah and yeah
> > 
> > 
> > Another question. How to get the duration on custom embed?
> 
> `giveaway.duration` just read the docs...

Ok thx

**Comment by SomeoneThatForkAnythingHeNeeds** [comment]
> > > yeah and yeah
> > 
> > 
> > Another question. How to get the duration on custom embed?
> 
> `giveaway.duration` just read the docs...

Its get the time in ms. I want the discord timestamp duration.

**Comment by Nico105** [comment]
Then you just have to look at the original generator from the package...
/ google. It's really not that hard to do a little research...

**Comment by SomeoneThatForkAnythingHeNeeds** [comment]
> Then you just have to look at the original generator from the package... / google. It's really not that hard to do a little research...

Ok i do it and works thx  but before close the issue i want ask another question
If i want to use the generateEndEmbed function so the example above work on it?

**Comment by SomeoneThatForkAnythingHeNeeds** [comment]
> [#204 (comment)](https://github.com/Androz2091/discord-giveaways/issues/204#issuecomment-770760259)

I mean this example

**Comment by Nico105** [comment]
Yeah
