### ISSUE TITLE
Discord timestamp (giveaway time)

### ISSUE THREAD

**Issue by irasakipkm** [Androz2091/discord-giveaways#399]
hello I wanted to know how to use the new discord timestamp to define the duration of a giveaway like this

[https://i.ibb.co/dLNQdg8/time.png](url)

  timeRemaining: "Time remaining:: **{duration}**!",
  
  what should be replaced please?

**Comment by Nico105** [comment]
You link doesn't work for me but I assume you want the "old" duration format? "1hour, 10min, 10sec"?

**Comment by irasakipkm** [comment]
> You link doesn't work for me but I assume you want the "old" duration format? "1hour, 10min, 10sec"?

No, I want the new format timestamps that Discord has set up like this one in video:
https://www.youtube.com/watch?v=VADX8HEiqM0

but i don't know how to set it up

**Comment by Nico105** [comment]
![image](https://user-images.githubusercontent.com/63612668/143906224-8208ff6c-c1a0-42b8-8d8e-ce076f5f5500.png)
I mean this is already the default for v5 of this package...
if you want a other format then you can write your code into the `{ this.duration + '>'}` brackets

**Comment by Lcxd65** [comment]
For the reroll command if there are no new users the bot will say: "No valid participations, no new winner(s) can be chosen!". How can I do this

**Comment by Nico105** [comment]
> For the reroll command if there are no new users the bot will say: "No valid participations, no new winner(s) can be chosen!". How can I do this

https://github.com/Androz2091/discord-giveaways#-translation
