### ISSUE TITLE
No winners (bug?) (v4.5.1)

### ISSUE THREAD

**Issue by Suni29** [Androz2091/discord-giveaways#401]
Okay so i was using this package for one of my small bots, and i setted up and everything but when i tested it on discord, it always said that there is no winners but i reacted with multiple accounts and it still said the same thing, my node version is v16.6.2 my discord.js version is v12 and i use the version 4.5.1 (discord-giveaways).

Also sorry if i placed this on the wrong place.

**Comment by Nico105** [comment]
check if you have exemptPermissions active in your manager config

**Comment by Suni29** [comment]
oh, ur the best ty
