### ISSUE TITLE
Error: `Cannot read properties of undefined (reading 'author')`

### ISSUE THREAD

**Issue by LHCLYT** [Androz2091/discord-giveaways#408]
**Describe the bug**  
I'm having an error with the latest version of discord-giveaways, because for some reason I don't know it gives the error, in the mentioned title

**Error**  
![image](https://user-images.githubusercontent.com/46402841/146803131-232e5787-0bde-4fad-9db0-c0967b0bb27b.png)

**To Reproduce**  
I don't know how reproduce this.

**Additional context**

* `discord-giveaways` version: latest
* `discord.js` version: latest
* Custom Database: mysql

**Comment by imranbarbhuiya** [comment]
This bug is identified today and I'll make a pr to fix the same.

This error occurs if anyone removes the giveaway embed using the `x` button from the message.

**Comment by LHCLYT** [comment]
Okey! Let me know if you solve it!

**Comment by LHCLYT** [comment]
However, it is not clear to me that the error comes from where you mentioned, since it is in the process of checking the draws.

**Comment by Nico105** [comment]
v5.1.0 has been released
