### ISSUE TITLE
exemptMembers:

### ISSUE THREAD

**Issue by AndromCoders** [Androz2091/discord-giveaways#41]
Hello,

adding in exemptMembers: (members) => !members.roles.some((r)=> r.name ==='Role name'),

to the .start options

it seems not to recognize the winner has the role or not the role.  the code still selects the winner without the role.

other than that all seems to be running

discord.js  Library version :v12.2

**Comment by ShreyashKira** [comment]
Same issue I have in my bot

**Comment by Androz2091** [comment]
Hello
Maybe it's because the member is not cached. What is the size of your server?

**Comment by ShreyashKira** [comment]
Yeah, its almost 190 members. It is cached because discord.js says, 250 members.

**Comment by TalonSilverStaff** [comment]
Same 563 members. 6 members on testing server.  Cached the members same issue. Seems like it might be 100 cache limit.

**Comment by NicoHd105** [comment]
same

**Comment by ShreyashKira** [comment]
Is someone finds any solution for this

**Comment by Androz2091** [comment]
Can you install v4.2.0 and check if this has been fixed for you?

**Comment by ShreyashKira** [comment]
Yeahh now fixed for me.
