### ISSUE TITLE
DeprecationWarning: Channel#deleted is deprecated

### ISSUE THREAD

**Issue by alima566** [Androz2091/discord-giveaways#411]
**Describe the bug**  

Due to the recent discord.js update (v13.4.0), getting this deprecation warning every time a giveaway is started.

**To Reproduce**  

Just start a giveaway and this deprecation warning should appear in your console.

**Additional context**

* `discord-giveaways` version: 5.0.1
* `discord.js` version: 13.4.0

**Comment by NotMarx** [comment]
I assume 04144a7 fixed this issue. You can install the dev version (`npm install Androz2091/discord-giveaways#develop`) to ignore the deprecation warning.

**Comment by Nico105** [comment]
v5.1.0 has been released
