### ISSUE TITLE
Replace usage of deprecated `String.prototype#substr` method

### ISSUE THREAD

**Issue by CoolJim** [Androz2091/discord-giveaways#415]
**Describe the bug**  

`String.prototype#substr` is a deprecated method and should be replaced with `String.prototype#substring` [see MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr)

**Error**  

n/a

**To Reproduce**  

Look around the code for `String.prototype#substr`

**Expected behavior**  

Remove deprecated methods

**Screenshots**  

Example of usage:
![image](https://user-images.githubusercontent.com/43405050/148170957-bf33ed2c-1b98-42cf-a82e-9857bcfa3a92.png)

**Additional context**

* `discord-giveaways` version: 5.0.1
* `discord.js` version: 13.3.1
* Custom Database (if you use one): mongodb (not applicable)

n/a

**Comment by imranbarbhuiya** [comment]
It's fixed in `Develop` branch and will be released soon.

**Comment by CoolJim** [comment]
Ah ok thanks

**Comment by CoolJim** [comment]
I'll close this issue since its fixed then
