### ISSUE TITLE
footer bug

### ISSUE THREAD

**Issue by BeLikeThugi** [Androz2091/discord-giveaways#417]
it doesnt write the amount of winners that are eligible to win in the normal giveaways' footer. it shows only in drops.

**Comment by Nico105** [comment]
Did you edit the footer message?

**Comment by BeLikeThugi** [comment]
no i didnt

**Comment by Nico105** [comment]
you're on v5.0.1?

**Comment by BeLikeThugi** [comment]
Yes.

**Comment by Nico105** [comment]
did you extend the `generateEmbed` function?

**Comment by Nico105** [comment]
@BeLikeThugi

**Comment by Nico105** [comment]
Please send your giveaway start options.
And maybe a screenshot of the embed

**Comment by Nico105** [comment]
If no additional information will be provided then I will have to close this issue, since it's not really reproduceable for me.
