### ISSUE TITLE
DeprecationWarning: Passing strings for MessageEmbed#setFooter is deprecated. Pass a sole object instead.

### ISSUE THREAD

**Issue by GeistFighter** [Androz2091/discord-giveaways#419]
**Describe the bug**  

Due to the discord.js update (v13.4.0), getting this deprecation warning every time a giveaway is started.

**Error**  

![image](https://user-images.githubusercontent.com/42804270/150641512-ddcda768-9873-4b87-beea-e12f00421029.png)

**To Reproduce**  

Start a giveaways.

**Additional context**

* `discord-giveaways` version: 5.0.1
* `discord.js` version: 13.6.0

Thanks you !

**Comment by Nico105** [comment]
v5.1.0 has been released
