### ISSUE TITLE
reroll error

### ISSUE THREAD

**Issue by nitplayz** [Androz2091/discord-giveaways#425]
I am getting an error in `reroll command` 
Its telling no giveaway foud even the message is Id correct i checked the mongo db there was also the same message ID
code: https://srcb.in/iv6VHyyxRD
error
https://media.discordapp.net/attachments/910072093276794890/935866271642288158/unknown.png?width=888&height=427

mongo ss:https://media.discordapp.net/attachments/910072093276794890/935866697548701696/unknown.png

**Comment by Nico105** [comment]
You wrote `const messageId = options.getString("message-id")
` but in your slash options you called it `messageId` so the names don't match.

**Comment by nitplayz** [comment]
> You wrote `const messageId = options.getString("message-id") ` but in your slash options you called it `messageId` so the names don't match.

brehh thanks for figuring it out
