### ISSUE TITLE
DM users if they are eligible for giveaway

### ISSUE THREAD

**Issue by amrit-2006** [Androz2091/discord-giveaways#427]
DM users if they have the requirement roles (exemptMembers) function , at the time when they react to the giveaway itselves and also add a field in the embed that these roles are required to entered the giveaway

**Comment by imranbarbhuiya** [comment]
You can listen to `GiveawayManager` event iirc the event name is `giveawayReactionAdd` then check if they don't have the role then dm you aren't eligible else dm entry confirmed

**Comment by amrit-2006** [comment]
How exactly can we retrieve the roles of that function that `giveawayReactionAdd` event

**Comment by imranbarbhuiya** [comment]
> How exactly can we retrieve the roles of that function at `giveawayReactionAdd` event

store the required roles in `extraData` and use it along with `exemptMember`

**Comment by amrit-2006** [comment]
What does the exemptPermission do

**Comment by Nico105** [comment]
https://github.com/Androz2091/discord-giveaways#exempt-members
