### ISSUE TITLE
5 seconds interval

### ISSUE THREAD

**Issue by nitplayz** [Androz2091/discord-giveaways#428]
hi,
I want to know that i have seen some bots using discord-giveaways and they edit the giveaway time every 5 seconds 
so how cani do that or enable that

**Comment by reinhello** [comment]
Yes, just do `forceUpdateEvery: 5000` on your `GiveawaysManager` class.

```js
const manager = new GiveawaysManager(client, {
       forceUpdateEvery: 5000, // time in ms          
       default: {
               // etc
        }
});

client.giveawaysManager = client;
```

**Comment by nitplayz** [comment]
my code: const { GiveawaysManager } = require('discord-giveaways');
const giveawayModel = require("../Schemas/Giveaways");
const emojis = require("../botconfig/emojis.json");

module.exports = (client) => {
    const GiveawayManagerWithOwnDatabase = class extends GiveawaysManager {

        async getAllGiveaways() {
            return await giveawayModel.find().lean().exec();
        }
    
        async saveGiveaway(messageId, giveawayData) {
            await giveawayModel.create(giveawayData);
            return true;
        }
    
        async editGiveaway(messageId, giveawayData) {
            await giveawayModel.updateOne({ messageId }, giveawayData, { omitUndefined: true }).exec();
            return true;
        }
    
        async deleteGiveaway(messageId) {
            await giveawayModel.deleteOne({ messageId }).exec();
            return true;
        }
    };
    
    const manager = new GiveawayManagerWithOwnDatabase(client, {
        forceUpdateEvery: 5000,
        default: {
            botsCanWin: false,
            embedColor: '#FF0000',
            embedColorEnd: '#000000',
            reaction: `${emojis.gw}`
        }
    });
    client.giveawaysManager = manager;
}


but its showing still like thishttps://media.discordapp.net/attachments/910072093276794890/936623404222677092/unknown.png

**Comment by imranbarbhuiya** [comment]
1st. Why you want to edit every 5s?

Iirc this `forceUpdateEvery` checks for is editing needed then it edits if necessary else it'll ignore.

**Comment by nitplayz** [comment]
o ok

but can u tell me i have added some message in the start command but its not showing in giveaway messages as u can see in above image 
 ```js
const {options} = interaction;

        const gchannel = options.getChannel("channel") || interaction.channel;
        const duration = options.getString("duration");
        const winnerCount = options.getInteger("winners");
        const prize = options.getString("prize")

        client.giveawaysManager.start(gchannel, {
            duration: ms(duration),
            winnerCount,
            prize,
            messages : {
                giveaway: `${emojis.gw} __**GIVEAWAY**__${emojis.gw}`,
                giveawayEnded: `${emojis.gw} __**GIVEAWAY ENDED**__ ${emojis.gw}`,
                winMessage: `${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}\n`+ emojis.gw+"Congratulations {winners}! you won **{this.prize}**!\n"+`${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}${emojis.dd}`,
                timeRemaining: "Time remaining: **{duration}**!",
                embedFooter: `Ending in:` + " " + ms(ms(duration))+", Winners:"+" " +winnerCount,
                hostedBy : "Hosted by: {this.hostedBy}",
                inviteToParticipate: "React with"+" "+emojis.gw +" "+"to participate!"


            }
        }).then(async () => {
            return interaction.reply({embeds: [success.setDescription(`${emojis.tick} Successfully started giveaway with follwing data:`)
            .addField(`Duration`, `${ms(ms(duration))}`, true)
            .addField(`Winners`, `${winnerCount}`, true)
            .addField(`Prize`, `${prize}`, true)

        ], ephemeral: true});

``
![unknown](https://user-images.githubusercontent.com/83857989/151562052-bf679098-b77b-404d-904c-9410f30188fc.png)
`

**Comment by Nico105** [comment]
> https://media.discordapp.net/attachments/910072093276794890/936623404222677092/unknown.png

`timeRemaining` changed to `drawing`
the `hostedBy` message will only get set if you provide `hostedBy: user` outside of the messages object too.
