### ISSUE TITLE
Drop ends with 0 winners if participant triggers exemptMembers

### ISSUE THREAD

**Issue by GeistFighter** [Androz2091/discord-giveaways#429]
**Describe the bug**  

In fact, the problem is that when a person who is normally part of the exclusions reacts, he is counted in the drop as a person who reacts, but is not counted in the fact that he can win, so if there is only one winner on the drop, if the 1st to add the reaction is a person who is part of the exclusions, the drop stops because it takes him into account, but indicates the "NoWinner" because he is excluded, so it would be necessary that the exclusions are also applied to the counter of the Drop reaction.

On the other hand, if there are several winners in the drop, if among the winners there are people excluded, the number of winners will not be equal to the number of winners set.

**Error**  

The error is that it sets the "noWinner" variable directly, so the Giveaway stops, the error is the "noWinner", i don't have a real error, I don't know if that is clear?

**To Reproduce**  

Example 1:
- Launching a Giveaway Drop with 1 winner
- The 1st person to set the reaction must be a user excluded from the rewards
- Giveaway ends without a winner

Example 2:
- Start a Giveaway Drop with 2 winners
- The 1st person who sets the reaction must be a non-excluded user and then the second must be excluded from rewards
- The Giveaway ends with one winner instead of two

**Expected behavior**  
That users excluded from the rewards do not count against the Giveaways Drop counter.

**Screenshots**  
I can make a video if necessary.

**Additional context**

* `discord-giveaways` version: 5.1.0
* `discord.js` version: 13.6.0

Thanks you !

**Comment by GeistFighter** [comment]
A video as an example: 😄 
https://user-images.githubusercontent.com/42804270/151698488-78676ea6-99a8-4ddf-a867-6d169a5d6147.mp4

**Comment by imranbarbhuiya** [comment]
#213 this can solve your issue

**Comment by GeistFighter** [comment]
Hi, yes indeed, putting an option that checks the number of winners required would solve the problem, but it would be like adding more steps, in this case, it would be easier to add the check of exemptMembers directly to the addition of the reaction on the Giveaway Drop ?

**Comment by Nico105** [comment]
> Hi, yes indeed, putting an option that checks the number of winners required would solve the problem, but it would be like adding more steps, in this case, it would be easier to add the check of exemptMembers directly to the addition of the reaction on the Giveaway Drop ?

exemptMembers was meant as a barrier directly before ending, e.g. when the bot was offline and users reacted.

What you mean is technically the reactionAdded event.
But it won't be fast enough (isn't awaited) if there is only 1 winner/when 2/3 reacted and the 3rd one reacts

**Comment by Nico105** [comment]
This will get solved when I somewhen have the time to do #107 in the form of a `endRequirement` function.
I started working on it some time ago but delayed it for now.
#213 is limited in it's use case. So ^^^ would give more options.

**Comment by imranbarbhuiya** [comment]
I believe this can be fixed by adding `giveaway.checkUserEntry` in this filter

https://github.com/Androz2091/discord-giveaways/blob/08b0a4152571bb57be314df98ce34562d43a5e1f/src/Manager.js#L284

**Comment by Nico105** [comment]
what should be done about the case, that a drop "never" reaches it's winnerCount.
cause that could potentially lead to dead drops littering the system.
should there be a data deletion after e.g. 1 week, when a drop hasn't ended yet?

**Comment by imranbarbhuiya** [comment]
> should there be a data deletion after e.g. 1 week, when a drop hasn't ended yet?

Yeah it'll be cool

**Comment by Nico105** [comment]
v5.2.0 was released.
(Should fix the issue, if I didn't forget smth XD)
