### ISSUE TITLE
Runaway Regular Expression, possibly catastrophic backtracking

### ISSUE THREAD

**Issue by Compositr** [Androz2091/discord-giveaways#430]
**Describe the bug**  

The regular expression at [Line 336 of Giveaway.js](https://github.com/Androz2091/discord-giveaways/blob/master/src/Giveaway.js#L336) can cause catastrophic backtracking if given a string like: `{{zzzzzzzzzzzzzzz`...

**Error**  

![image](https://user-images.githubusercontent.com/43405050/151898840-bdb159af-381f-4eb4-8b09-5c99d5938d60.png)

**To Reproduce**  

n/a

**Expected behavior**  

A faster/more efficient Regex which is not prone to backtracking

**Screenshots**  

![image](https://user-images.githubusercontent.com/43405050/151899016-0d867589-bc32-4dd4-9222-ecbd41c708e7.png)

**Additional context**

* `discord-giveaways` version: 776e2c002ce5ac3c8c511f06b03d2f2e5d588b4b
* `discord.js` version: 13.3.1
* Custom Database (if you use one): MongoDB

n/a

**Comment by Nico105** [comment]
https://regex101.com/r/CRUAUF/1 was suggested by imranbarbhuiya.
It should do the job, unless someone has got some other idea?

**Comment by imranbarbhuiya** [comment]
If this is also showing the same error then ignore this error. Why I'm saying is bcz this regex match is done in strings provided by the bot developer not users. So developers should know what string they are providing to avoid exponential backtracking. The above provided regex is much faster but it'll also allow unlimited numbers of letters bc this is the purpose of this regex. It should allow anything inside `{}`. But it won't cause any ddos attack.

**Comment by Nico105** [comment]
5.2.1 was released
