### ISSUE TITLE
Discord.JS v14 support

### ISSUE THREAD

**Issue by bad-boy-discord** [Androz2091/discord-giveaways#441]
Hello, will there be DiscordJS version 14 support soon?
Every time I update modules, I get the error "Discord.Intents is not a constructor", and I have to fix it manually.

**Comment by Dragonizedpizza** [comment]
> Hello, will there be DiscordJS version 14 support soon? Every time I update modules, I get the error "Discord.Intents is not a constructor", and I have to fix it manually.

You can make a GitHub fork, fix the issue there and clone that if its too much effort :+1:
