### ISSUE TITLE
No Winner

### ISSUE THREAD

**Issue by Justman10000** [Androz2091/discord-giveaways#457]
**Describe the bug**  

In giveaways no winners will be drawn

**Error**  

![grafik](https://user-images.githubusercontent.com/49990629/163959235-79d377d4-548e-4954-b72f-4805ee6fd5ba.png)

PS: Everything on my bot is in German

**To Reproduce**  

- Create a GiveAway
- Take part
- Wait of the End
- No Winners

**Expected behavior**  

The bot triggers the variable noWinner...

**Additional context**

* `discord-giveaways` version: newest
* `discord.js` version: newest
* Custom Database (if you use one): No (.json)

**Comment by Nico105** [comment]
does it happen for every giveaway you start, or does it only happens sometimes = randomly?

**Comment by Justman10000** [comment]
> does it happen for every giveaway you start, or does it only happen sometimes = randomly?

With every giveaway

**Comment by Nico105** [comment]
What are your manager options

**Comment by Justman10000** [comment]
> What are your manager options

```javascript
const manager = new GiveawaysManager(client, {
    storage: './giveaways.json',
    default: {
        botsCanWin: false,
        exemptPermissions: 'ADMINISTRATOR',
        embedColor: '#3a9b75',
        embedColorEnd: '#ff0000',
        reaction: '🎉',
        lastChance: {
            enabled: true,
            embedColor: '#ff0000',
            content: 'LETZTE CHANCE! Noch schnell teilnehmen'
        }
    }
});
```

**Comment by Nico105** [comment]
> ```js
> exemptPermissions: 'ADMINISTRATOR'
> ```

`exemptPermissions: ['ADMINISTRATOR']`

cause its supposed to be an array
