### ISSUE TITLE
No Winner

### ISSUE THREAD

**Issue by Sand200** [Androz2091/discord-giveaways#458]
Hello! My giveaways does not choose a winner when the giveaway ends.

Here's my manager code

const { GiveawaysManager } = require("discord-giveaways");
client.giveawaysManager = new GiveawaysManager(client, {
  storage: "./storage/giveaways.json",
  default: {
    botsCanWin: false,
    embedColor: "#E9A5B7",
    embedColorEnd: "#E9A5B7",
    reaction: "<a:tada:960229635122139156>", 
  },
});

**Comment by Nico105** [comment]
your provided reaction seems odd.
have you tried it with a normal emoji?
