### ISSUE TITLE
[object Object] when want to list all giveaways

### ISSUE THREAD

**Issue by NicoHd105** [Androz2091/discord-giveaways#46]
So I took the line "let allGiveaways = client.giveawaysManager.giveaways;" from the "guide" for this package and then i created an embed ".addField('Current active giveaways:', allGiveaways, true)" and then i want  to send it "message.channel.send(embed)" but it only returns some [object Object], that also happens when i want to use "not ended giveaways". Why?

**Comment by Snowflake107** [comment]
You can't send Array/Object like that. Parse the required items from the Array/object and send it a message.

**Comment by NicoHd105** [comment]
Ok sry
