### ISSUE TITLE
Animated Giveaway Reaction - Not working

### ISSUE THREAD

**Issue by Sand200** [Androz2091/discord-giveaways#461]

**Comment by Sand200** [comment]
> please send how you provided the reaction


<a:Tada:960229635122139156>

it's not an invaild emoji

**Comment by Nico105** [comment]
_Can't really test cause I'm too broke for nitro (can't get animated emoji id/to lazy to search>_
did the reaction get put onto the embed or not?

**Comment by oMvhmoud** [comment]
just use emoji id in reaction option not the emoji code
