### ISSUE TITLE
Mongoose - The schema don't get deleted on db

### ISSUE THREAD

**Issue by TheDogHusky** [Androz2091/discord-giveaways#466]
No issue like this one created

**Describe the bug**  

I used the example for mongodb, just edited it for my actual structure (file of model: ./models/giveaway.js (and it works), file of manager: ./utils/giveawaymanager.js (it still work on exports and all)). When I start a giveaway, it creates a document for the giveaway, everything's fine. Then, when it ends, or I end it manually, the document don't get deleted. (btw when i delete it manually i get the error that it can't find a giveaway with this message id after ending it manually and when it tries to end it automatically.)

**Error**  

A screenshot or the text block of the error if there is one.

No error for the document deletion, but the error for the auto end it "Ending aborted because giveaway with message Id 984443503364935756could not get edited. Try later!" even if a giveaway exists on db and with the message id.

**To Reproduce**  

1 - Make a file named giveawaymanager.js where you put the example code
2 - Make a file named giveaway.js for the model, enter the model and export it (module.exports = mongoose.model("Giveaways", giveawayschema);)
3 - In the giveawaymanager.js file put this line: `const giveawayModel = require('./giveaway');`
4 - In index.js, make a client, a giveaway manager and a mongoose db connection working.
5 - Start a giveaway, end it manually and the document don't get deleted + it gets error after trying to delete it a the end time.

**Expected behavior**  

It's expected to delete the document on mongodb database + not supposed to have error if i ended the giveaway manually before.

**Screenshots**  

https://imgur.com/FImHlDo
https://imgur.com/f7xYkNH
https://imgur.com/QSaa68x
https://imgur.com/32TfLEW

**Additional context**

* `discord-giveaways` version: 5.2.1
* `discord.js` version: 13.8.0
* Custom Database (if you use one): MongoDB (Mongoose 6.3.5)

**Comment by Nico105** [comment]
giveaway data does not get deleted by default.
you have to use the `endedGiveawaysLifetime` manager option.

for the "coult not get edited" error tho, I will have to investigate more

**Comment by Nico105** [comment]
" but the error for the auto end it"
"it gets error after trying to delete it a the end time."
=> Ending aborted because giveaway with

could you describe the things you did to get a this a bit more?

**Comment by TheDogHusky** [comment]
So, i try to end the giveaway with the command, first, it's supposed to reply after and i just get an interaction failed then the giveaways stops. After, the package tries to delete it manually but it gets this error.
Code of the end.js command:
```js
module.exports = {
    name: "end",
    description: '🎉 Mettre fin à un giveaway déjà lancé',
    options: [
        {
            name: 'giveaway',
            description: 'Mettre fin au giveaway (message ID ou prix du giveaway)',
            type: 3,
            required: true
        }
    ],
    run: async (client, interaction) => {

        // If the member doesn't have enough permissions
        if (!interaction.member.permissions.has('MANAGE_MESSAGES') && !interaction.member.roles.cache.some((r) => r.name === "Giveaways")) {
            return interaction.reply({
                content: '<:Non_:844228495542452296> **Vous devez disposer des autorisations de gestion des messages pour terminer des giveaways.**',
                ephemeral: true
            });
        }

        const query = interaction.options.getString('giveaway');

        // fetching the giveaway with message Id or prize
        const giveaway =
            // Search with giveaway prize
            client.giveawaysManager.giveaways.find((g) => g.prize === query && g.guildId === interaction.guild.id) ||
            // Search with giveaway Id
            client.giveawaysManager.giveaways.find((g) => g.messageId === query && g.guildId === interaction.guild.id);

        // If no giveaway was found with the corresponding input
        if (!giveaway) {
            return interaction.reply({
                content: 'Impossible de trouver un giveaway pour `' + query + '`.',
                ephemeral: true
            });
        }

        if (giveaway.ended) {
            return interaction.reply({
                content: 'Ce giveaway est déjà terminé !',
                ephemeral: true
            });
        }

        // Edit the giveaway
        client.giveawaysManager.end(giveaway.messageId)
            // Success message
            .then(() => {
                // Success message
                interaction.reply(`**[Ce giveaway](https://discord.com/channels/${giveaway.guildId}/${giveaway.channelId}/${giveaway.messageId}) à été terminé !**`);
            })
            .catch((e) => {
                interaction.reply({
                    content: e,
                    ephemeral: true
                });
            });

    }
};
```

**Comment by TheDogHusky** [comment]
and for the ednedGiveawayLifetime it's ms passed or something else?

**Comment by Nico105** [comment]
> and for the ednedGiveawayLifetime it's ms passed or something else?

ms yeah

**Comment by TheDogHusky** [comment]
huh.. I passed 10000 as parameter (10s) and after 10 seconds the document doesn't get deleted

**Comment by TheDogHusky** [comment]
**__I found the issue__**
> The giveaway isn't marked as ended and doesn't get deleted. I found it while debugging and logging every giveaway on the _checkGiveaways() function.
> The ended property doesn't get updated. Still ended: false.

**Comment by TheDogHusky** [comment]
@Nico105 need to patch that

**Comment by Nico105** [comment]
_if it would be that easy_
could you provide your discord.js client options?

**Comment by TheDogHusky** [comment]
@Nico105 ?

**Comment by TheDogHusky** [comment]
@Nico105, so what’s the problem? I need to fix it fast so I can publish a mongo version of a certified bot, it’s really important.

**Comment by confusion0** [comment]
> So, i try to end the giveaway with the command, first, it's supposed to reply after and i just get an interaction failed then the giveaways stops. After, the package tries to delete it manually but it gets this error. Code of the end.js command:
> 
> ```js
> module.exports = {
>     name: "end",
>     description: '🎉 Mettre fin à un giveaway déjà lancé',
>     options: [
>         {
>             name: 'giveaway',
>             description: 'Mettre fin au giveaway (message ID ou prix du giveaway)',
>             type: 3,
>             required: true
>         }
>     ],
>     run: async (client, interaction) => {
> 
>         // If the member doesn't have enough permissions
>         if (!interaction.member.permissions.has('MANAGE_MESSAGES') && !interaction.member.roles.cache.some((r) => r.name === "Giveaways")) {
>             return interaction.reply({
>                 content: '<:Non_:844228495542452296> **Vous devez disposer des autorisations de gestion des messages pour terminer des giveaways.**',
>                 ephemeral: true
>             });
>         }
> 
>         const query = interaction.options.getString('giveaway');
> 
>         // fetching the giveaway with message Id or prize
>         const giveaway =
>             // Search with giveaway prize
>             client.giveawaysManager.giveaways.find((g) => g.prize === query && g.guildId === interaction.guild.id) ||
>             // Search with giveaway Id
>             client.giveawaysManager.giveaways.find((g) => g.messageId === query && g.guildId === interaction.guild.id);
> 
>         // If no giveaway was found with the corresponding input
>         if (!giveaway) {
>             return interaction.reply({
>                 content: 'Impossible de trouver un giveaway pour `' + query + '`.',
>                 ephemeral: true
>             });
>         }
> 
>         if (giveaway.ended) {
>             return interaction.reply({
>                 content: 'Ce giveaway est déjà terminé !',
>                 ephemeral: true
>             });
>         }
> 
>         // Edit the giveaway
>         client.giveawaysManager.end(giveaway.messageId)
>             // Success message
>             .then(() => {
>                 // Success message
>                 interaction.reply(`**[Ce giveaway](https://discord.com/channels/${giveaway.guildId}/${giveaway.channelId}/${giveaway.messageId}) à été terminé !**`);
>             })
>             .catch((e) => {
>                 interaction.reply({
>                     content: e,
>                     ephemeral: true
>                 });
>             });
> 
>     }
> };
> ```

Instead of using the .end() function, try using the .edit() function and set the end timestamp parameter to the current date. Example: 
```js
client.giveawaysManager.edit(giveaway.messageId, {
            setEndTimestamp: Date.now()
})
```

**Comment by Nico105** [comment]
> @Nico105 ?

try updating to the latest version

**Comment by confusion0** [comment]
you guys should add a feature that after a set amount of time, ended giveaways will get permanently deleted from the db

**Comment by confusion0** [comment]
ah, i didnt notice lol

**Comment by TheDogHusky** [comment]
Thank you very much, it's finally solved with the new Update.
