### ISSUE TITLE
[Feature Request] Editing giveaway messages

### ISSUE THREAD

**Issue by Shashank3736** [Androz2091/discord-giveaways#47]
Is there any way I can edit inviteToParticipate option. After giveaway starts. by using edit config

**Comment by Androz2091** [comment]
Currently there is no way to update messages for a giveaway. What would be the use case?

**Comment by ShreyashKira** [comment]
Actually that part shows the requirement to join. If I edit giveaways requirements then I need to edit that part too. Like last day we increase the requirement to join

**Comment by ShreyashKira** [comment]
Any update for me??

**Comment by Androz2091** [comment]
Oh, I see. A way to modify the messages will be added.

**Comment by wolfier74** [comment]
Good idea

**Comment by Androz2091** [comment]
:tada: v4.3.0 is now released and include a new `newMessages` property!
