### ISSUE TITLE
Discord.js V14

### ISSUE THREAD

**Issue by jonas-ell** [Androz2091/discord-giveaways#470]
I can't use the package with new Intents :/
![error](https://user-images.githubusercontent.com/45735514/179967647-f6116683-4440-481b-a659-ee2cf5db539f.png)
![code1](https://user-images.githubusercontent.com/45735514/179967697-5724559f-d666-4887-bb3b-387c3207c773.png)
![code2](https://user-images.githubusercontent.com/45735514/179967796-50a5e4f7-af26-4e60-b662-68bff4eae5b1.png)

**Comment by hocsinhgioitoan** [comment]
wait for merge pr :v it is coming

**Comment by hocsinhgioitoan** [comment]
https://github.com/Androz2091/discord-giveaways/pull/464

**Comment by Nico105** [comment]
✨ v6 has been released
