### ISSUE TITLE
Not getting giveaway info after restarting (quickmongo tested)

### ISSUE THREAD

**Issue by oMvhmoud** [Androz2091/discord-giveaways#473]
**Describe the bug**  

After restarting your node instance if you log your giveaways list it will show prize/msg id/channel id/etc as undefined.

**Error**  

![image](https://user-images.githubusercontent.com/40049200/182004610-0d40fbaf-1c74-4d77-98d6-b1f60a8797be.png)

**To Reproduce**  

1. Run a giveaway
2. Restart your node instance
3. Log your giveaway list
4. You will find every giveaway value undefined and giveaways not ending

**Expected behavior**  

![image](https://user-images.githubusercontent.com/40049200/182004615-9ae83b9b-f008-4b16-9aa8-c35e5dd4f555.png)

**Additional context**

* `discord-giveaways` version: 5.2.2
* `discord.js` version: 13.9.2
* Custom Database (if you use one): quickmongo latest version.

**Steps to Fix**

1. Go to node_modules/discord-giveaways/src/Manager.js
2. Create a new line at 679
3. Type in that line: `rawGiveaways = rawGiveaways.map((giveaway) => giveaway.data);`
4. Save the file
5. Restart your node instance
6. Boom you fixed the problem

**Hope you publish v5.2.3 with fixing that. (idk if its out of support rn)**

**Comment by Nico105** [comment]
_Quickmongo introduced the responsible change with its v5.0.1_
Adjusted the example in v6.0.1
