### ISSUE TITLE
the discord-giveaways isnt installing

### ISSUE THREAD

**Issue by DanSpared** [Androz2091/discord-giveaways#483]
![Screenshot 2022-10-08 180745](https://user-images.githubusercontent.com/88373669/194714197-bda7d6ee-6139-47c6-83b6-e18036652722.png)

**Describe the bug**  

**Error**  

A screenshot or the text block of the error if there is one.

**To Reproduce**  

**Expected behavior**  

**Screenshots**  

**Additional context**

* `discord-giveaways` version:
* `discord.js` version:
* Custom Database (if you use one):

**Comment by Nico105** [comment]
Install v5 if you are still using discord.js v13
