### ISSUE TITLE
Giveaway Author not showing!

### ISSUE THREAD

**Issue by Cupcake-Development** [Androz2091/discord-giveaways#487]
Hello, 

I created a bot using this npm in d.js v14..
I added hostedBy: "Hostedby: {this.hostedBy}"

But its not showing in giveaway message how can i make it show in giveaway message..
![Uploading IMG_20221215_001317.jpg…]()

**Comment by reinacchi** [comment]
Your attachment image doesn't seem to be loaded correctly. Can you resend that or provide us with the code you're using instead?

**Comment by Nico105** [comment]
```js
messages: { 
    hostedBy: "HostedBy: {this.hostedBy}"
},
hostedBy: interaction.user
```

**Comment by Cupcake-Development** [comment]
Got it Thankyou for the help. ❤
