### ISSUE TITLE
Reset bot

### ISSUE THREAD

**Issue by ReturnTheAcuatic** [Androz2091/discord-giveaways#488]
Let me tell you, today I was looking at modules and I found one that caught my attention (discord giveway), I read your guides a bit and some examples and compensated by implementing the codes to my bot, after implementing the codes I run the first command (/start giveaways) everything was normal, but when I chose the winner the bot restarted

Code:
![Screenshot_2022-12-17-03-12-44-703-edit_com android chrome](https://user-images.githubusercontent.com/100498298/208232597-a7cdded6-cce2-4d14-95a6-6a67c87a6bad.jpg)

**Comment by Nico105** [comment]
Your code seems fine, and the module cannot restart a bot itself.
Do you maybe have some system in place which auto restarts on error like nodemon? Cause then the cause was some error, which you could look out for.
