### ISSUE TITLE
Stop displaying so many logs when a message is not found

### ISSUE THREAD

**Issue by NicoHd105** [Androz2091/discord-giveaways#49]
So yeah, i deleted a giveaway message manually and from then on the bot spammed the log with "Unable to fetch message with ID 712700687082979339." even when i restarted it, it still continued. I guess that happens because he wants to update the duration. Is there a fix for this or is this a bug I discovered?

**Comment by NicoHd105** [comment]
![image](https://user-images.githubusercontent.com/63612668/82473707-4894bd00-9aca-11ea-8ae0-e5710c9a7419.png)

**Comment by NicoHd105** [comment]
Ok, I restarted again and now it stopped, so i guess there is a timer somewhere that stops sending that error message after a time.

**Comment by NicoHd105** [comment]
But still maybe make that the timer is a little bit faster/less time till stop

**Comment by NicoHd105** [comment]
thanks

**Comment by ShreyashKira** [comment]
I have solution for it just use the delete command and delete that giveaway. Then it stops saying that in the console.

**Comment by Androz2091** [comment]
Fixed. Install v4.1.1 or higher 👍
