### ISSUE TITLE
Question: Where can i add emojis and stuff to the giveaway embed?

### ISSUE THREAD

**Issue by NicoHd105** [Androz2091/discord-giveaways#51]
So i tried adding my emji into the module folder src>utils and then into the cosnt GiveawaysMessages and the "Property string" above that but none of that worked, so is it even possible and when yes where?

**Comment by Androz2091** [comment]
Hello @NicoHd105. Instead of editing the code of the package yourself, you should look at the `messages` property, here: https://github.com/Androz2091/discord-giveaways#-translation

**Comment by NicoHd105** [comment]
oh fu** totally forgot about that sry for my "stupidness" but thanks (i think i got alzeimer lol)

**Comment by NicoHd105** [comment]
but to add a icon into the footer, i will have to edit smth in the package or i will have to extend smth right?

**Comment by Androz2091** [comment]
Yes, for this modification you'll need to edit the package.
