### ISSUE TITLE
Giveaways duration: "val is not a non-empty string or a valid number" when awaitMessages

### ISSUE THREAD

**Issue by NicoHd105** [Androz2091/discord-giveaways#53]
So, i tried to make the whole start process into a conversation but when I provide a giveaway duration then it just logs the error: [UnhandledPromiseRejectionWarning: Error: val is not a non-empty string or a valid number. val={"channelID":"711670460529770596","deleted":false,"id":"714729185372798986","type":"DEFAULT","content":"1d","authorID":"391243477058584588","pinned":false,"tts":false,"nonce":"714729185171472384","system":false,"embeds":[],"attachments":[],"createdTimestamp":1590475116819,"editedTimestamp":null,"webhookID":null,"applicationID":null,"activity":null,"flags":0,"reference":null,"guildID":"672002616372363274","cleanContent":"1d"}](url)

my code: // Giveaway duration
            await message.channel.send(`Please provide a duration for the giveaway!`)
            const response2 = await message.channel.awaitMessages(m => m.author.id === message.author.id, { max: 1 });
            let giveawayDuration = response2.first();
            // If the duration isn't valid
            if(!giveawayDuration || isNaN(ms(giveawayDuration))){
                return message.channel.send(':x: You have to specify a valid duration!');
            }
The reason for this is sometimes: if(!giveawayDuration || isNaN(ms(giveawayDuration))){ or sometimes: "time: ms(giveawayDuration)" (at the startoptions) 

But i mean i provided a a valid number and a "format" btw it didn't work with "1000" also so i guess it's not a error from ms but then what is the reason cause i mean when i log the giveaway duration it shows my message so i will maybe have to change smth in you package? or did i just made i big mistake?

(btw sry for asking so much)

**Comment by Androz2091** [comment]
Hello,
Instead of passing the full message object to `ms`, just send the message content:
```js
if(!giveawayDuration || isNaN(ms(giveawayDuration))){
    return message.channel.send('❌ You have to specify a valid duration!');
}
```
will become:
```js
if(!giveawayDuration || isNaN(ms(giveawayDuration.content))){
    return message.channel.send('❌ You have to specify a valid duration!');
}
```

If you have other questions and you don't know if it really concerns discord-giveaways, you can ask first on **[this development server](https://discord.gg/hw87VUQ)**.

**Comment by NicoHd105** [comment]
ok thank you very much, but if anyone sees this comment, you also have to add ".content" at "time: ms(giveawayDuration)"
so that it is "time: ms(giveawayDuration.content)"
