### ISSUE TITLE
[object Object] as prize after giveaway ended

### ISSUE THREAD

**Issue by NicoHd105** [Androz2091/discord-giveaways#54]
![image](https://user-images.githubusercontent.com/63612668/82883999-743cfa80-9f43-11ea-9990-21d8a37a3f05.png)

So this isn't caused by me right? this is a bug i guess..., btw but i haven't upgraded to the newest version yet. but it only happens sometimes

![image](https://user-images.githubusercontent.com/63612668/82884194-b36b4b80-9f43-11ea-9152-a1bbfba0327e.png)

I tried it again and then it worked so idk

**Comment by Androz2091** [comment]
Can you try to upgrade discord-giveaways to v4.2.1?

**Comment by NicoHd105** [comment]
it seems to be fixed i guess but now something else (funny) happens 
![image](https://user-images.githubusercontent.com/63612668/82886049-46a58080-9f46-11ea-90f1-2d3b42cefc7c.png)

**Comment by NicoHd105** [comment]
thats you btw

**Comment by NicoHd105** [comment]
no error btw

**Comment by Androz2091** [comment]
Oh, shit. Fixed in v4.1.3.

**Comment by NicoHd105** [comment]
and now it cannot provide a winner and the countwdown stops at 1s
![image](https://user-images.githubusercontent.com/63612668/82888634-df89cb00-9f49-11ea-9c3d-14ab1ae2467c.png)

ok somehow it finished now but still dind't provide a winner
and it repeats the error message on and on for the one that cannot end
