### ISSUE TITLE
[ISSUE] Multiple ends

### ISSUE THREAD

**Issue by ShreyashKira** [Androz2091/discord-giveaways#57]
Ok so last time the bot trigger 3 winners even idk why. The no. of winner selected 1. Even its like giveaway ended 3 times becoj the bot dms me 3 time which i added in giveawayEnd event.

**Comment by Androz2091** [comment]
Hello @ShreyashKira,
Which version of discord-giveaways are you using?

**Comment by ShreyashKira** [comment]
4.1.0 version. BTW i face this problem first time

**Comment by Androz2091** [comment]
Can you upgrade to the latest version (v4.1.5) please?

**Comment by ShreyashKira** [comment]
Yahh i upgraded it to v4.1.5 and run a giveaway for 2min and i participated alone and it do not show any error. But i m not able to find out why this occur.

**Comment by Androz2091** [comment]
v4.1.0 had some issues that are resolved in v4.1.5

**Comment by Androz2091** [comment]
Is your problem fixed?

**Comment by ShreyashKira** [comment]
I tried on multiple giveaways and it works fine so yahh it is solved, Thx for your help i love your package alot 🙂
