### ISSUE TITLE
Giveaway stops after bot restarts.

### ISSUE THREAD

**Issue by xenowing** [Androz2091/discord-giveaways#6]
Hi, Giveaway stops after bot restart. How to fix that?

**Comment by Androz2091** [comment]
Hmm... That's not normal
Can you show me your code please?

**Comment by Androz2091** [comment]
@xenowing? Can I close the issue?

**Comment by xenowing** [comment]
@Androz2091 I am using the same code that you have provided in example.

**Comment by Androz2091** [comment]
And you really don't have any error?

**Comment by xenowing** [comment]
@Androz2091 yIt shows this on starting the giveaway ```
{ ID: undefined,
  messageID: '623143637617999882',
  channelID: '553258780452978698',
  endAt: undefined }```

**Comment by Androz2091** [comment]
And do you have the problem each time you try to start a new giveaway? Or only sometimes?

**Comment by xenowing** [comment]
Thanks! Its fixed now :)
