### ISSUE TITLE
[DB] MongoDB support

### ISSUE THREAD

**Issue by misa-coder** [Androz2091/discord-giveaways#60]
Is this npm module support MongoDB if yes how to do that. I have 0 knowledge about MongoDB and I want to use that so that my other bots can also read db.

**Comment by misa-coder** [comment]
Is there any update for me????

**Comment by Androz2091** [comment]
This package supports MongoDB, but there is no example at this time.

**Comment by misa-coder** [comment]
Oof sad! I may try t learn noSql db

**Comment by powerflips** [comment]
I also wanted to make it work with mongodb, but I also have zero knowledge and I don't know how to do it, even though I tried in various ways, it always went wrong and I never succeeded

**Comment by misa-coder** [comment]
There are too many users who want a mongoDB example. Let's see if he add index4mongodb.js in his example bot.

**Comment by powerflips** [comment]
yes it would be very nice, let's wait

**Comment by Akurejs** [comment]
To date, no MongoDB example has come out

**Comment by NicoHd105** [comment]
Look at the #90 issue there's a example with quickmongo, so a wrapper for mongoDB if that is fine for you

**Comment by misa-coder** [comment]
Solution in issue #90 [here](https://github.com/Androz2091/discord-giveaways/issues/90#issuecomment-668409524)
