### ISSUE TITLE
Enhancement Giveaway drops

### ISSUE THREAD

**Issue by NicoHd105** [Androz2091/discord-giveaways#61]
So it would be cool if there was the option/system to create a giveaway drop which would mean that the first person who enters the giveaway would win it.

**Comment by misa-coder** [comment]
You can actually make it by using giveawayReactioAdd event. End the giveaway after first reaction of this giveaway actually a drop. Make sure giveawayReactioAdd event also trigger when your bot first time react on that msg. So first filter the user then end.
