### ISSUE TITLE
Unable to get the channel of the giveaway

### ISSUE THREAD

**Issue by NicoHd105** [Androz2091/discord-giveaways#63]
Unable to get the channel of the giveaway with message ID 716975896216469556.

what does that mean? cause i used the "list giveaways" cmd and it displayed about 10 but on the whole test server no giveaway is active anymore so idk maybe we deleted a channel but then why are the giveaways still saved as active?
or at least, how could i delete them from the databse?

**Comment by misa-coder** [comment]
giveaway is saved in db for reroll function. To delete them use delete function.
For e.g: 
client.on("message", (message) => {

    const args = message.content.slice(settings.prefix.length).trim().split(/ +/g);
    const command = args.shift().toLowerCase();

    if(command === "delete"){
        let messageID = args[0];
        client.giveawaysManager.delete(messageID).then(() => {
            message.channel.send("Success! Giveaway deleted!");
        }).catch((err) => {
            message.channel.send("No giveaway found for "+messageID+", please check and try again");
        });
    }

**Comment by NicoHd105** [comment]
that is why the error happens... if i want to end or delete that id it says: " Unable to get the channel of the giveaway "ID" cause the channel was probably deleted

**Comment by NicoHd105** [comment]
Now i just deleted the json.sqlite file where the data was stored what just deleted that mysterious giveaways
