### ISSUE TITLE
How do you use the .json file to save data?

### ISSUE THREAD

**Issue by gavserve** [Androz2091/discord-giveaways#65]
I created a file named storage.json, but what am I supposed to put in there?

I get this error: SyntaxError: The storage file is not properly formatted (Unexpected end of JSON input).

**Comment by NicoHd105** [comment]
You don't have to create one, the module will do it itself/there should already be one "giveaways.json" delete this one and then start the bot and try to make a giveaway, it should work

**Comment by gavserve** [comment]
Thanks!
