### ISSUE TITLE
Limit Giveaways

### ISSUE THREAD

**Issue by inxec** [Androz2091/discord-giveaways#66]
Is there a way to limit the amount giveaways per server can run? Example: 10 giveaways in each server

Because, crazy people MIGHT abuse the bot and make tons of nonsense giveaways, and eventually crash the bot

**Comment by SimonLeclere** [comment]
When launching a giveaway, list those already active with the code below:
```js
    let giveaways = client.giveawaysManager.giveaways.filter((g) => g.guildID === message.guild.id);
    // Keep the giveaways that are not ended
    let notEndedGiveaways = giveaways.filter((g) => !g.ended);
```
And check if the length of notEndedGiveaways is smaller than 10, if it is not cancel the command
