### ISSUE TITLE
Giveaways don't keep going automatically after bot restarts (using Quick.db as database)

### ISSUE THREAD

**Issue by Gav-King** [Androz2091/discord-giveaways#68]
Is there any way you could make the giveaway keep going if the bot restarts?

**Comment by NicoHd105** [comment]
It does already do that

**Comment by NicoHd105** [comment]
if you have 10m left before you restart then after the restart it will tell smth like 9m

**Comment by gavserve** [comment]
It didn't do it for me.

**Comment by NicoHd105** [comment]
what did it do then? nothing? so the giveaway just freezed? and another q do u use the normal .json file or a DB (which?) to store the data?

**Comment by gavserve** [comment]
I'm using quick.db, and the giveaway just freezes.

**Comment by NicoHd105** [comment]
did u use the axact example that was given by androz ?

**Comment by gavserve** [comment]
Yes.

**Comment by NicoHd105** [comment]
weird, i will try to get androz into here

**Comment by Androz2091** [comment]
Do you have any error in the terminal?

**Comment by gavserve** [comment]
Nope.

**Comment by powerflips** [comment]
Are you using heroku to host the bot? If so, that could be the problem.

**Comment by misa-coder** [comment]
I think your vps do not support self hosted db. Try mongoDB maybe your issue will be solved

**Comment by Androz2091** [comment]
Closed due to inactivity. Feel free to comment here if you are experiencing the same problem.
