### ISSUE TITLE
Question with Giveaways

### ISSUE THREAD

**Issue by NTMNathan** [Androz2091/discord-giveaways#71]
I've been using this module for my new Giveaways System and with quick.db as the db. I saw that you can list down all the Active Giveaways. Is it possible to get information about a specific Giveaway?
So you run `!ginfo <messageid>` and it will filter the array of Active Giveaways and get the message id giveaway info.

Also is it possible to create a walkthrough style Giveaway Command? Its basically a step by step where it uses message awaits instead of `!gstart <#channel> <duration> <winners> <prize>`

**Comment by misa-coder** [comment]
const giveaway = manager.giveaways.filter(g => g.messageID === args[0]) //this will provide you the info of a special giveaway.
You can do that interactive setup by using message collector. If you know how to do that.

**Comment by Androz2091** [comment]
If you want to get help to make the message collector, ask in [our development server](https://discord.gg/hw87VUQ).
