### ISSUE TITLE
CustomDB

### ISSUE THREAD

**Issue by ShreyashKira** [Androz2091/discord-giveaways#74]
Custom db have an error that even if i delete giveaway it do not load till we restart the complete bot.

**Comment by Androz2091** [comment]
Hello
Could you send your code that extends the Giveaways Manager with your own db functions please?

**Comment by ShreyashKira** [comment]
Yahh https://media.discordapp.net/attachments/695489872999219227/726468749703643216/custom_db.png?width=468&height=427

**Comment by ShreyashKira** [comment]
It do not work at all

**Comment by Androz2091** [comment]
Okay so you're using quick.db? And your bot is not shared?

**Comment by ShreyashKira** [comment]
Yes my bot is not sharded and i m using quick.db

**Comment by misa-coder** [comment]
Hmm I see delete giveaway do not work for customDB

**Comment by misa-coder** [comment]
Check #76 and try that in your index.js

**Comment by ShreyashKira** [comment]
thx @misa-coder it works :)
