### ISSUE TITLE
problem with indexquickdb.js logs 

### ISSUE THREAD

**Issue by powerflips** [Androz2091/discord-giveaways#80]
I am using index.js with quick.db in Androz's project and it has 2 codes that generate logs in the terminal of when the person reacts to emoji to participate in giveaway

`client.giveawaysManager.on("giveawayReactionAdded", (giveaway, member, reaction) => {
    console.log(`${member.user.tag} entered giveaway #${giveaway.messageID} (${reaction.emoji.name})`);
});

client.giveawaysManager.on("giveawayReactionRemoved", (giveaway, member, reaction) => {
    console.log(`${member.user.tag} unreact to giveaway #${giveaway.messageID} (${reaction.emoji.name})`);`

the giveawayReactionAdded log works normally, generating the log in the terminal of each person who participates in a giveaway

The giveawayReactionRemoved log when someone removes a reaction from a giveaway generates a terminal error

`TypeError: Cannot read property 'emoji' of undefined`

researching I found out that the problem comes directly from the discord-giveaways package in the manager.js file more precisely on line 84

`if (!reaction) return;
            if (packet.t === 'MESSAGE_REACTION_ADD') {
                this.emit('giveawayReactionAdded', giveaway, member, reaction);
            } else {
                this.emit('giveawayReactionRemoved', giveaway, member);`

as you can see in giveawayReactionRemoved is missing the reaction function
by correcting this through my computer the log worked normally without any error

the correction is `this.emit('giveawayReactionRemoved', giveaway, member, reaction);`

I wanted this to be fixed with a new version of the package put where I leave my bot online it is not possible for me to make a manual fix in Manager.js, because it is an instance I have no way to make changes to the packages that are installed automatically.

**Comment by Androz2091** [comment]
Hello
This should be fixed by v4.2.0. Install it and restart the bot (`npm install discord-giveaways@4.2.0`).
