### ISSUE TITLE
no winners

### ISSUE THREAD

**Issue by 3061LRTAGSPKJMORMRT** [Androz2091/discord-giveaways#81]
So there are no winners even after rerolling. I tried `exemptPermissions :	[]` but it still won't work

**Comment by misa-coder** [comment]
Will you mind showing the error you face

**Comment by powerflips** [comment]
it seems this error was after the new version 4.2 i am also having problems with the new version where there are no winners, there is also no error in the terminal. the giveaway only says Giveaway cancelled, in valid participations. let's wait for a fix

**Comment by misa-coder** [comment]
It starts when you updated your code to v12

**Comment by Androz2091** [comment]
Install v4.2.1, and it should work.
