### ISSUE TITLE
Undefined???

### ISSUE THREAD

**Issue by Lag01** [Androz2091/discord-giveaways#87]
I keep getting this error: `TypeError: Cannot read property 'pluralS' of undefined` while trying to start the giveaway with custom messages. without messages it works...

after defining pluralS in the `messages` option in the code, i got this error: `TypeError: Cannot read property 'endsWith' of undefined`

Any way to fix it?

**Comment by Androz2091** [comment]
Hello,
Could you send me your code? (where you create the GiveawaysManager instance + where you start the giveaway)

**Comment by Lag01** [comment]
Okay, 

- Giveaway manager instance
``const manager = new GiveawaysManager(client, {
    storage: './giveaways.json',
    updateCountdownEvery: 10000,
    default: {
        botsCanWin: false,
        exemptPermissions: [],
        embedColor: "BLURPLE",
        reaction: "🎉",
        messages: {
            giveaway: "🎉**GIVEAWAY!**🎉",
            giveawayEnded: ":( **Giveaway Ended.**",
            noWinner: "Giveaway has been cancelled, could not find valid participations."
        }
    }
});``

- Start giveaway
``client.giveawaysManager.start(channel, {
        time: ms(duration),
        prize: giveawayPrize,
        winnerCount: giveawayNumberWinners,
        hostedBy: message.author,
        messages: {
            giveaway: "🎉**GIVEAWAY!**🎉",
            giveawayEnded: ":( **Giveaway Ended.**",
            units: {
                pluralS: false
            }
        }
    });``

**Comment by Lag01** [comment]
@Androz2091 ?, anyone?

**Comment by NicoHd105** [comment]
Do you still face this issue with the latest version of this module? You should not, so please close this issue.
