### ISSUE TITLE
Editing giveaway embed without forking the project

### ISSUE THREAD

**Issue by SoftyMystic** [Androz2091/discord-giveaways#88]
Is it possible to add fields to the embed?

**Comment by NicoHd105** [comment]
I think just with editing the module folder, but if you want it in the descripttiln you could just add your text to the time message

**Comment by misa-coder** [comment]
@NicoHd105 do not recommend editing of node_modules folder it's better to make a fork and install that. But if @Androz2091 create an embed() function in manager and use that to create embed in start and after every editing then we can simply extend the GiveawayManager which support our custom embed.

**Comment by ririko5834** [comment]
Please add this

**Comment by Androz2091** [comment]
This is planned in v4.3.0
