### ISSUE TITLE
Restart Giveaway 

### ISSUE THREAD

**Issue by NikXxX** [Androz2091/discord-giveaways#9]
Can you do a restart giveaway command because sometimes when I start a giveaway I do shitty with it.
Can you do it please ?
Thanks,
By !CR3W#1754

**Comment by Androz2091** [comment]
To restart a giveaway, you need to use the `edit()` function. Here is an example of what you can do.
```Js
let giveaways = require("discord-giveaways");
let messageID = "330393908390"; // The ID of the giveaway to restart
let giveawayInfo = await giveaways.fetch(messageID);
let addTime = Date.now() + giveaway.time;
giveaways.edit(messageID, {
    setEndTimestamp: endTimestamp
});
```
