### ISSUE TITLE
Make a project trello

### ISSUE THREAD

**Issue by Shashank3736** [Androz2091/discord-giveaways#94]
Make a project Trello where we can see:
* Future updates you planned.
* Bugs which are already mentioned.
Many more...

**Comment by Mr-KayJayDee** [comment]
There is already a project section available for every github repositories. 👌

**Comment by Androz2091** [comment]
Yes, I think we will use GitHub projects and GitHub milestones.

**Comment by ShreyashKira** [comment]
Yeah, the GitHub project is really nice you can also add issues there as a tab.
