### ISSUE TITLE
Bonus entry

### ISSUE THREAD

**Issue by misa-coder** [Androz2091/discord-giveaways#95]
A way to increase chances to win giveaway for some participants.

**Comment by Androz2091** [comment]
It's a good idea, but a little hard to implement (for users). Do you have ideas on how we could add that? It would be an option passed to the `start()` method?

**Comment by misa-coder** [comment]
start method have a function name as `entries` this function need member parameter and return no. Of entries. Users need to set that function so

entries(member) //returns no. Of entries this member have.

And then you can do the roll stuff.

For e.g
entries: member => db.get(`entries_${member.guild.id}_${member.user.id}`) || 1

Now in roll() make an array that contain participants user id and push ids that many time a member have entries. And then get a random from it.

**Comment by hannesfant** [comment]
Would be really cool to have a method to add entries for a specific user too. Possible use cases could be buying more entries in a shop and additional entries for every server invite. Might be worth adding the hacktoberfest label to this to see if someone would be up for doing it. :)

**Comment by wolfier74** [comment]
This is nice idea

**Comment by Lebyy** [comment]
@Nico105 I think you should close this as it is already merged?

**Comment by Nico105** [comment]
It's only merged in `develop` so it's not officially available, so it wouldn't make sense to close this.

**Comment by Nico105** [comment]
🎉 v4.5.0 is now released!
