### ISSUE TITLE
bot crash

### ISSUE THREAD

**Issue by sambeano7** [Androz2091/discord-giveaways#98]
Mot bot works fine when I am created a giveaway but right when I am done answering the questions (I have it ask questions to fill out the time, winnercount, prizes) it crashes/restarts my bot....

**Comment by Androz2091** [comment]
Do you have a specific error, or a message in the logs? And could you send your full code please?

**Comment by sambeano7** [comment]
No specific error...and I've even tried the exact sample code you have and still just crashes my bot

**Comment by NicoHd105** [comment]
Are you still facing this issue? If yes, what discord.js version are you using? If no, please provide a solution if you have found one/did anything that fixed the issue and close this issue.

**Comment by Androz2091** [comment]
Closed due to inactivity
